### ISSUE TITLE
Gauge files should have gauge symbol against it

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#1]
VS code has support for symbols against a file type.
<img width="180" alt="screen shot 2017-08-02 at 4 01 26 pm" src="https://user-images.githubusercontent.com/6310197/28869881-e3676602-779b-11e7-9357-f7bb332cf950.png">

We should have gauge symbol against Gauge supported file types.

**Comment by zabil** [comment]
The current symbol for gauge spec as document is good enough
![symbol](https://user-images.githubusercontent.com/54427/34092539-f4efdbec-e3e9-11e7-80d1-3a6b0e202302.png)
