### ISSUE TITLE
Running one project should not show errors from another project.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#103]
**Expected behavior**
Running one project should not show errors from another project.

**Actual behavior**
Getting parse errors of a different project

**Steps to replicate**
* Create project `parse-errors`
* Create project `other`
* Add a circular reference error in project `parse-errors`
* Add both projects to workspace
* Run scenario from project `other`

>Note: The errors on the console. 

>Note: `Run Scenario` command from command palette is getting an error `Cannot read property uri of undefined`

**Comment by Apoorva-GA** [comment]
The above issue is not replicable. But found an other issue.

`Run Scenario` command from command palette(when the curser focus is not in the scenario context) is getting an error `Path must be a string. Received undefined`.

Fix should be available in gauge-vscode nightly >= 17/01/18
