### ISSUE TITLE
[Workspace] Unable to run Commands from the palette 

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#106]
**Expected behavior**
Should be able to execute commands from the palette

**Actual behavior**
Getting command not found

<img width="675" alt="specificationall" src="https://user-images.githubusercontent.com/6310197/35080156-d7716c56-fc31-11e7-8ce2-136008f8e0db.png">

![image](https://user-images.githubusercontent.com/6310197/35080183-0124685a-fc32-11e7-9f43-38f8132658bc.png)

![image](https://user-images.githubusercontent.com/6310197/35080288-8b41e2ba-fc32-11e7-8bb6-a4a8493e21d1.png)

![UriUndefined.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46dd8693168c87ac89e0b146a01fbcd6395428792c07b7692ac7b67eea462350090a18af120d0b44f8ff892ba2e73f238f5e19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bd8c4ec4e03425e08a874a2c53.png)

**Steps to replicate**
* Open [LSP Project](https://github.com/getgauge/gauge-lsp-tests) - data/testdata.code-workspace 
* Run all specifications of a project
* Now Run commands from the command palette.

**Version**
gauge-0.0.4.nightly-2018-01-17.vsix

**Comment by sguptatw** [comment]
For running a specification and scenario we need to have specification file open. Instead of giving error, we can show a warning similar to

<img width="674" alt="warningnospecification" src="https://user-images.githubusercontent.com/6310197/35084520-636338c6-fc4a-11e7-8f34-cc4eab0f852b.png">

The message can be : `No gauge specification file open`

**Comment by sguptatw** [comment]
Getting the `Cannot read property 'uri' of undefined` after selecting a scenario for execution as well as when you are in scenario context.

**Comment by sguptatw** [comment]
**Question**
If a specification file is not open, but in test explorer a scenario/specification is selected - What should be the behavior of `Run scenario/specification`?

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >=18/01/18
