### ISSUE TITLE
External library paths are appended with project root path

### ISSUE THREAD

**Issue by riju91** [getgauge/gauge-vscode#107]
Expected behavior
When run from vscode, external library path should not be appended with project root path

Current behavior
When run from vscode, external library path is getting appended with project root path

Version
gauge-0.0.4.nightly-2018-01-16

**Comment by sguptatw** [comment]
**Steps to replicate**
* run project - 
[gauge-lsp-tests (Errors).zip](https://github.com/getgauge/gauge-vscode/files/1651042/gauge-lsp-tests.Errors.zip)
