### ISSUE TITLE
Add Debugging support with JS runner

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#108]
Should be able to debug step implementations with javascript runner.

**Comment by Apoorva-GA** [comment]
Should be available in gauge, gauge-js and gauge-vscode nightly >= 02/02/18

**Comment by sguptatw** [comment]
**Blockers**
- [ ] Debugger is getting attached after the execution - https://github.com/getgauge/gauge-vscode/issues/125
- [ ] Debugger should get detached when execution is stopped from the command palette - https://github.com/getgauge/gauge-vscode/issues/124

**Comment by sguptatw** [comment]
**Question**
Currently the debug console is empty. What information should get printed on it?
