### ISSUE TITLE
Indicate an error occurred

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#110]
**Current behaviour**
When an error occurs, like request time out or connection closed - the errors are shown in the output panel 

**Proposed behaviour**
Apart from showing the errors in the panel, indicate to the user that an error occurred. 

This will help to report the issue better. As we will be able to clearly see when a issue occurs.

**Comment by nehashri** [comment]
There are a lot of errors that are sent to VSCode from Gauge. 

Some errors, for example, Code lens request failure may occur when the user is authoring a spec, and a code lens request is received by Gauge from VSCode. In this case, the code lens request cannot be processed if there are parse errors in the file(it can be very frequent as the user is still authoring the spec). Showing a error notification in VSCode can be quite annoying in this case. 

However, it would be useful to show genuine errors from Gauge as an error notification. We need to see if we can differentiate such errors and show only the critical ones as an error notification.
