### ISSUE TITLE
Spec Explorer should update when a file is moved or deleted

### ISSUE THREAD

**Issue by riju91** [getgauge/gauge-vscode#111]
Expected Behavior:
Spec Explorer should update when a file is moved or deleted

Actual Behavior:
Spec explorer only reflects file move or deletion once it is explicitly refreshed

**Comment by riju91** [comment]
should be available in nightly >= 2018-01-29

**Comment by sguptatw** [comment]
When I move a spec file, I get the following error.

**Steps to replicate**
* Create a basic project
* Delete the `example.spec`
* Create a new spec `something.spec`
* Move to folder `specs/ooo`

>We get the following error-

<img width="954" alt="movefileerror" src="https://user-images.githubusercontent.com/6310197/35733162-4c211382-0842-11e8-95d9-2c8c52a7b715.png">

**Comment by riju91** [comment]
fix will be available in nightly >=2018-02-04
