### ISSUE TITLE
Recommend Gauge plugin on opening a gauge project

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#114]
If Gauge or Gauge VS code plugin is not installed

### Expected behavior

* Open a Gauge project folder in visual studio code
* Recommend Gauge plugin in the extensions sidebar

For e.g while opening a `.rb` file it recommends the Ruby plugin

![recommended](https://user-images.githubusercontent.com/54427/35505994-e413d824-050d-11e8-8404-5be2a700647b.png)

**Comment by sriv** [comment]
`gauge` is listed as a recommended plugin for `spec` files. although there are other recommendations too.

@zabil - is that good enough?

Alternatively, we can add `gauge` to the workspace recommendations in the template.

**Comment by zabil** [comment]
> gauge is listed as a recommended plugin for spec files. although there are other recommendations too.

This is good enough

**Comment by nehashri** [comment]
To prompt user to install Gauge VSCode plugin, we can add .vscode folder to the gauge templates. It can have a extensions.json file with gauge listed as a recommended extension.

**Comment by shubhamsc** [comment]
should be added to all js, python and ruby templates and examples.
