### ISSUE TITLE
Install Gauge binaries

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#115]
If Gauge plugin is installed and `gauge` binaries are not found in `PATH`

### Expected behavior

* Display an info section on getting started page telling gauge is not installed 
* Detect the OS and provide a link to the installers and instructions on how to install.
* Point to configuration where a custom gauge path can be specified

**Comment by zabil** [comment]
For mac display the following instructions


Install gauge using the following instructions

Using brew

```

$ brew install gauge

```
Or download the pkg installer here

Or using curl

```
$ curl -SsL https://downloads.gauge.org/stable | sh

```

Installers for other platforms are available here.

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 02/03/18

**Comment by sguptatw** [comment]
**Test Cases**
- [ ] On OSx the instructions should be
```
brew install gauge
```
- [ ] On Windows it should be
```
choco install gauge
```
- [ ] On Debian, Ubuntu
```
sudo apt-get install gauge
```
- [ ] On Fedora:
```
sudo dnf install gauge
```
- [ ] On CentOS/RHEL:
```
sudo yum install gauge
```
- [ ] Message `Gauge executable not found!` should be displayed only if `gauge version` exit code is not successful.

**Comment by sguptatw** [comment]
- Pre-requisites to be listed with links - ex:- [brew](https://brew.sh/) , [choco](https://chocolatey.org/install)

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
