### ISSUE TITLE
Recommend settings

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#117]
For gauge to work smoothly, a user must to modify a few settings for e.g. autosave.  

### Expected behavior
* Identify the settings required by Gauge plugin to work smoothly.
* Display and information bar to modify and save these settings (if they are set)
* Provide a command palette action "Optimize VS Code configuration for Gauge"

**Comment by sriv** [comment]
should be available in nightly >= 13/4/2018

**Comment by sguptatw** [comment]
The nightly available as on 15/4/2018 is of - 0.0.4.nightly-2018-04-05
