### ISSUE TITLE
Show a Get Started page

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#118]
After the installing the Gauge plugin

### Expected behavior.

* Display a get started page as a tab in the editor area.
* The "Get started" section documents
    * Running Specification/Scenarios
    * Viewing reports.
    * Creating projects from a template.
    * Syntax
    * Link to main documentation
* Give an option "Don't show this page again" to hide the page on subsequent project creation or launch of the IDE.

**Comment by sguptatw** [comment]
The font size can be reduced to be similar to the specs.

**Comment by sguptatw** [comment]
Creating project from templates is not yet available in nightly gauge-0.0.4.nightly-2018-03-22.vsix
