### ISSUE TITLE
Generate implementation stubs in files

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#119]
### Expected behavior
* When a specification has an unimplemented step, show a quick fix to generate implementation stub
* When the quick fix is used being up a list of Gauge related javascript files in the command palette
* The list of files can be filtered. 
* Select a file from the list to open and insert the generated stub.
* The dropdown list of files must remember recently used files.
* In case of multiple unimplemented steps, add another quick fix option "Generate all implementation stubs" 
* The list (of files) must have an option to create a new file.

**Comment by BugDiver** [comment]
> Microsoft/vscode#41897 is the blocker for generating multiple implementations.

This issue has been fixed. Now we can implement the feature to generate multiple implementations at once.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
