### ISSUE TITLE
[Goto definition] Unable to open an exisiting concpet file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#12]
**Expected behavior**
Using goto definition, I should be able to navigate to the concept.

**Actual behavior**
From a spec when I try navigating to a concept. I get the error
`Unable to open 'abc.cpt': File not found (\\c:\<project_path>\lsp-tests\specs\concepts\abc.cpt).`
> This file exists in the given path

**Steps to replicate**
* Project [js.zip](https://github.com/getgauge/gauge-vscode/files/1374413/js.zip)
* Open file `some.spec`
* Try navigating to the concept `One`
* We get the following error

**Version**
```
Gauge version: 0.9.4.nightly-2017-10-09
Commit Hash: 8ef345c

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.1)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
VS Code - gauge-0.0.1.nightly-2017-10-06

**Comment by nehashri** [comment]
Should be fixed as part of gauge nightly >= 11-10-2017
