### ISSUE TITLE
The errors of refactoring should be indicated

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#122]
**Actual behavior**
`No result` is displayed on the step text

**Steps to replicate**
* In a `gauge-js` project
* Refactor `Vowels in English language are "aeiou"` to an empty step. This should display the reason why refactoring failed clearly.
Currently the output pane shows the error
```
Request textDocument/rename failed.
  Message: Refactoring failed due to errors:
:2 Step should not be blank => ''
  Code: 0 
```
* Another example is when `{` is used in the step
```
Request textDocument/rename failed.
  Message: Refactoring failed due to errors:
:2 '{' is a reserved character and should be escaped => '"aeiou" Vowels in English "ddd" {}'
  Code: 0 
```
* Another example 
```
Request textDocument/rename failed.
  Message: refactoring failed due to parse errors
  Code: 0 
```
However the IDE gives `No result` on the step.

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```

Bug on story https://github.com/getgauge/gauge-vscode/issues/81

**Comment by nehashri** [comment]
Fix should be available in nightly >= 15-2-18

**Comment by sguptatw** [comment]
Blocked 'cause of https://github.com/getgauge/gauge/issues/943

**Comment by sguptatw** [comment]
**Question**
* How should multiple errors be handled?
Example: One/more concept file can have a parse errors 'cause if which user cannot refactor.

**Comment by BugDiver** [comment]
Please verify the issue and update.

> Blocked 'cause of getgauge/gauge#943

This issue has been closed.
