### ISSUE TITLE
Spec Explorer should have multi select

### ISSUE THREAD

**Issue by riju91** [getgauge/gauge-vscode#123]
We should be able to select multiple scenarios and specifications and then run them from spec explorer
It is a part of https://github.com/getgauge/gauge-vscode/issues/42

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.

**Comment by jensakejohansson** [comment]
Why was this decided not to be implemented? It's a really crucial feature to make the test explorer useful.

**Comment by zabil** [comment]
🤔 Can't recollect why exactly. In hindsight I should've added more info. 

Unfortunately there is no plan to implement this in the near future, but please do feel free to submit a PR.
