### ISSUE TITLE
Debugger should stop when execution is stopped from the command pallete

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#124]
**Actual behavior**
It stops when I explicitly detach the debugger, however it is not detached when I stop the execution from the command pallete using `Stop current gauge execution`

**Steps to replicate**
* Project `LSP test`. Spec `Find Usages`
* Add a breakpoint in implementation file
* Start debugging a Spec/Scenario
* Stop gauge execution using `Stop current gauge execution` from the palette

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
js (2.1.1.nightly-2018-02-05)
```
VSCode - gauge-0.0.4.nightly-2018-02-02

Bug on story - https://github.com/getgauge/gauge-vscode/issues/108

**Comment by sguptatw** [comment]
Since the debugger is not stopped after `User stops` gauge execution. The status bar of the project is in an inconsistent state (the color has not changed back to the default color).

>Note : Replicable on mac OS as well

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >= 08/02/18

**Comment by sguptatw** [comment]
**Issue**
- Should work on Windows as well

**Comment by sriv** [comment]
is this still an issue?

**Comment by sguptatw** [comment]
Working as expected
