### ISSUE TITLE
[Windows] Debug point in a step should be honoured

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#125]
**Actual behavior**
Debug point of a step is not getting honored.

**Steps to replicate**
* Create a `gauge-js` project
* Add a breakpoint in the context step.
* Debug the Spec.
>Note the debug point is not honoured.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
js (2.1.1.nightly-2018-02-05)
```

Bug on story - https://github.com/getgauge/gauge-vscode/issues/108

**Comment by sguptatw** [comment]
The debug point of tear down is also not getting honoured

**Comment by Apoorva-GA** [comment]
@sguptatw Debugging is supported only on the implementation files.

**Comment by sguptatw** [comment]
@Apoorva-GA : Debug point is put on the step implementation of the context and tear down step

**Comment by sguptatw** [comment]
> Note: Debugger is getting attached after the execution

Debugger listening on ws://127.0.0.1:50852/fcfdbe65-28b8-47de-a191-c73d3e65281e
For help see https://nodejs.org/en/docs/inspector
# Specification Heading
  ## Vowel counts in single word
  ## Vowel counts in multiple word

Successfully generated html-report to => c:\work\testFolder\jstest\basic3\reports\html-report\index.html
Debugger attached.

**Comment by Apoorva-GA** [comment]
Raised a [issue](https://github.com/Microsoft/vscode/issues/43491) on VSCode.

**Comment by riju91** [comment]
working as expected for the following versions

Gauge version: 0.9.8.nightly-2018-03-09
Commit Hash: c895c3f

Plugins
-------
html-report (4.0.3.nightly-2017-12-08)
js (2.2.0.nightly-2018-03-12)

**Comment by sguptatw** [comment]
Working as expected - VS Code - 1.21.0
