### ISSUE TITLE
Error concatenating the project path twice

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#127]
**Expected behavior**
The file path in the error stack should be valid

**Steps to replicate**
* Run the project [basic1.zip](https://github.com/getgauge/gauge-vscode/files/1697987/basic1.zip)
Getting the following error

<img width="698" alt="concatination" src="https://user-images.githubusercontent.com/6310197/35844722-e4e9a21a-0b34-11e8-9909-ed1bee3e401b.png">

**Steps to replicate**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
js (2.1.1.nightly-2018-02-05)
```
VS-Code - gauge-0.0.4.nightly-2018-02-02.vsix

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
