### ISSUE TITLE
After detaching the process once, debugging is not working as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#129]
**Expected behavior**
In the next session, debug points should get honored.

**actual behavior**
In subsequent debugging session, debug points are not honoured. However pause works as expected

**Steps to replicate**
* Start debugging a spec or scenario. Detach the process and stop gauge execution.
* Now debug again.
> Note: Debug points are not honored

**version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
js (2.1.1.nightly-2018-02-05)
```
VSCode - gauge-0.0.4.nightly-2018-02-02.vsix

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
