### ISSUE TITLE
Depricated messages should not be shown while executing from the IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#13]
**Expected behavior**
Deprecation messages should not appear in the IDE

**Actual behavior**
Old gauge commands are being used, so we see deprecation message.

Either use gauge latest commands or the flag that suppresses deprecation message.

**Comment by nehashri** [comment]
@sguptatw Gauge vscode is using the latest gauge commands. Deprecation messages are not displayed for Gauge commands. You may be seeing other deprecation messages. Please provide exact deprecation message being displayed.
