### ISSUE TITLE
LSP features not available should not comeup

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#133]
**Actual behavior**
Currently VSCode IDE features is supported for js, ruby and python. LSP Feature options is coming up for gauge projects with language runners not compliant with LSP.

**Steps to replicate**
* Create a `gauge-dotnet` project
* Open a spec file
> Note: Code Lens debug appears.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
ruby (0.4.3.nightly-2018-02-07)
```

**Comment by nehashri** [comment]
This issue was moved to getgauge/gauge#954
