### ISSUE TITLE
Debug Restart not working as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#135]
**Expected behavior**
Click Restart on the Debug menu to stop the target's execution and end the target process and all its threads. This command then restarts the target execution at the beginning of the process.

**Actual behavior**
It continues and finishes the execution

**Steps to replicate**
* In the IDE, add a debugger point on an implementation file
* Start the debugging
* Once the point is reached, click on the restart  option of the debug menu.

> Note: The execution is not restarted
**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
html-report (4.0.4.nightly-2018-01-11)
js (2.1.1.nightly-2018-02-05)
ruby (0.4.3.nightly-2018-02-07)
xml-report (0.2.1.nightly-2017-10-26)
```
VSCode - gauge-0.0.4.nightly-2018-02-02.vsix

Bug on story - https://github.com/getgauge/gauge-vscode/issues/108

**Comment by nehashri** [comment]
We cannot restart the debugger when it started with attach process.
