### ISSUE TITLE
Should be able to pause anytime

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#136]
**Actual behavior**
When a API is called and not yet received the response, should be able to pause.
> Note: I am able to stop the execution at anytime

**Steps to replicate**
* Project [LSP Tests](https://github.com/getgauge/gauge-lsp-tests) Spec - `Find Usages`.
- Break point on `project.js` line 9 `await languageclient.openProject(relativePath,process.env.language)`
- Continue execution. After a couple of seconds - click pause.
It does not pause (This happens when the `codelens` call is being processed).

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
html-report (4.0.4.nightly-2018-01-11)
js (2.1.1.nightly-2018-02-05)
ruby (0.4.3.nightly-2018-02-07)
xml-report (0.2.1.nightly-2017-10-26)
```
VSCode - gauge-0.0.4.nightly-2018-02-02.vsix

Bug on story - https://github.com/getgauge/gauge-vscode/issues/108

**Comment by Apoorva-GA** [comment]
This works for me. You can try with the basic JS project by putting sleep.
