### ISSUE TITLE
Once an execution starts the previous status should get cleared from the status bar.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#139]
**Actual behavior**
The previous status is retained on the status bar

**Steps to replicate**
* Create a new `gauge-js` project
* Execute the specifications
* Now make some changes. Execute the specifications again.
> Note the status bar still displays the older run stats

Bug on story - https://github.com/getgauge/gauge-vscode/issues/90

**Comment by sguptatw** [comment]
Also, When a run was stopped by the user previous status is displayed.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >= 16/02/18
