### ISSUE TITLE
Link to resultant html-report does not work

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#14]
**Expected behavior**
I should be able to click on the link to html-report and see the report

**Actual behavior**
Hover on the link says `click to follow`. However a Click on the link does nothing

**Steps to replicate**
* Run a scenario
* Click on the link
Successfully generated html-report to => c:\work\js\reports\html-report

**Comment by nehashri** [comment]
Seems to be an issue in html report. https://github.com/getgauge/html-report/issues/138. Closing this issue.
