### ISSUE TITLE
Run in parallel should not be displayed data from table is not used

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#141]
**Expected behavior**
If the data from the table is not used in the specifications, it executes the scenarios only once. Hence the `run in parallel` should not be displayed

**Actual behavior**
Run in parallel code lens is displayed irrespective of the data being used in the specification

**Steps to replicate**
* Create a `gauge-js` project
* Replace the spec file content with the following
```
Specification Heading
=====================

   |something|
   |---------|
   |aeiou    |
   |aeiou    |

tags: o
* Vowels in English language are "aeiou".

Vowel counts in single word
---------------------------

tags: single word, o

* The word "gauge" has "3" vowels.

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels 

   |Word  |Vowel Count|
   |------|-----------|
   |Gauge |3          |
   |Mingle|2          |
   |Snap  |1          |
   |GoCD  |1          |
   |Rhythm|0          |
```
* The code lense for this spec shows the `Run in parallel` option.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-12
Commit Hash: 8166611

Plugins
-------
js (2.1.1.nightly-2018-02-08)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
