### ISSUE TITLE
Cannot read property path of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#142]
**Expected behavior**
Should not get error when file is saved

**Actual behavior**
Getting the following error
![screen shot 2018-02-15 at 1 29 10 pm](https://user-images.githubusercontent.com/6310197/36246373-8c40055a-1255-11e8-96a2-ca6409108e3f.png)

**Steps to replicate**
* Create a new `gauge-python` project
* Create a new spec file blah.spec
* Type the following content in to the empty file
```
# Something
```
* Now save the file
> The above error occurs

**Version**
```
auge version: 0.9.8.nightly-2018-02-14
Commit Hash: d5db0c9

Plugins
-------
html-report (4.0.4.nightly-2018-01-11)
js (2.1.1.nightly-2018-02-08)
python (0.2.4.nightly-2018-02-11)
ruby (0.4.3.nightly-2018-02-13)
xml-report (0.2.1.nightly-2017-10-26)
```

**Comment by Apoorva-GA** [comment]
Unable to reproduce. @sguptatw Do you quickly want to check if this is still a issue?

**Comment by Apoorva-GA** [comment]
Was able to replicate this on windows on both js and python projects.

Steps to replicate :

- Create a new gauge-python project
- Create a new spec file blah.spec
- Type the following content in to the empty file

```
# Something
```
- Reload the project. (when the blah.spec file is open in the editor)

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >= 19/02/18
