### ISSUE TITLE
Use the # and ## for spec and scenario headings

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#145]
### Current behavior

Scenario and specifications use a cumbersome header format

```
Specification
==========

Scenario
---------

``` 

This makes it tough to use templates to edit as the == and -- need to be matched to the heading length. 

### Expected behavior

Convert the headers to use `#` and `##`

For e.g.

```
# Specification

## Scenario
```

Format should use this style.

**Comment by BugDiver** [comment]
The snippets are updated to use # and ## for spec and scenario.
Fix should be available in gauge-vscode nightly  >= 26-02-2018
