### ISSUE TITLE
Couldn't start client langserver

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#15]
**Expected behavior**
Give a better error

**Actual behavior**
Getting error Couldn't start client langserver

**Steps to replicate**
* Gauge core is **not** installed
* plugins are installed
* Open VSCode - Getting the error `Couldn't start client langserver`. 
Instead this can be an info. Cannot find `gauge` binary. Show the install gauge button.

**Comment by zabil** [comment]
Gauge VS code plugin must download and install Gauge if it's found in the path.

**Comment by zabil** [comment]
Fix implemented as a part of https://github.com/getgauge/gauge-vscode/issues/27
