### ISSUE TITLE
Javascript stack trace missing when implementation throws error

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#152]
```
VS-Code version: 1.20.1
Gauge Extension Version: 0.0.4

Gauge version: 0.9.8


Plugins
-------
html-report (4.0.3)
java (0.6.6)
js (2.1.1)
ruby (0.4.2)
screenshot (0.0.1)
```

### Current behavior

Generate a stub implementation using the code fix for e.g.

```
step("This is the third unimplemented step", async function() {
	throw 'Unimplemented Step';
});
```
Run the scenario with the step implementation and it throws the following error with an empty stack trace

```
 ## This is a new scenario
        
        Failed Step: This is the an unimplemented step
        Specification: /Users/zabilcm/Projects/vowels/specs/example.spec:43
        Error Message: Unimplemented Step
        Stacktrace: 
        
```

### Expected behavior

The stack trace must refer to the line number a file of `throw 'Unimplemented Step';`

**Comment by BugDiver** [comment]
`throw 'Unimplemented Step';` is not actually throwing an error object so It will not have any stack trace.
