### ISSUE TITLE
The Generated files should be in the implementation folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#155]
**Actual behavior**
The generated file is in the specs folder.

**Steps to replicate**
* Generate a stub for an unimplemented step. Choose New File.
>This file is created in the specs folder.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-26
Commit Hash: 77c642d

Plugins
-------
dotnet (0.0.1.nightly-2018-02-14)
html-report (4.0.4.nightly-2018-01-11)
java (0.6.7.nightly-2018-02-23)
js (2.1.1.nightly-2018-02-27)
python (0.2.4.nightly-2018-02-27)
ruby (0.4.3.nightly-2018-02-13)
screenshot (0.0.1)
spectacle (0.1.3.nightly-2017-10-26)
```
Bug on story https://github.com/getgauge/gauge-vscode/issues/119

**Comment by BugDiver** [comment]
While creating the new file, instead of creating an `Untitled` documentation figure out a file name and write that file in defaults implementation dir with implementation stub.

**Comment by BugDiver** [comment]
The fix should be available in following nightlies -

|Name                |Nighly Date|
|---------------|------------|
|gauge-vscode |07-03-2018|
|gauge-js          |07-03-2018|
|gauge-python |07-03-2018|
|gauge-ruby     |07-03-2018|
