### ISSUE TITLE
Focus should be on the generated code

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#156]
**Expected behavior**
When step implementation is generated into a new file, the focus should be on the generated code.

**Actual behavior**
The focus is on the start of the file

**Steps to replicate**
* Create a new `gauge-js` project
* Generate step of an Unimplemented step
* Create another unimplemented step
* Generate step.
> The code generated is at the eof while the focus is on the start of the file.

**Comment by riju91** [comment]
should be available in nightly >= 2018-03-07
