### ISSUE TITLE
Suggestions to Welcome Page

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#159]
- The space between the logo and the content can be reduced.
- About wordings can be changed - Gauge is a light-weight cross-platform fast test automation tool. 
- Explore can have link to blog
- The Font weight and size of `Project/Workspace`, `Customize`, `Learn` can be the similar to `Start` in Help WelcomePage of VSCode.
- Learn can have link to [Gauge Terminologies](https://docs.gauge.org/longstart.html#gauge-terminologies) as well.
- Customize can have link to `Apply recommended settings` - https://github.com/getgauge/gauge-vscode/issues/161
- There can be a `Start` section above `Explore` - https://github.com/getgauge/gauge-vscode/issues/162

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 02/03/18
