### ISSUE TITLE
Show usages of a step implementation

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#16]
Show a code lens over the step implementation that will bring up a usages view.

**Acceptance criteria**
* List number of usages above the step implementation
```
2 references
step("Vowels in English language are <vowels>.", function(vowelsGiven) {
  assert.equal(vowelsGiven, vowels.join(""));
});
```
* If the step has multiple implementations then all the implementations should show the usages

**Test cases**
* [x] Should list number of usages 
* [x] Multiple implementations should show all the usages

**Comment by sguptatw** [comment]
**Issues**
* [ ] Multiple step implementations for the same step does not show the warning

**Comment by nehashri** [comment]
@sguptatw The issue talks about showing code lens for references of step. 
The acceptance criteria

> If the step has multiple implementations then the warning message should be shown instead of the usage count

and test case 

> Multiple implementations for the same step should show the warning

looks like it is mixing up problem diagnostics and references.
If a duplicate step implementation exists in a different file, it is hard for the user to find the duplicate. References also will not be shown if we decide to show a warning instead. 
Also a code lens cannot be used to show a warning. It is more like an action that can be invoked by a user. It should not be used to show warnings to a user.

To handle the issue you have pointed outTo show a warning
We should ideally be populating it with problem diagnostics for javascript files.
*OR* 
Show another code lens with which takes you to the duplicate implementation.

In either case, it should *not* be mixed up with showing usages of a step.

**Comment by zabil** [comment]
> If a duplicate step implementation exists in a different file, it is hard for the user to find the duplicate. References also will not be shown if we decide to show a warning instead.

Agreed, didn't consider this scenario.

**Comment by zabil** [comment]
### New test case

* [ ] Highlight the step text (Almost all words have vowels) in the preview pane, to locate it easily

![highlightreference](https://user-images.githubusercontent.com/54427/32595945-b86fb7ba-c557-11e7-8b4c-a0323a76a9d2.png)

**Comment by sguptatw** [comment]
@nehashri Thanks for the clarification

## Question
In code when there is a duplicate step implementation how should the references are displayed

**Current behavior**
If the step implementations are in 2 different files, the number of usages are displayed for all the duplicate step implementations.
If the duplicate step implementation is in the same file, only one of the step implementations have the usage number. The other step implementation(s) will not have the code lens link.

How should this be handled?

**Comment by zabil** [comment]
>  In code when there is a duplicate step implementation how should the references are displayed?

The references code lens must be displayed for all duplicated methods.

**Comment by nehashri** [comment]
changes should be available in gauge, gauge-js, gauge-vscode nightly >= 15-11-2017
