### ISSUE TITLE
Start section on Welcome page

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#162]
The Welcome Page should have a start section with action `Create a new spec`. 
This should create a new specification initialized with the default specification template.

A command palette action should be available to create a new specification.

> This command should not be available for a non-gauge project.

**Comment by BugDiver** [comment]
The fix should be available in following nightlies -
* gauge 29-05-2018
* gauge-vscode 29-05-2018

**Comment by sguptatw** [comment]
When file is created, The cursor focus should be on the specification heading and not on the step.

**Comment by sguptatw** [comment]
- [x] Create specification should be available on the palette and the Welcome Page for a gauge project.
- [x] This command should not be available for a non-gauge project in the palette and the Welcome Page
- [x] With multiple workspaces, a dropdown of gauge projects should be available for selection
- [x] Should create a new specification in the gauge_specs_dir. If there are multiple spec directories, it provides a drop down with selection.
- [ ] When specification file is created, The cursor focus should be on the specification heading and not on the step.
- [ ] Documentation should be updated

**Comment by BugDiver** [comment]
>  When specification file is created, The cursor focus should be on the specification heading and not on the step.

That's the expected behavior.

**Comment by sguptatw** [comment]
Getting a segmentation violation in Linux when there is no implementation directory.
