### ISSUE TITLE
Autocomplete adds an extra * when invoked without a space

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#165]
**Expected behavior**
Autocomplete should not prefix the step text with a star

**Actual behavior**
It is prefixing a star when autocomplete is invoked without a space

**Steps to replicate**
* Create a `gauge-csharp` project
* In a new line add a star
* Invoke autocomplete (Ctrl+space) just after the star
* Choose the first available step
> It adds an extra * prefixed to the step text. Seems like Gauge is crashed

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
