### ISSUE TITLE
Remove message `Gauge updated to version...`

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#168]
_From @sguptatw on March 2, 2018 3:32_

**Actual behavior**
Both the pop-up and Welcome Page are shown.

**Expected behavior**
With the welcome page, the popup message about Gauge version being updated is redundant.
- Remove the popup message
- Remove configuration settings if any w.r.t it

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-01
Commit Hash: fa1a10f

gauge-0.0.4.nightly-2018-03-01.vsix
```

_Copied from original issue: getgauge/gauge-js#120_

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 02/03/18

**Comment by sguptatw** [comment]
The settings `gauge.notification.suppressUpdateNotification` should be removed.
