### ISSUE TITLE
Show installation instruction on Welcome Page when gauge is not installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#169]
Should show installation instruction if gauge-executable is not found.

- These instructions should be based on the OS of the user
- These instructions should be shown only if the gauge executable is not found

**Comment by sguptatw** [comment]
**Test Cases**
- [ ] On OSx the instructions should be
```
brew install gauge
```
- [ ] On Windows it should be
```
choco install gauge
```
- [ ] On Debian, Ubuntu
```
sudo apt-get install gauge
```
- [ ] On Fedora:
```
sudo dnf install gauge
```
- [ ] On CentOS/RHEL:
```
sudo yum install gauge
```
- [ ] Message `Gauge executable not found!` should be displayed only if `gauge version` exit code is not successful.
> Note: Gauge can be installed in a custom path.

**Comment by sguptatw** [comment]
**Open Questions**
- Should the message be displayed even after `Gauge executable` is installed?
- Should pre-requisites be listed with links - ex:- [brew](https://brew.sh/) , [choco](https://chocolatey.org/install)

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 02/03/18

**Comment by sguptatw** [comment]
Duplicate of https://github.com/getgauge/gauge-vscode/issues/115
