### ISSUE TITLE
Debug after refactor should work as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#172]
**Expected behavior**
After refactoring, one should be able to debug a spec or a scenario

**Actual behavior**

**Steps to replicate**
* Create a new project `gauge-js`
* Put a breakpoint in a step
* Refactor that step
* Now debug the spec
* The debugger doesn't honour the breakpoint
> Note the behavior is same on a `gauge-python` project

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-01
Commit Hash: fa1a10f

Plugins
-------
js (2.1.1.nightly-2018-02-14)
python (0.2.4.nightly-2018-02-28)
```
gauge-0.0.4.nightly-2018-03-01.vsix

**Comment by riju91** [comment]
Since we are pasting the whole file contents, the debug point is moving to the end of the file

**Comment by BugDiver** [comment]
The fix should be available following nightlies

* guage 23-05-2018
* guage-python 23-05-2018
* guage-ruby 23-05-2018
* gauge-js 23-05-2018

**Comment by sguptatw** [comment]
Verified on python
- [x] OSx
- [ ] Windows
- [ ] Mac

Verified on js
- [ ] OSx
- [ ] Windows
- [ ] Mac

Verified on ruby
- [ ] OSx
- [ ] Mac
