### ISSUE TITLE
Create new specification command palette action

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#177]
### Current behavior

* Locate the specs folder in the file explorer
* Right-click and select "New File"
* Name the specification file

It's cumbersome to locate folders and create specs with the right extension, especially when there are multiple workspaces.

### Expected behavior

* Add a command palette action "New Specification"
* Selecting this action will create a specification under the "specs" folder with an auto-generated `.spec` filename

**Comment by sguptatw** [comment]
Tracking this as a part of https://github.com/getgauge/gauge-vscode/issues/177
