### ISSUE TITLE
A user with admin permissions should be able to install gauge from the Welcome Page

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#178]
**Actual behavior**
Unable to install from VSCode. I can however install gauge by starting powershell in admin mode.
> VSCode is using `choco install gauge` which currently needs admin permissions.

**Steps to replicate**
* On Windows click with gauge not installed open a gauge project
* Click on run of the installation section

**Version**
```
gauge-0.0.4.nightly-2018-03-02.vsix
```
Bug on story - https://github.com/getgauge/gauge-vscode/issues/115

**Comment by sguptatw** [comment]
If Gauge is installed using choco from VSCode, the user should be able to uninstall using 
`choco uninstall gauge`

**Comment by sriv** [comment]
not an issue with gauge-vscode. this is a behaviour noted on the gauge-chocolatey package.

**Comment by sguptatw** [comment]
Issue to track the uninstall behavior - https://github.com/getgauge/chocolatey-packages/issues/6
