### ISSUE TITLE
Getting command not found for welcome page

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#179]
**Expected behavior**
Should not get command not found

**Actual behavior**
<img width="674" alt="gauge_welcome_not_found" src="https://user-images.githubusercontent.com/6310197/37013507-4a790bf6-2120-11e8-9227-b93474170a80.png">

**Steps to replicate**
* Open an existing gauge-python project
* In command pallet look for `Welcome Page`
> Getting the above error. OS - Windows

**Version**
```
gauge-0.0.4.nightly-2018-03-05.vsix
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >= 06/03/18

**Comment by sguptatw** [comment]
Still replicable in `gauge-0.0.4.nightly-2018-03-06.vsix`

**Comment by Apoorva-GA** [comment]
Gauge-vscode build was failing. Have triggered the nightly after the fix, Please check with gauge-vscode nightly = 07/03/18
