### ISSUE TITLE
Html-report can be shown within vscode

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-vscode#183]
A new command `Gauge: Show Last Run Report` can be introduced in the command pallette.

The above command shall open the html-report in a new tab in vscode (inline, and not in browser).

The html-report shall have a theme optimized for vscode viewing.

**Comment by sguptatw** [comment]
**Question**
- How should an existing project with a previously generated report behave?
- How should a project with no runs yet behave?

**Comment by sriv** [comment]
My take:

> How should an existing project with a previously generated report behave?

Currently the vscode plugin remembers the run only per session. So if you reopen a project, the plugin isn't aware of previous report location. 

Ideally, it would be nice to have the report location stored, so that closing the project does not have any effect. But this should be consistent, i.e. the status bar should also have the state. 

There are challenges:

- what if there was a run outside vscode in the same project? i.e. via cli
  - the theme would not be suited to display the report inline
  - the plugin does not have any way to detect where to take the report from.

For sake of simplicity, I'd say display reports only if there was a run in the current session.

> How should a project with no runs yet behave?

Should do nothing, IMO. If it is not obvious, then perhaps show a message. But it is a bit intrusive.

**Comment by sriv** [comment]
Font size of what? Please provide some specific details

**Comment by sguptatw** [comment]
Font size comparable to that of the specification
![Spec.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db849f20c0cfeb9ffbb049a15ee4d6730472257c00fb7a7680e57bbc477f515b594eac45095c17f9fb9b37b4f46d2ede0356b49b381d66cc2f10abb2831abd03bb228f4980b6b98248d2a5.png)

**Comment by sguptatw** [comment]
Note: GAUGE_HTML_REPORT_THEME_PATH will not be ignored, we are not custom styling reports shown in vs code.
