### ISSUE TITLE
Codesign gauge MacOS binaries

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#184]
### Current behavior
* Whenever the gauge daemon runs (for e.g from VS Code) it pops up the "Allow connections" dialog in macOS
* Not allowing the daemon to open connections and breaks functionality.

### Expected behavior
* Whitelist gauge binary on MacOS firewall.
* codesign the MacOS binary to prevent popups

More information here https://support.apple.com/en-in/HT201642

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge#973
