### ISSUE TITLE
Parameter autocompletion removes fullstop

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-vscode#187]
```
VS-Code version: 1.21.0
Gauge Extension Version: 0.0.4

Gauge version: 0.9.8
Commit Hash: 40357c6

Plugins
-------
html-report (4.0.3)
js (2.2.0.nightly-2018-03-07)
screenshot (0.0.1)
```

## Steps to replicate

[noticed on ubuntu]

- `gauge init js`
- edit `example.spec`
  - add table
     ```
     |vowels|
     |------|
     |aeiou|
     ```
- replace static parameter `"aeiou"` in `* Vowels in English language are "aeiou".` with `<vowels>`. 
- notice the end result
  - `* Vowels in English language are <vowels>`
  - the step is unimplemented.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
