### ISSUE TITLE
Should be able to generate impl even if there are no other implementation files

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#190]
_From @sguptatw on March 8, 2018 8:35_

**Actual behavior**
Unable to generate impl files

**Steps to replicate**
* Create a `gauge-js` project
* Delete the generated implementation file
* Now try generating stub for the steps in the spec
* Unable to generate the implmentation

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-07
Commit Hash: 40357c6
```

_Copied from original issue: getgauge/gauge#965_

**Comment by riju91** [comment]
should be available in nightly >= 2018-03-13

**Comment by sguptatw** [comment]
Not working as expected with latest Gauge

**Comment by Apoorva-GA** [comment]
Unable to replicate.
Works as expected with gauge nightly = 21/03/18

**Comment by sguptatw** [comment]
Replicable on Ubuntu

**Comment by riju91** [comment]
should be available in nightly >= 2018-03-27
