### ISSUE TITLE
The settings for VS code plugins should have the gauge icon

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#2]
* Goto Settings -> gauge.
The icon displayed is empty.

<img width="974" alt="screen shot 2017-08-02 at 4 07 06 pm" src="https://user-images.githubusercontent.com/6310197/28870112-b77ee29e-779c-11e7-9894-9a08371c5838.png">
This should be the gauge icon.

**Comment by zabil** [comment]
Gauge icon shows up now.
