### ISSUE TITLE
Run failed scenarios

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#20]
Ctlr-shift-p to display an command "Rerun failed scenario(s)" that will rerun failed scenarios. 

**Acceptance criteria**
* If a spec has multiple scenarios, only failed scenarios must be re-run
* If a spec has multiple test cases(data driven by rows). Re-run should run only the  failed test case

**Test cases**
* [x] If rerun is used when only passed and skipped scenarios are present, then it is considered as a `Tests failed`
* [x] Only failed scenarios must be run
* [ ] Only failed test case must be run

**Issues**
- [ ] If there are multiple test cases, only [failed test case should be run](https://github.com/getgauge/gauge/issues/416)

**Comment by BugDiver** [comment]
This feature is already added through https://github.com/getgauge/gauge-vscode/commit/749305c99af59f354144ec8c43c92a5185753205. It should be available in nightly > 10-10-2017

**Comment by sguptatw** [comment]
If there are only passed and skipped scenarios are present, then we are getting an error
```
Running tool: gauge run --failed
No failed tests found.
Error: Tests failed.
```
If there are multiple test cases, only [failed test case should be run](https://github.com/getgauge/gauge/issues/416)
