### ISSUE TITLE
If Gauge executable is not found, Welcome Page should be shown

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#204]
**Current behavior**
Welcome page is shown based on the setting `gauge.welcome.showOn` or file state.

**Proposed behavior**
If Gauge executable is not found, it should show the Welcome Page.

Enhancement on story - https://github.com/getgauge/gauge-vscode/issues/118

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 26/03/18

**Comment by Apoorva-GA** [comment]
Make sure that gauge is not in path and check again.

**Comment by sguptatw** [comment]
Works as expected - Considering "gauge.welcomePage.enabled": true
