### ISSUE TITLE
Show Last Run Report should not give an error for a newly created project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#205]
**Expected behavior**
For a newly created project, `Show Last Run Report` should not do anything

**Actual behavior**
Getting the following error

<img width="340" alt="lastexecutionreport" src="https://user-images.githubusercontent.com/6310197/37635926-a832edac-2c24-11e8-9a14-8ca81ea3fb6a.png">

**Steps to replicate**
* Create a new `gauge-js`  project
* `Show Last Run Report` from the command palette.
> We get the above error

**Version**
```
gauge-0.0.4.nightly-2018-03-16.vsix
```
Bug on https://github.com/getgauge/gauge-vscode/issues/183

**Comment by Apoorva-GA** [comment]
Works as expected with nightly version `0.0.10.nightly-2019-05-10`
