### ISSUE TITLE
Remove telemetry before 1.0

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#206]
[Telemetry data](https://blog.getgauge.io/why-we-collect-data-b19df366b677) was collected for Gauge.

Now that we have gathered the information we seeked, we want to remove the data collection before Gauge 1.0 Release

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge#981

**Comment by sriv** [comment]
gauge-vscode does not collect telemetry. This is a change for https://github.com/getgauge/gauge
