### ISSUE TITLE
Put Stub implementation on existing empty file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#212]
**Expected behavior**
Should put stub impl on selected file

**Actual behavior**
If the file is empty, it puts the implementation on a new file

**Steps to replicate**
* Create a `gauge-python` project
* Clear the contents of the implementation file
* Goto the spec file. Generate the stub impl. Select the existing empty impl file.
* It adds a new impl file

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-22
Commit Hash: 506987e

Plugins
-------
python (0.2.5.nightly-2018-03-20)
```
Bug on feature - https://github.com/getgauge/gauge-vscode/issues/119

**Comment by riju91** [comment]
fix should be available in nightly >= 2018-04-06

**Comment by sguptatw** [comment]
Required nightly not available. As on 2018-04-13, the latest nightly is `2018-04-05`
