### ISSUE TITLE
Enable only relavent command palette commands

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#216]
A lot of commands are shown to the user even if they do not work on a specific page or context. They are shown even for non gauge projects. Disable such commands from the command palette if they are not supposed to work.

**Comment by sguptatw** [comment]
- [ ]  `Apply Recommended Settings` should be enabled on the Welcome Page only if the current project is a gauge project or the current workspace has a gauge project
- [ ] `Run Scenario` should be available only if spec file is open
- [ ] `Find  Step References` should be available only if the implementation file is open
- [ ] `Optimize VSCode Configuration...` should apply and restart if the configurations are not optimized.
- [x] For a non Gauge project only the following commands should be available
* Welcome
* Create a new Gauge Project
* Report Issue

**Comment by Apoorva-GA** [comment]
As discussed, keeping the behaviour of `Run Scenario` and `Find Step References` as it is. That is showing an error message instead of hiding the commands from command palette.

Fix should be available in gauge-vscode nightly >= 22/05/18

**Comment by sguptatw** [comment]
The message on clicking `Find Step References` gives
`Running the contributed command:'gauge.showReferences.atCursor' failed.` when `Welcome Page` is open

The message on clicking `Find Step References` gives
`Running the contributed command:'No references found` when `spec file` is open

In either case user does not have a clarity on why the command is not working.

**Comment by sguptatw** [comment]
The message should be `Action NA:Try this on an implementation`

**Comment by Apoorva-GA** [comment]
Fixed the above issue when spec file is open. But when Welcome page is open the behaviour is same for now. To fix the issue we will have to disable the irrelevant commands from command palette.

**Comment by sguptatw** [comment]
Tracking adding relevant commands in issue https://github.com/getgauge/gauge-vscode/issues/268
