### ISSUE TITLE
Generate step implementation stubs

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#22]
Provide a codeAction on unimplemented steps to generate a method stub and copy it to the clipboard.

For e.g. 
```
* This is a new step
```

Gets a codeAction option `"Copy function stub for this step to clipboard"`
Running the codeAction copies following codeto clipboard

```
step("This is a new step", async function(){
 throw 'Unimplemented Step'; 
});
```

**Comment by sguptatw** [comment]
The  quick fix and the suggestion provided on command line for unimplemented steps should by the same.

The suggestion provided on command line is
```
step("This is a new step", function(){
 throw 'Unimplemented Step'; 
});
```
> async keyword is missing in the command line suggestion. What is the correct behavior?

**Comment by zabil** [comment]
Let's have `async`
However, this will work only on nodejs 8 and we must call that out.

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 14- 11-2017

**Comment by zabil** [comment]
Change the text for the quick fix to.
"Generate Step implementation Stub"

After a user clicks on this, Display and info message.

"Step Implementation copied to clipboard"

**Comment by sguptatw** [comment]
Functionality is working as expected. Only the text for the quick fix is "Show fixes (Ctrl+.)"

**Comment by BugDiver** [comment]
Expected behavior should be available in following nightlies : 

* gauge-js 16-11-2017
* gauge-vscode 16-11-2017
