### ISSUE TITLE
IDE features should work when gauge_specs_dir is configured

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#222]
**Expected behavior**
VSCode features should work when gauge_specs_dir is configured.

**Actual behavior**
- [x] Diagnostics are have to be displayed
- [x] Should be able to create new step implementation
- [x] Find Usage statistics must take folders specified in gauge_specs_dir into consideration

- [x] Test Explorer must list the scenarios in gauge_specs_dir

- [x] Gauge features on specs should be invoked for specs within gauge_specs_dir

> Concepts can be defined anywhere in the project, i.e irrespective of this env
- [x] Should be able to navigate to a concept defined outside of gauge_specs_dir

- [x] `Run All Specifications` should consider all the specs within the gauge_specs_dir

- [x] Autocomplete features should work with the configured directories

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 23/05/18
