### ISSUE TITLE
The statistics shown in report should be consistent with the status bar

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#224]
**Expected behavior**
The status bar and the report should show the same statistics

**Actual behavior**
Report is showing the specification statistics, the status bar is showing the scenario statistics
The order of statistics is also different

**Steps to replicate**
* Create a `gauge-js` project
* Add 2 speca
* Ensure 1 spec fails with 2 scenarios and other is skipped
* Run All specs using VSCode command palette
* Open the report
> The report statistics show specification statistics and status bar shown the scenario statiscs

**Version**
```
gauge-0.0.4.nightly-2018-03-26.vsix
```

**Comment by sriv** [comment]
fix should be available in nightly >= 11/4/2018. 

Also ensure that the html-report nightly >= 11/4/2018
