### ISSUE TITLE
[Report] User should be able to expand/collapse scenarios

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#225]
**Expected Behavior**
User should be able to expand/collapse scenarios on reports. The passed and skipped scenarios should be collapsed by default

**Actual behavior**
Only specifications can be expanded of collapsed on reports. The passed and skipped scenarios are expanded by default

**Steps to replicate**
* Run specs
* Open report in VSCode
> The scenarios cannot be collapsed
The passed and skipped scenarios are expanded. It should be collapsed by default

**Version**
```
gauge-0.0.4.nightly-2018-03-26.vsix
```

**Comment by sriv** [comment]
not a bug.

@zabil and self spoke. Here's the idea:

- make console reporting and vscode inline report consistent, i.e. expanded=verbose, collapsed = regular.
- specs are expanded, and not collapsible
- instead scenarios are collapsible
- by default all failed scenarios are expanded, passed/skipped are collapsed.
- a collapsed report shall display only the spec and scenario heading, expanded view shall include steps, gauge_messages, screenshot etc.

**Comment by sriv** [comment]
should be available in nightly >= 13/4/2018

**Comment by sguptatw** [comment]
- [x] Specs are not collapsible
- [x] User can expand/collapse scenarios
- [x] By default failed scenarios are expanded, passed/skipped are collapsed
- [x] A Collapsed report displays spec and scenario heading
- [x] Expanded view includes steps, gauge_messages

------------------------------------------------
**Issue**
* Report should be generated https://github.com/getgauge/html-report/issues/177

**Question**
* The Before hook gauge messages and stacktrace are printed after the element. What should be the behavior?

**Comment by sguptatw** [comment]
As discussed,
- before hook, gauge messages the existing behavior is acceptable
- After suite failure display position is acceptable
