### ISSUE TITLE
Run All specifications should invoke gauge run

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#226]
**Expected behavior**
When `gauge_specs_dir` is set the directories should be considered for execution

**Current behavior**
This invokes `gauge run specs`

**Steps to replicate**
* Create `specsOne` directory at the same level as `specs`
* Set the `gauge_specs_dir` to `specs, specsOne`
* Restart the IDE
* Now `Run All specifications` from the command palette.
> This runs only `gauge run specs`

Related to issue https://github.com/getgauge/gauge/issues/984

**Comment by zabil** [comment]
This is fixed the latest version of VS Code plugin
