### ISSUE TITLE
The IDE support should be available after installation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#227]
**Expected behavior**
On Installing and restart of the VSCode, the IDE features should be available

**Actual behavior**
The IDE features are not available. The Gauge extensions show `Reload` despite reloading the project

**Steps to replicate**
* Install `gauge-0.0.4.nightly-2018-04-05.vsix`
* Reload VSCode
> The following message is displayed
<img width="1180" alt="screen shot 2018-04-09 at 8 25 23 am" src="https://user-images.githubusercontent.com/6310197/38477428-110a9a4a-3bd0-11e8-96bf-910350e25e60.png">

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-06
Commit Hash: ac32b86

Plugins
-------
html-report (4.0.4.nightly-2018-03-30)
java (0.6.7.nightly-2018-04-05)
js (2.2.0.nightly-2018-03-29)
gauge-0.0.4.nightly-2018-04-05.vsix
```

**Comment by sriv** [comment]
Observation: Works on windows. 

@getgauge/core - someone with osx - please check.

**Comment by nehashri** [comment]
Works well on OsX and Ubuntu.
@sguptatw Can you check if issue still exists.

**Comment by sguptatw** [comment]
Yes, the issue exists. However it got resolved when I uninstalled the Gauge plugin and installed  again.

Previously I installed the VSCode plugin without uninstalling the same.

**Comment by sguptatw** [comment]
Re-opening it as the issue exists on `gauge-0.0.4.nightly-2018-04-05.vsix`

**Comment by sriv** [comment]
@sguptatw - still an issue?

observation: reinstalling VSCode + gauge-vscode seem to have fixed this.
