### ISSUE TITLE
Gauge associations should be added by default

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#232]
When Gauge is installed the IDE features should be available even when other VSCode plugins are installed.
```
"files.associations": {
        "*.spec": "gauge",
        "*.cpt": "gauge"
    }
```
should be added by default to the settings

**Comment by nehashri** [comment]
**Approach to be followed**
When Gauge VSCode plugin is started within a Gauge project workspace, the above settings should be added to the workspace. This should be done automatically without prompting the user to add the settings.

**Comment by nehashri** [comment]
should be available in nightly >= 23-4-18
