### ISSUE TITLE
Peek definition of concepts should highlight all steps also

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#234]
**Expected behavior**
The peek definition should highlight concept heading and all steps of the current concept

**Current behavior**
It highlights only the concept heading

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
java (0.6.7.nightly-2018-04-06)
js (2.2.0)
python (0.3.0.nightly-2018-04-13)
report-seed (0.0.1)
ruby (0.5.0.nightly-2018-04-11)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
