### ISSUE TITLE
Report not available in VSCode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#238]
_From @sguptatw on April 19, 2018 11:23_

**Expected behavior**
Should be able to run specs seamlessly

**Actual behavior**
no template "indexPageFailure" associated with template "Reports"

**Steps to replicate**
* Create a `gauge-js` project
* With before suite failure
```
beforeSuite(function () {
  gauge.message('suite')  
  assert.equal(1,2)  
});
```

* Run the specs
> The console gives the above error

**Version**
```
Gauge version: 0.9.8
Commit Hash: 61d692c

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
java (0.6.7.nightly-2018-04-06)
js (2.2.0)
```
VSIX - commit hash 25d1a30

_Copied from original issue: getgauge/html-report#177_

**Comment by sriv** [comment]
fix should be available in nightly >= 23/04/2018
