### ISSUE TITLE
Add run Scenario/Specification to the Command Palette

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#24]
**Proposed behavior**
While editing a Gauge specification Ctrl+Shift+P must display the commands

**Out of scope**
* Running multiple specifications

**Acceptance criteria**
- [x] "Run Specification" - run currently open specification
- [x] "Run Scenario at cursor" if a specification is open,  run the scenario at the cursor.
- [x] "Run Scenario" if the cursor is outside all scenarios - show the list of scenarios for selection.

**Comment by sguptatw** [comment]
Open questions
- [ ] Are these command(s) limited to one open specification?
To list all scenario(s) do which specification(s) do we consider?
- [ ] Can I run a specification by selecting it in the IDE. Or should it be open?

**Comment by BugDiver** [comment]
Should be available in following movies

* Gauge - 15-11-2017
* Gauge-VScode - 15-11-2017

**Comment by sguptatw** [comment]
"Run Specification" - is giving a warning that instead of running the last run specification

**Comment by BugDiver** [comment]
That's the expected behaviour for now.

**Comment by sguptatw** [comment]
@BugDiver : Kindly update all the acceptance criteria with the latest expected behaviors, so that I can proceed with the test cases.

**Comment by sguptatw** [comment]
Cancel the action of "Run Scenario at cursor" and I get
![CannotReadProperty.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46cb95942d8d979b8ae8bb73b652e0913b523e316546b3397f8fe62bab0021435a594bf849590911aafada7ef2b638768a5c0fbcd23e5a76d42103eee9dc4be05ce36ade0d97bcae8b44cae93824e7838f48371a061f8fff4f78.png)

**Comment by sguptatw** [comment]
Changed Test Cases
--------------
- [x] Should be able to run scenario at cursor
- [x] Should be able to run any scenario from the specification
- [x] Run all scenarios from a specification
- [x] Should get a warning if the open file is not a specification
