### ISSUE TITLE
gauge-message within a step is displayed as an after step message

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#240]
**Expected behavior**
The information displayed on hover should indicate that it is a step message

**Actual behavior**
It is displayed as an after step message

**Steps to replicate**
* in a `gauge-js` project, add a `gauge.message` on a step
* Run the specs from VSCode
* Open the Last run report in VSCode

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-19
Commit Hash: 58298e2

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
js (2.2.0.nightly-2018-04-13)
```

**Comment by sguptatw** [comment]
Note the behavior is similar to html-report behavior

**Comment by sriv** [comment]
This is the current behaviour of html report. messages from step implementation and afterStep hooks are accumulated and printed together.
