### ISSUE TITLE
Unable to write into workspace settings because the file is dirty

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#242]
**Expected behavior**
Should be able to change workspace settings

**Actual behavior**
<img width="468" alt="screen shot 2018-04-25 at 1 17 42 pm" src="https://user-images.githubusercontent.com/6310197/39232720-d2516db0-488b-11e8-88f3-bedafcc95b45.png">

**Steps to replicate**
* Ensure user settings do not have recommended settings
* Apply recommended settings
* Cut the recommended settings from user settings paste to workspace settings.
* Change the `"files.autoSave": "onWindowChange"`
> The above error occurs

**Version**
```
gauge-0.0.4.nightly-2018-04-24.vsix
```

Related to issue https://github.com/getgauge/gauge-vscode/issues/117

**Comment by sriv** [comment]
so what happens to the edits ? i.e. if the file is dirty then there are pending edits (possibly unrelated to gauge's settings)

**Comment by zabil** [comment]
Closing as an old issue.
