### ISSUE TITLE
If workspace already has recommended settings pop up should not appear

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#243]
**Expected behavior**
If the recommended setting is available for the current project, the pop up should not come

**Actual behavior**
Workpace settings contains
```
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 500,
```
The pop still shows

**Steps to replicate**
* Ensure user settings do not have recommended settings
* Let the workspace settings contain the recommended settings
* reload the project
> The above message appears

**Version**
```
gauge-0.0.4.nightly-2018-04-24.vsix
```

Related to issue https://github.com/getgauge/gauge-vscode/issues/117

**Comment by sriv** [comment]
fix should be available in nightly >= 27/04/2018

Now, gauge-vscode will only prompt for recommended settings only when :

- workspace/workspaceFolder settings do not contain the key (recommended or otherwise)
- user settings do not have the recomended settings.
