### ISSUE TITLE
Report of debug and run should be similar

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/gauge-vscode#244]
**Actual behavior**
In VSCode when we debug the report generated is similar to the html-report generated from console

**Steps to replicate**
* Create a `gauge-js` project
* Debug a scenario. 
* Open the report
> The format should be similar to the VSCode run

**Version**
```
gauge-0.0.4.nightly-2018-04-25.vsix
```

**Comment by sriv** [comment]
What exactly is the difference you notice?

On mac, latest gauge-vscode(HEAD), gauge(HEAD), gauge-js(HEAD) : I get these:

debugging a scenario report:
<img width="1199" alt="screen shot 2018-04-27 at 8 23 32 am" src="https://user-images.githubusercontent.com/389148/39342201-7ee75972-49f4-11e8-9a7e-5fafcc4045d6.png">


running a scenario report:

<img width="1189" alt="screen shot 2018-04-27 at 8 23 55 am" src="https://user-images.githubusercontent.com/389148/39342203-85061104-49f4-11e8-9c75-53edd7ff6ea9.png">

**Comment by sriv** [comment]
Ditto on latest vscode nightly. @sguptatw - please confirm, if issue still persists.
