### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#246]
**Expected behavior**
Should be able to cancel new project creation without an error

**Actual behavior**
Gives the error `Cannot read property '0' of undefined`

**Steps to replicate**
* Create a new project from VSCode
* `Esc` to cancel project
> Gets the error `Cannot read property '0' of undefined`

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-26
Commit Hash: 5bd699e

Plugins
-------
```

**Comment by BugDiver** [comment]
Fixed should be available in nightly >= 27-04-2018
