### ISSUE TITLE
Welcome should open by default only if Gauge project

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#249]
### Expected Behaviour
Welcome page should be opened by default (according to the welcome page settings) only if a Gauge project is open.

### Actual Behaviour
Welcome page is opened on Gauge plugin activation irrespective of whether a Gauge project is open in the workspace. 

### Steps to replicate
- Open VSCode without any folders open.
- From command palette, invoke `Gauge: Create a new Gauge Project`
- Welcome page come up by default.

*Note: This is replicable on osx*

**Comment by nehashri** [comment]
should be available in nightly >= 7-05-18

**Comment by sguptatw** [comment]
This story can be tested only with setting `versionUpgrade`. However, when settings is marked as `versionUpgrade` the `Welcome Page` is not shown when new nightly is installed.

**Suggestion**
When setting is `versionUpgrade` new nightly installations should also be considered as a different version and show the `Welcome Page`.
