### ISSUE TITLE
Show Last report should indicate if html-report is not added for current project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#252]
**Proposed behavior**
If html-report plugin is not added to the current project, show Last report should not be available in the command pallete.
> Or it can also give a message to the user that html-report is not available/added to the project.

**Current behavior**
Getting an error.

**Comment by Apoorva-GA** [comment]
If html-report is not installed, during execution html-report will be installed. So this scenario shouldn't occur.
Verified on version  `0.0.10.nightly-2019-05-10`.
