### ISSUE TITLE
All templates should be listed for project creation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#254]
**Proposed behavior**
Should list all the templates available

**Current behavior**
Only basic templates of Ruby, JS and python are listed.

**Version**
```
	
gauge-0.0.4.nightly-2018-05-08.vsix
```

**Comment by zabil** [comment]
Add the templates only when we support the language on VS Code/LSP

**Comment by zabil** [comment]
Closing this issue. Add this as a step on Language support ticket.

https://github.com/getgauge/gauge-vscode/issues/83
https://github.com/getgauge/gauge-vscode/issues/84
