### ISSUE TITLE
Creating a new project fails when gauge is not installed

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#255]
## Current behavior
* Download VS Code
* Install Gauge extension
* Try to create a new project using "Create a new Gauge Project"

It shows the following error
![gaugeerror](https://user-images.githubusercontent.com/54427/39817945-40c40438-53bd-11e8-99eb-18ab70783b7b.png)

### Information
OS: Ubuntu 18 and MacOS
Gauge binaries are not installed.

**Comment by Apoorva-GA** [comment]
Fix should be available in vscode nightly >= 10/05/18

**Comment by sguptatw** [comment]
Getting the same error on Windows when Gauge is not installed with vscode `gauge-0.0.4.nightly-2018-05-11`
