### ISSUE TITLE
Language runner logs are added irrespective of gauge.launch.enableDebugLogs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#258]
**Expected behavior**
The debug information should not be logged if "gauge.launch.enableDebugLogs": false

**Actual behavior**
The language runner information is logged irrespective of the debug information

**Steps to replicate**
* ensure `"gauge.launch.enableDebugLogs": false`
* Create a new `gauge-js` project
* Open lsp.logs
> The runner log details are available

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-09
Commit Hash: 7d99e17

Plugins
-------
js (2.3.0.nightly-2018-05-04)
```

**Comment by nehashri** [comment]
The logs are getting rolled over. 
It is also easier for user to report issues when they face issues. 
So we need not implement this
