### ISSUE TITLE
gauge.welcomePage.enabled should be true by default

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#259]
_From @sguptatw on May 14, 2018 7:54_

**Expected behavior**
Welcome Page should be available based on the settings

**Actual behavior**
`gauge.welcomePage.enabled` is false by default

**Steps to replicate**
* Ensure Gauge is not installed
* Open VSCode settings. `gauge.welcomePage.enabled` is false

**Version**
```
gauge-0.0.4.nightly-2018-05-11
```

_Copied from original issue: getgauge/gauge#1036_

**Comment by Apoorva-GA** [comment]
Should be availble in vscode nightly >= 14/05/18
