### ISSUE TITLE
Should be able to report issue from IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#260]
**Expected behavior**
From the command pallet, the user should be able to report the issue even when gauge is not installed.
> The issue should contain `vscode-gauge version` and message that `gauge` is not installed.

**Actual behavior**
`Running the contributed command:'gauge.help.reportIssue' failed.`

**Steps to replicate**
* Ensure gauge is not installed.
* Open a `gauge-js` project
* Select `Gauge:Report Issue` from the pallet

**Version**
```
gauge-0.0.4.nightly-2018-05-11
```

**Comment by Apoorva-GA** [comment]
**Expected behaviour**
Should give message `Gauge executable not found!!` instead of gauge version information.

Should be available in gauge-vscode nightly >= 14/05/18
