### ISSUE TITLE
Should give a suitable template message when initialization fails

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#261]
**Actual behavior**
The message says `Command Gauge: Create a new Gauge Project' resulted in an error.`
> The user should be able to find out went wrong.

**Steps to replicate**
* Ensure gauge is not installed
* Ensure user is offline
* Create a new project
> The above message is displayed.

**Version**
```
gauge-0.0.4.nightly-2018-05-11
```

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 15/05/18
