### ISSUE TITLE
When the initialization fails, the empty folder should not be created

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#262]
**Expected behavior**
The folder in which gauge project is to be created, should not be present if initialization fails.

**Actual behavior**
The empty folder is created

**Steps to replicate**
* Ensure gauge is not installed
* Ensure user is offline
* From IDE, create a `gauge-js` project
> Note the empty folder is created

**Version**
```
gauge-0.0.4.nightly-2018-05-11
```

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 15/05/18
