### ISSUE TITLE
Partial project files/folder should not be created

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#263]
**Actual behavior**
The directory contains gauge project related folders even when initialization is incomplete
```
d-----        5/14/2018   1:11 AM                env
d-----        5/14/2018   1:11 AM                logs
d-----        5/14/2018   1:11 AM                Properties
```
**Expected behavior**
Should contain gauge project files/folders only when the initialization succeeds

**Steps to replicate**
* `gauge init csharp` when offline

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-15
Commit Hash: 8db625f

Plugins
-------
csharp (0.10.4.nightly-2018-05-11)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
