### ISSUE TITLE
Assertion errors should be clickable

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#264]
**Actual behavior**
When there is a failure in a function called by the step impl function, the stacktrace of the actual failure is not clickable

**Steps to replicate**
* Create a `gauge-js` project
* Create a step and add impl
```
step('step <word> <number>', function (word, number) {
    somethingelse()
});

function somethingelse(){
    assert.equal(number, numberOfVowels(word));
}
```

**Version**
```
gauge-0.0.4.nightly-2018-05-15
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
