### ISSUE TITLE
Use test view container to show spec explorer

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#265]
Use the new [test view container](https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar) feature of VSCode to show the spec explorer.

**Comment by nehashri** [comment]
should be available in nightly >= 22-5-18

**Comment by sguptatw** [comment]
**Expected behavior**
Should not appear for a non gauge project.

**Current behavior**
Should appear only for gauge project.

**Comment by nehashri** [comment]
There seems to be an [issue](https://github.com/Microsoft/vscode/issues/49145) in VS Code which makes the activity bar icons to appear irrespective of view present in the container. 

Even if a separate view container with gauge icon is added, the view container for Gauge will be shown if gauge plugin is installed. The same issue will persist and needs a fix on VS Code.
