### ISSUE TITLE
Commands on pallete should be shown based on file type

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#268]
**Expected behavior**
Commands specific to a file type should be shown when file is open
- [ ] If a file type is specification, Run scenario, run specification
- [ ] If a file type is concept/impl then Find usages

**Current behavior**
All gauge commands are shown on a gauge project irrespective of the file open

Related to https://github.com/getgauge/gauge-vscode/issues/216

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
