### ISSUE TITLE
Spec explorer only seems to work if gauge project is the top level folder

### ISSUE THREAD

**Issue by justin-haight** [getgauge/gauge-vscode#269]
I have a few projects which contain gauge tests within them as a subdirectory.  When I open the master project in VSCode and try to use the spec explorer, I can't get the spec explorer context menu or any of the features of the gauge plugin.  It recognizes the extension but doesn't seem to recognize that there's a gauge project present.

If I instead open the folder containing the gauge project (so it is the top level folder in VSCode) then the spec explorer works as advertised.  It would be really nice to be able to modify my project code and the gauge tests covering the code all in one place.

```
VS-Code version: 1.23.1
Gauge Extension Version: 0.0.5

Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
python (0.3.2)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Have tried creating a [workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) and adding all the Gauge projects to the workspace instead?

**Comment by justin-haight** [comment]
I just tried that now.  Adding the gauge project folders to the workspace (right click in workspace and "add folder to workspace") allows me to use all the features the plugin has to offer.  It still doesn't like when I have something else above the gauge project (ex: biggerProject/gaugeProject).

I'm still new to using vscode.  Is the second method not an expected/standard use case?

**Comment by zabil** [comment]
@justin-haight can you give us an example of the original project folder structure?

**Comment by justin-haight** [comment]
@zabil here's a quick example of my setup where I'm seeing the problem.  I created the gauge project in the test directory via command line `gauge init python`.  The plugin recognizes the .spec file is a gauge association but if I right click in there, I get no context menus.

![gaugeexampleproject](https://user-images.githubusercontent.com/35248484/40920126-9b69c906-67d9-11e8-8f34-ffa0de579dd3.png)

**Comment by zabil** [comment]
Gauge doesn't support this at the moment. The recommended way is using separate folders and adding them to a workspace. 

That said, your use case is common. We'll try to fix this next release. Thanks for raising this!

**Comment by negiDharmendra** [comment]
Right now we look for the manifest.json file on the project root level and then start the gauge vscode 
extension. So In order to support nested gauge project I have two approaches in my mind.

* The first approach would be to look for the manifest.json recursively in the project hierarchy.

* The second approach would be to provide some configuration where the user can provide a path to gauge project.

**Open question.**
1. Should we allow users to have multiple gauge project within the project hierarchy.

**Comment by nehashri** [comment]
The Gauge extension only starts off if there is a manifest.json file present in the top level. If we try to deep dive into every folder, there will be a performance hit. So I think that configuring a property where the user defines the project roots is a good idea.
But we must also figure out, when we start the Gauge plugin in this case. 
Can it be started if there is a configuration property in the workspace?
Or should it start when a user invokes a command like `Start Gauge Server` from the command pallet?

**Comment by negiDharmendra** [comment]
Agree on the point to provide some sort of config for the user to set any directory as gauge project root.

> But we must also figure out, when we start the Gauge plugin in this case.
> Can it be started if there is a configuration property in the workspace?
Or should it start when a user invokes a command like Start Gauge Server from the command pallet?

To solve this problem we can use wildcard path identifier when defining the path of `manifest.json` file.
**Example:**
> ...
>"activationEvents": [
    ....
    "workspaceContains:**/manifest.json"
  ],
> ....

**Comment by zabil** [comment]
> Agree on the point to provide some sort of config for the user to set any directory as gauge project root.

While this is great it's not intuitive enough for the user.
The ideal case would be to not scan project automatically instead scan and initialize a Gauge project when either a spec or implementation file is opened for the first time.

**Comment by sguptatw** [comment]
The original issue is still replicable in version Gauge-VSCode `gauge-0.0.8.nightly-2018-11-27`

**Gauge version**
```
Gauge version: 1.0.4.nightly-2018-11-26
Commit Hash: f6cb60c

Plugins
-------
python (0.3.5.nightly-2018-10-31)
```

**Steps to replicate**
* `mkdir sub_project`
* `cd sub_project`
* `mkdir src`
* `mkdir test`
* `cd test`
* `gauge init python`
* `cd ../..`
* `code .`
> Gauge IDE features are not available on opening the test/specs/example.spec.

**Comment by Apoorva-GA** [comment]
@sguptatw from where are you trying to do `code .` I guess its from `sub_project` right? But doing `cd ../..` take you outside `sub_project` directory.

**Comment by sguptatw** [comment]
@Apoorva-GA sorry it is just `cd ..`. The user is still inside the sub_project folder. The steps to replicate are

**Steps to replicate**
* mkdir sub_project
* cd sub_project
* mkdir src
* mkdir test
* cd test
* gauge init python
* cd ..
* code .

> Gauge IDE features are not available on opening the test/specs/example.spec.
> The issue is observed on Windows

**Comment by sguptatw** [comment]
I have deleted the extensions folder from `%USERPROFILE%\.vscode\extensions` and installed `gauge-0.0.8.nightly-2018-11-27`. IDE features are available for a project directly in the folder but not subfolder.

**Comment by Apoorva-GA** [comment]
Make sure to delete the extensions using command `del ~\.vscode\extensions`.

**Comment by sguptatw** [comment]
@Apoorva-GA Thanks

Manually deleting the file from the `%USERPROFILE%\.vscode\extensions` did not help. After using the commande `del ...\.vscode\extensions` it worked as expected.
