### ISSUE TITLE
Collapsible icon should not appear next to a parameter in reports

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#270]
**Expected behavior**
The collapsible icon should appear for concept names

**Actual behavior**
It appears for the concept name and the parameter of the concept
<img width="408" alt="screen shot 2018-06-12 at 4 23 00 pm" src="https://user-images.githubusercontent.com/6310197/41286487-4bc10a9c-6e5d-11e8-81f2-8587d0465e0c.png">

**Steps to replicate**
* Create a gauge-js project
* Create a concept with parameter
* Use the concept in the specification
* Run it in VSCode
* Open the report
> The icon appears for the parameter as well

**Version**
gauge-0.0.6.nightly-2018-06-01.vsix

**Comment by nehashri** [comment]
should be available in 13-6-18 nightly
