### ISSUE TITLE
The code lenses should be configurable

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-vscode#272]
The user should be able to turn off the reference code lense ( maybe execution and debug as well), since sometimes there are a lot of code lenses in the file (Gauge reference + language specific reference).
Ref - https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L505
and https://github.com/eamodio/vscode-gitlens/blob/12a93fe5f609f0bb154dca1a8d09ac3e980b9b3b/package.json#L165

**Comment by sguptatw** [comment]
Is this available in the nightly gauge-0.0.7.nightly-2018-07-31.vsix?
What is the property name?

**Comment by BugDiver** [comment]
@sguptatw  Following  are the ways to configure this
* Gauge - set `gauge_lsp_reference_codelens` to  true (as env or in `properties` file).
* VS-Code - set `gauge.codeLenses.reference` to `true` in workspace settings.

**Comment by sguptatw** [comment]
Is this applicable only to the implementation source files?

**Comment by BugDiver** [comment]
> Is this applicable only to the implementation source files?
Yes. Currently, it is only applicable for implementation files.

We can make the execution codelens also configurable if users ask for it.

**Comment by sguptatw** [comment]
Currently the gauge_lsp_reference_codelens in the property file has more weightage than gauge.codeLenses.reference
