### ISSUE TITLE
Should be able to create a dotnet new project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#274]
**Expected behavior**
Should be able to create dotnet project from the IDE

**Actual behavior**
Currently only js and python projects are being listed.

**Version**
```
Gauge-VSCode - 0.0.6
```
Blocks #6

**Comment by BugDiver** [comment]
The fix should be available in nighty >= 17-07-2018

**Comment by sguptatw** [comment]
Verified on [VSCode nightly - 0.0.7.nightly-2018-07-19](https://bintray.com/gauge/gauge-vscode/Nightly/0.0.7.nightly-2018-07-19)
