### ISSUE TITLE
Should display the screenshot captured execution

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#276]
**Actual behavior**
Only screenshots captured on failure is captured and displayed

**Steps to replicate**
* Create a `gauge-csharp` project
* Add a screenshot capture
```
GaugeScreenshots.Capture()
```
* Open the project in VSCode
* Run it from the spec file
> The generated report does not have the screenshot

**Version**
```
VSCode - 0.0.7.nightly-2018-07-19
```

**Comment by shubhamsc** [comment]
Fixed should be available in nightly >= 07-08-2018
