### ISSUE TITLE
[dotnet] clicking on the continue debug is throwing an exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#277]
**Expected behavior**
Should not get an exception while debugging

**Actual behavior**
<img width="477" alt="screen shot 2018-07-20 at 2 36 19 pm" src="https://user-images.githubusercontent.com/6310197/42994012-98575c54-8c2a-11e8-8ae3-36cfed4a319f.png">

**Steps to replicate**
* Start debugging
* Click on pause debug
* Click on continue debug almost immediately
> Getting the above exception

**Version**
```
https://bintray.com/gauge/gauge-dotnet/Nightly/0.1.1.nightly-2018-07-19
```
Blocks #279

**Comment by sguptatw** [comment]
Getting the same exception when the step out button of the debug panel is used

**Steps to replicate**
* Create a dotnet project 
* Put a break point at
```
            var actualCount = CountVowels(word);
``` 
line:27 of the StepImplementation.cs
> Start Debugging
* Use the `Step in` of the debug panel on a function here
* When the debugger takes you to the first line of the method, Use `Step Out` function from the panel
> This error occurs. When I try to stop debugging getting another exception `Debugger adapter terminated unexpectedly`

**Comment by BugDiver** [comment]
Not able to replicate it. Please verify if this still exists.

**Comment by BugDiver** [comment]
Ok, I was wrong using `justMyCode` solve this problem. The project has to be built in  Debug mode then the debugger will just load user code symbols.
