### ISSUE TITLE
Released Gauge VS code plugin must hide language server output.

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#28]
### Steps to reproduce

* Install Gauge VS Code plugin
* Open a gauge project
*  Run a scenario
* The result of the test run is displayed on the console output
* Make a change in the spec file
* The output changes focus to a verbose language server messages.

### Expected behavior. 

Do not show language server output so that output of running specifications or scenarios is always in focus.

If this is required for debugging make it available only on nightly versions.

**Comment by nehashri** [comment]
Added a new config `gauge.launch.enableDebugLogs` which starts gauge with debug log level. When gauge starts with debug log level, lsp messages will be shown in the output panel.

**Comment by nehashri** [comment]
Should be available in gauge and gauge-vscode nightly >= 9-11-2017.

**Comment by nehashri** [comment]
@sguptatw when `enableDebugLogs` is set to `true`, gauge lsp is invoked with log level debug.

**Comment by nehashri** [comment]
should be available in gauge nightly > 13-11-2017

**Comment by nehashri** [comment]
Gauge logs do not output to the console when invoked with lsp flag. All log information will be sent to vscode via the `window/logMessage` request, hence  logs will be shown in vscode's output pane.

**Comment by sguptatw** [comment]
- [ ] When `gauge.launch.enableDebugLogs` property is not present the LSP logs should not be printed.
- [ ] Documentation for this feature to be added.

**Comment by nehashri** [comment]
@sguptatw when gauge.launch.enableDebugLogs is enabled, the request messages are not printed in the vscode Gauge output channel. Errors, and other log messages - info and error logs will still be printed.
Documentation has already been added. Please check the readme.
