### ISSUE TITLE
Unsupport Chinese for example,I want to print('我是中文') or print('￥')

### ISSUE THREAD

**Issue by yicaifeitian** [getgauge/gauge-vscode#282]
Unsupport Chinese for example,I want to print('我是中文') or print('￥')，it will go wrong. throwing Exception"UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 319: illegal multibyte sequence" . 
I try best to read source code, and find I can't fix it!
Thank you very much for helping fix this bug, you are all our hope! we are very very  interested in Gauge!

for more details:
filename = xx_impl.py
```python
#coding:utf-8
import os

from getgauge.python import Messages, before_scenario, step

from step_impl.utils.commonrequest import post
debug_line = '@' * 50
service_url = os.getenv('messageService')

# import io
# import sys
# sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
print('我是中文'.encode('utf-8'))


def add_repay_card(req):
    tail_url = 'bankcardService/addRepayCard'
    resp = post(service_url, tail_url, req)
    print(debug_line)
    code = resp['code']
    return code
```
D:\py\3\baozidai>gauge run specs
Python: 3.6.5
Traceback (most recent call last):
  File "start.py", line 65, in <module>
    main()
  File "start.py", line 29, in main
    load_implementations()
  File "start.py", line 35, in load_implementations
    load_files(d)
  File "E:\Program Files\Python36\lib\site-packages\getgauge\static_loader.py", line 52, in load_files
    load_files(file_path)
  File "E:\Program Files\Python36\lib\site-packages\getgauge\static_loader.py", line 47, in load_files
    ast = generate_ast(impl_file.read(), file_path)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 313: illegal multibyte sequence
Error ----------------------------------

Failed to start gauge API: Runner with pid 6972 quit unexpectedly(exit status 1).

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.0, 5a99965
        html-report (4.0.5), java (0.6.8), python (0.3.3), screenshot (0.0.1)

```
VS-Code version: 1.25.1
Gauge Extension Version: 0.0.6

Python version:3.6.5
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.5)
java (0.6.8)
python (0.3.3)
screenshot (0.0.1)
```

**Comment by BugDiver** [comment]
@yicaifeitian I'm not able to replicate this issue on my end.

### Environment

Windows 10
Python 3.6
getgauge 0.3.3

this is my implementation file
```python
#coding:utf-8
import os

from getgauge.python import Messages, before_scenario, step

debug_line = '@' * 50
service_url = os.getenv('messageService')

# import io
# import sys
# sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
print('我是中文'.encode('utf-8'))


def add_repay_card(req):
    tail_url = 'bankcardService/addRepayCard'
    resp = post(service_url, tail_url, req)
    print(debug_line)
    code = resp['code']
    return code

@step("hello")
def bad_character_in_python_file():
    pass
```

When I execute specs I get 

```
Python: 3.6.5
b'\xe6\x88\x91\xe6\x98\xaf\xe4\xb8\xad\xe6\x96\x87'
# Short Test
  ## Should not fail

Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 18ms
Success: Tests passed.
```

Can you provide some more details or a sample project where we can replicate the issue?

**Comment by yicaifeitian** [comment]
Thank, Our team met the same problem.
Our difference is: I come from China, maybe my default code is 'gbk'!
when I run test.py print('我是中文') without gauge , it will do well!
**Environment**
Windows 7
Python 3.6
getgauge 0.3.3

**Comment by yicaifeitian** [comment]
Thank you!
I fix this  issue , just 
static_loader.py

**Comment by BugDiver** [comment]
@yicaifeitian You can fork the project under your account, make changes into that and the create a PR.

**Comment by zabil** [comment]
The new release of the python plugin fixes this
