### ISSUE TITLE
print('我是中文'),output ��������

### ISSUE THREAD

**Issue by yicaifeitian** [getgauge/gauge-vscode#284]
```
VS-Code version: 1.25.1
Gauge Extension Version: 0.0.6

Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.5)
java (0.6.8)
python (0.3.3)
screenshot (0.0.1)
```
windows 7
![image](https://user-images.githubusercontent.com/18083559/43637470-bb38274e-9747-11e8-8aee-5ab8edef8122.png)

**Comment by oooooold2** [comment]
import codecs
assert codecs.encode('我是中文', "utf-8") == '我是中文'

我现在比较好奇的是怎么在spec里加中文

**Comment by zabil** [comment]
This should be fixed in the latest version of the gauge python plugin.
