### ISSUE TITLE
Clearing the notification should not assume telemetry choice by the user

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#285]
**Expected behavior**
When the message of telemetry is cleared/dismissed. Telemetry option should not be assumed to be selected by the user

**Actual behavior**
On dismissing the message, a user selection is being assumed.

**Steps to replicate**
* Install gauge
* Remove the config folder
* Open the terminal for a gauge project
* Run gauge specs.
> This displays the telemetry message
* open a gauge project in vscode
> A message of telemetry is displayed
* Click dismiss/clear
* Close the project
* From the terminal run gauge specs
> The telemetry message is not displayed

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-03
Commit Hash: 7a7b53b

IDE - 0.0.7.nightly-2018-07-31
```
Blocks #283

**Comment by sriv** [comment]
fix should be in *gauge* nightly >= 04/08/18

**Comment by sguptatw** [comment]
As on 06/08/18 Latest Gauge nightly available is 
gauge-1.0.1.nightly-2018-08-03-windows.x86_64.zip
