### ISSUE TITLE
Support Debug for C#

### ISSUE THREAD

**Issue by angelovstanton** [getgauge/gauge-vscode#288]
Based on the information here- https://marketplace.visualstudio.com/items?itemName=getgauge.gauge
it seems the integration doesn't support debugging for C#

I tried to debug my tests but it seems it is not working. Do you plan to add such support? Most of the things are working perfect in VS Code for C#. Right now I prefer to use VS 2017 but your plugin there is totally not working. I switched to VS Code and it was great till I had to debug my tests...

**Comment by zabil** [comment]
Yes, there's support features like, debug, refactoring etc with available in the latest [nightlies](https://github.com/getgauge/gauge-dotnet#nightly-installation) 

The official release will be out before the end of this month.

**Comment by zabil** [comment]
@angelovstanton a new release of Gauge and .net core plugin is out! Please update Gauge and plugins to get all features working and please give us feedback.

**Comment by angelovstanton** [comment]
@zabil thank you. I will check it.
