### ISSUE TITLE
Should recognize a gauge installation locally installed using npm

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#290]
**Expected behavior**
Should recognize a gauge installation locally installed using npm. 

**Actual behavior**
the installation is not recognized by VSCode even after explicitly adding <project_path>/node_modules/.bin to path.
> `gauge version` and `which gauge` work as expected after explicitly adding to the path

<img width="1306" alt="screen shot 2018-09-19 at 2 21 11 pm" src="https://user-images.githubusercontent.com/6310197/45742317-54561f00-bc17-11e8-97b9-1faa9cc0ccba.png">

**Steps to replicate**
* Ensure gauge is not installed previously
* in gauge js-taiko project, install gauge locally using npm
`npm install @getgauge/cli`
* Add the <project>/node_modules/.bin to path
* Reload the gauge project. This still shows gauge as uninstalled.

Related to https://github.com/getgauge/gauge/issues/1157

**Comment by sguptatw** [comment]
This does not happen when `-g` option is used while installing gauge with npm.

**Comment by kuechlerm** [comment]
@sguptatw I cannot reproduce that it works with gauge installed via `npm i -g @getgauge/cli`
I see the same error message that you show in your inital comment.

I run Windows 10 with the current VS Code.

**Comment by sguptatw** [comment]
@kuechlerm 
Please confirm if gauge is installed successfully? 
Can you please restart the command prompt and execute `gauge version`  and paste the details here

> Assuming a VSCode project is already open, for Gauge to be recognized it has to be reloaded. Kindly confirm if you are facing the issue despite restarting the IDE as well.

**Comment by sguptatw** [comment]
@kuechlem Thanks for your feedback. 
Able to replicate the issue.
Gauge is installed globally using `npm install -g @getgauge/cli`. However VSCode does not recognize it.

**Steps to replicate**
* Remove all gauge versions installed
* Install gauge using `npm install -g @getgauge/cli`
> `where gauge`  on command line gives
```
...\AppData\Roaming\npm\gauge
...\AppData\Roaming\npm\gauge.cmd
```
* Open gauge project in VSCode.
> The above error can be seen.
![gauge_unavailable.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46ef958f2487bcbc81e8a942ad51f1962543653f6b14b1247a80e03cfd183954595a1aa4400e0a12ffaadc7fa6b23a708a585aee82685d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3925e48d88483f19041c8bed10.png)

**Comment by francois-nitenberg** [comment]
@nehashri , this issue was initially a feature request for to detect a local gauge installation (in ./node_modules).
Is there another issue tracking this? It seems that the point made from the reporter was misunderstood.
