### ISSUE TITLE
Add telemetry to measure Gauge and Taiko usage

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#291]
We'd like to measure adoption of Gauge and adoption to make sure that we are building the right product and solving the right problems.

Our aim is to integrate Gauge extremely well with Taiko so that writing tests are easy.

This must be default opt-in like the telemetry in Gauge but with warnings informing the user about data collection until they opt-in or opt-out. 

The collected data must not have any personal or sensitive information.

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge-js#173
