### ISSUE TITLE
Extract code to step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#292]
**Expected behavior**
User should be able to select a code block in the implementation file and extract it to a gauge step.
> It should create a new gauge-step in the same implementation file.

**Current behavior**
No support to extract a portion of the code to a step

**Open Question**
* Should the current step used in the spec file be appended with the new step?

**Comment by BugDiver** [comment]
The scope of this feature has been changed and being tracked as https://github.com/getgauge/taiko/issues/273

**Comment by sguptatw** [comment]
Closing this issue as the scope has changed and tracked as a part of getgauge/taiko#273
