### ISSUE TITLE
Add telemetry to measure plugin usage.

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-vscode#293]
Add vs code plugin usage telemetry data. 
The data should contain information about actions taken from vs code like, `formatting, refactoring, goto def`. Capture language runners and os as well.

**Comment by zabil** [comment]
To better understand adoption we want *active* VS Code usage grouped by language. Active usage means editing (i.e formatting, refactoring, goto definition etc) and running specs from VS Code. For e.g. if a user invokes go to definition on a Gauge JavaScript project then mark it as "Goto definition" action and it's language server protocol event (VS Code for now) for JavaScript.

**Comment by NivedhaSenthil** [comment]
• code completion
• goto definition
• step references
• formatting
• rename
• generate concept
• generate step

Are covered from LSP actions in gauge core. Execution and Debugging has to be captured from plugin.

**Comment by NivedhaSenthil** [comment]
done as part of https://github.com/getgauge/gauge/issues/1251

**Comment by sguptatw** [comment]
Closing it as the updated requirements are tracked as a part of https://github.com/getgauge/gauge/issues/1251
