### ISSUE TITLE
Misleading message on installation of Gauge plugin

### ISSUE THREAD

**Issue by nyuday** [getgauge/gauge-vscode#295]
The initial telemetry message on installation of Gauge VS Code plugin gives the user the illusion that Gauge will not collect data till they choose to participate. 

New corrected message. 

"This installation of Gauge collects usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. Read more about [Gauge telemetry](https://gauge.org/telemetry). "

Button Options: Opt-Out / Ignore

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
