### ISSUE TITLE
Remove the getting started page

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#296]
The default getting started page is outdated and the content is based on the old website.
Update this.

**Comment by negiDharmendra** [comment]
@zabil Right now there is no way for us to display a notification when a user installs the extension. We can do this only when the extension is activated. 
> When the user clicks "Learn more" it takes the user to a gauge specific website with information specific to Gauge and the language runner.

Does this mean `Learn more` link will open with the different web page for different Gauge runner?

**Comment by zabil** [comment]
> We can do this only when the extension is activated.

Yes that's right. Display the notification when the user opens a new Gauge project.

> Does this mean Learn more link will open with the different web page for different Gauge runner?

For now this can point to https://docs.gauge.org

**Comment by zabil** [comment]
Please use this message

"Gauge plugin initialised." and the buttons "Learn More" and "Skip" with a check box option "Do not show this again"

**Comment by negiDharmendra** [comment]
> with a checkbox option

@zabil I don't think so we can do this as `vscode` notifications does not support `checkbox` in notifications.

**Comment by zabil** [comment]
Use buttons for both.

**Comment by Debashis9012** [comment]
Currently this works as excepted.
```
Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647
Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-18)
js (2.3.4.nightly-2018-12-20)
gauge-0.0.8.nightly-2019-01-21.vsix
<img width="518" alt="screen shot 2019-01-24 at 12 31 35 pm" src="https://user-images.githubusercontent.com/46309201/51660582-38eb8e00-1fd4-11e9-9ec8-e870c1991c7b.png">

```
