### ISSUE TITLE
How do I turn off vscode setting recommendation?

### ISSUE THREAD

**Issue by fengzhou0x** [getgauge/gauge-vscode#302]
Whenever I open vscode, the gauge extension always recommends some settings to vscode, which I don't want. How do I turn off the recommendation?

**Comment by Apoorva-GA** [comment]
Could let us know as to, which language you are using? and what exact recommendations are you getting?

**Comment by Apoorva-GA** [comment]
Also wanted to understand why you prefer to not use the recommended settings?
Because certain gauge-vscode extenstion features(diagnostics, autocomplete etc) may not work as expected if these settings are not applied.

**Comment by fengzhou0x** [comment]
I don't wan any of those 2 autosave settings.

My project is configured to re-compile when files are changed. Autosave causes many unnecessary compilations while I'm just typing, thinking and not ready to compile yet, which slows everything down.

Can you at lease not pop the recommendation on startup if I clicked ignore? It's annoying having to clicking "Ignore" every time I reopen vscode.

**Comment by nehashri** [comment]
The solution here is to have another option which says `Ignore Always` button along with `Apply & Reload` and `Ignore`.

**Comment by fengzhou0x** [comment]
That's great, thank you!
