### ISSUE TITLE
Should be able to debug with latest my-python.python

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#304]
**Expected behavior**
User should be able to seamlessly debug

**Actual behavior**
Getting error `use of closed network connection`

**Steps to replicate**
* Open a gauge-python project in VSCode
* Ensure `my-python.python` is `2018.10.1`
* Debug a scenario
> Getting the exception `use of closed network connection`
> Note: Debugging works as expected in `2018.9.1`

**Comment by negiDharmendra** [comment]
@sguptatw Which version of python you are working on. I have tried with python 2.7 and python 3.7 and it works fine. 

**My setup:**

- vscode 1.29.1
- python(2.7.15_1 and 3.7.1)
- ms-python.python 2018.10.1
- gauge-python (0.3.5.nightly-2018-10-31)

**Comment by reachcsekar** [comment]
When is the nightly expected to be available? I dont see one in https://bintray.com/gauge/gauge-vscode/Nightly

**Comment by negiDharmendra** [comment]
@reachcsekar Sorry for the confusion. Please try with this [gauge-python](https://bintray.com/gauge/gauge-python/Nightly)-0.3.5.nightly-2018-10-31  nightly build, not the gauge-vscode nightly.

**Comment by sguptatw** [comment]
Working as expected after upgrading to gauge-python nightly `0.3.5.nightly-2018-10-31`
