### ISSUE TITLE
Handle loading of non-javascript gauge projects.

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#31]
### Steps to reproduce
```
$ gauge init ruby
$ code .
```
Open `example.spec`. All the steps are highlighted as red with the following errors on hover.
"Connection closed 127.0... cause: EOF"
"write tcp 127.0.0.1:42569->127.0.0.1:52118: use of closed network connection"

### Expected behavior.
Disable gauge features that don't work for non-javascript projects.

**Comment by nehashri** [comment]
available in gauge nightly >= 10-11-2017
