### ISSUE TITLE
Show recommended settings in command pallete should have the Ignore always option

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#310]
**Expected behavior**
Show recommended settings in command pallete should have the Ignore always option

**Actual behavior**
User is able to select `Ignore Always` on the pop-up suggesting Gauge-recommendations. However the command pallete does not reflect this option

**Steps to replicate**
* Open a Gauge project
* Open the command pallete
* Open Gauge configuration
> `Show Recommended Settings` is still a boolean

Even in the User settings this reflects as a boolean. How can I differentiate between `Ignore` and `Ignore Always`?
![showrecommendedsettings](https://user-images.githubusercontent.com/6310197/49201791-559a8980-f3c8-11e8-91e3-35850d42d05a.png)

**Version**
```
Gauge VSCode - gauge-0.0.8.nightly-2018-11-27
```
> Blocks #302 #298

**Comment by sguptatw** [comment]
The current value is getting defaulted to the first value. But that is not the user selection. To solve this we should have the first option as `Select`. Which indicates that the user has not chosen the recommendedSettings yet.

**Comment by Apoorva-GA** [comment]
- Renamed `Ignore` to `Remind me later`, and its the default value. 
- Renamed `Ignore Always` to `Ignore`. 
- `Apply & Reload` remains the same.


The fix should be available in nightly >= 20-12-2018
