### ISSUE TITLE
Support for Java Maven projects

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#311]
### Current behaviour

The Gauge VS code plugin does not handle dependencies on Gauge Maven Java projects. 

### Expected behaviour

Gauge VS code plugin must work with Gauge Java Maven projects.

* Support creating a Gauge maven project from from the command pallete
* Recommend the [maven](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven) plugin.
* Once the maven plugin is configured Gauge specification code lens actions "Run/debug scenario", "Run/debug Spec" must run their equivalent gauge maven plugin commands.
* All the command pallette actions like "Run all Specifications" etc must run their equivalent maven commands
* Use the `-q` action to reduce verbosity by default

Things to watch out for
* Gauge runner compiles a java maven project on launch.
* All features must work on maven multi module projects.
* Check if the preview spec feature is important
* Must allow user to configure Gauge tags and load environments while executing specs.

**Comment by Debashis9012** [comment]
Tested the above feature in the below version:
Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647

Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-24)
gauge-0.0.8.nightly-2019-01-30.vsix
