### ISSUE TITLE
can't evaluate field Screenshot in type *generator.result

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/gauge-vscode#312]
_From @sguptatw on November 29, 2018 6:57_

**Expected behavior**
Should get the screenshot seamlessly

**Actual behavior**
Getting the error `[html-report]2018/11/29 11:32:00 template: Reports:234:35: executing "stepFailureDiv" at <.Screenshot>: can't evaluate field Screenshot in type *generator.result`

**Steps to replicate**
* Create a new `gauge-python` project
* Add step with implementation
```
@step("something")
def something():
    assert False, "Add implementation codesdfsdf"
```
* Use this in the spec
* Run the scenario from the **IDE**
> The above error occurs

**Version**
```
Gauge-VSCode - gauge-0.0.8.nightly-2018-11-27
Gauge version: 1.0.4.nightly-2018-11-26
Commit Hash: f6cb60c

Plugins
-------
python (0.3.5.nightly-2018-10-31)
```

_Copied from original issue: getgauge/gauge-python#122_

**Comment by shubhamsc** [comment]
When we were implemented taking a custom screenshot for hooks. we rename default screenshot field to failureScreenshot and screenshots for others. somehow it left to update in vs code. so i just update that. Now it working fine.
## Before the fixed
<img width="1062" alt="screenshot 2018-11-30 at 4 23 56 pm" src="https://user-images.githubusercontent.com/34643008/49285328-26b20f80-f4bd-11e8-8aa4-378c65204f02.png">

## After the Fixed
<img width="1020" alt="screenshot 2018-11-30 at 4 20 47 pm" src="https://user-images.githubusercontent.com/34643008/49285356-36c9ef00-f4bd-11e8-9b1f-42c4535f3292.png">

**Comment by sguptatw** [comment]
[Blocker] - The latest nightly available is 0.0.8.nightly-2018-11-27

**Comment by sguptatw** [comment]
Not getting the error any longer but the report opened in VSCode does not contain the screenshot.

**Steps to replicate**
* Create a `gauge-js` project
* Change the step_implementation.js to
```
/* globals gauge*/
"use strict";
const { openBrowser,write, closeBrowser, goto, press,text, contains } = require('taiko');
const assert = require("assert");
const headless = process.env.headless_chrome.toLowerCase() == 'true' ? true : false;

// beforeSuite(async () => openBrowser({ headless: headless }));

// afterSuite(async () => closeBrowser());

// step("Goto Google's search page", async () => goto('http://google.com'));

// step("Search for <query>", async (query) => {
//     await write(query);
//     await press('Enter');
// })

// step("Page contains <content>", async (content) => {
//     assert.equal('Exists', (await text(contains(content)).exists()).description);
// });


step("failing step", async function() {
	throw 'Unimplemented Step';
});
```
* Change the example.spec to 
```
# Getting Started with Gauge

## Search Google

* failing step
```
* Run Scenario from IDE
* Open the report
> This does not show the screenshot

**Comment by sguptatw** [comment]
Tracking screenshot not available as a part of https://github.com/getgauge/gauge-js/issues/177
