### ISSUE TITLE
Add step using to scenario using Taiko

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#317]
## Current behavior

For a specification 

```
## Search Google

* Goto Google's home page (1)
* Search for "github Taiko" (2)
* Page contains "getgauge/taiko" (3)
```

To add a step

```
* Second page also contains "getgauge/taiko" (4)
```

The user must open a REPL run implementations for (1), (2), (3) before recording (4) using #292 

## Proposal

Make it easy to run existing steps and launch a REPL to record further steps. For e.g. a code lens "Record step"

```
## Search Google

* Goto Google's home page (1)
* Search for "github Taiko" (2)
* Page contains "getgauge/taiko" (3)
Record step
```
This will run all the steps in the scenario and launch the Taiko REPL in VS Code terminal. The user can use the `.step` feature to record (4)

**Comment by sriv** [comment]
Perhaps this can be extended to insert a recorded step? If so, then rather than code lens, it should be a code action.

**Comment by zabil** [comment]
Yes that sounds better.
Maybe a code action on an unimplemented step that says "Record step implementation"

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
