### ISSUE TITLE
Apply and reload in the command palette should apply the recommended settings

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#318]
**Expected behavior**
Apply and reload in the command palette should apply the recommended settings

**Actual behavior**
It does not apply the recommended settings

**Steps to replicate**
* Open the command palette
* Change the Recommended settings to ignore
* Change the `Auto Save Delay` to `1000`
* Reload the project
* Now change it `Apply and reload`.
* Reload the project
> The selection is `Apply and reload` but the value of Auto Save is not changed to the recommended setting

**Version**
```
gauge-0.0.8.nightly-2018-12-20
```
> Blocks #302

**Comment by Apoorva-GA** [comment]
Nightly gets triggered at IST 1PM every day.

**Comment by sguptatw** [comment]
**Question**
If the setting is `Apply & Reload`, the user changes the recommended settings to something else. Now what should be the behavior on reload?

**Comment by Apoorva-GA** [comment]
It should apply the recommended settings.

**Comment by sguptatw** [comment]
**Verified with version**
```
gauge-0.0.8.nightly-2019-01-03.vsix
```
