### ISSUE TITLE
Java debug option should work

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#321]
**Expected behavior**
Java debug option should work

**Actual behavior**
The breakpoint is not being honored

**Steps to replicate**
* Open a gauge-java project in VSCode
* Put a debug point in the implementation file
* Open a spec file
* Reload the project (This resolves the unwanted undefined step definitions)
* Debug a scenario
* The spec is getting executed without stopping at the debug point

**Version**
```
gauge-0.0.8.nightly-2018-12-20.vsix
```
> Blocks https://github.com/getgauge/gauge-vscode/issues/83

**Comment by negiDharmendra** [comment]
**Known Issues**
- [Consecutive debug from IDE](https://github.com/getgauge/gauge-vscode/issues/326)

**Comment by sguptatw** [comment]
Verified in version
```
gauge-0.0.8.nightly-2019-01-07.vsix
```
