### ISSUE TITLE
No classPath specified

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#323]
**Expected behavior**
If a project is created using gauge template, the classPath details should be taken care of without user intervention.

**Actual behavior**
On a newly created project, if I add a compilation error and reload I get this message. The compilation errors are not displayed. 

**Steps to replicate**
* Create a new gauge-java project in VSCode
* Ensure there is a compilation error
* Reload the project
![classpath](https://user-images.githubusercontent.com/6310197/50581254-160b0580-0e7e-11e9-8adc-183519825603.png)

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2018-12-28)
```
VSCode - gauge-0.0.8.nightly-2018-12-27

Blocks https://github.com/getgauge/gauge-vscode/issues/83

**Comment by nehashri** [comment]
I guess the only option here is to go with Approach 2. IMO, Auto generating the files every time the project is opened in VSCode should be good enough.

**Comment by Debashis9012** [comment]
Tested above steps able to reproduce it in windows but it works fine in mac.
Version:

```
Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647
gauge-0.0.8.nightly-2019-01-24.vsix
```

**Comment by Debashis9012** [comment]
Tested this issue with both default and custom path of gauge. Its working as excepted in both mac and windows os.
Versions:
```
Gauge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647

Plugins
-------

java (0.7.0.nightly-2019-01-24)
gauge-0.0.8.nightly-2019-01-30
```
