### ISSUE TITLE
Should be able to create java maven project from IDE using default options

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#324]
**Expected behavior**
Should be able to create java maven project from IDE

**Actual behavior**
Unable to create a java_maven project from IDE

**Steps to replicate**
* Open the VSCode IDE
* Create a new `gauge java maven` project from the IDE
* Press enter to select the default option for group ID. 
> The project is not created but the process of creating the project is terminated

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2018-12-28)
```
VSCode - gauge-0.0.8.nightly-2018-12-27

> Blocks https://github.com/getgauge/gauge-vscode/issues/311

**Comment by BugDiver** [comment]
@sguptatw There is no default option provided for group ID. The text shown in the background is just the hint how a group ID should look like.
I found it hard to set up a default value. If we provide a default value then the user can press enter to choose it, but the user can press enter or escape at any point and it won't be easy to distinguish between the two since in both cases the value will be empty.

**Comment by sguptatw** [comment]
Fair enough but the process should not exit if a value is not provided. It should prompt until the user has provided a valid input. Currently it exits without giving an error or creating the project.

**Comment by Apoorva-GA** [comment]
GroupId is defaulted to `example` and version to `1.0-SNAPSHOT`.
User will be prompted to enter name for the new project being created.(which will be artifactID).

**Comment by Debashis9012** [comment]
The above steps has been validated in both mac and windows os. 
Kindly find the below observations.

In windows: We are able to create java maven project from IDE successfully. 

In Mac: We are not able to create java maven project.  In IDE footer we are
getting "Creating project from maven archtype" 
message with a loading icon for infinite period of time.
Creating java maven project seems a no ending process in mac os.

   **Verified with version**
```
Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-15)

gauge-0.0.8.nightly-2019-01-16.vsix
```

**Comment by Debashis9012** [comment]
Tested the above steps its working in both windows and mac os.

   **Verified with version**
```
Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-

gauge-0.0.8.nightly-2019-01-21.vsix
```
