### ISSUE TITLE
Should recommend Gauge-vscode extension if it is not installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#327]
**Expected behavior**
Should recommend Gauge-vscode extension if it is not installed

**Actual behavior**
Not getting the recommendation

**Steps to replicate**
* Ensure gauge-vscode is uninstalled.
* Create a gauge project
> This adds the .vscode/settings.json with the file associations
* Open it in VSCode
* Open a spec file
> It is not showing the gauge-vscode as the recommended plugin
![Screen Shot 2019-01-03 at 4.41.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226454f06b7191a37cf1162a4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19041c95df24de44c56ad113f65e3712431.png)

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
