### ISSUE TITLE
Find all step references in command pallette

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#33]
The feature provided by #16 must be available in the command pallete as "Gauge: Find All Step References"

**Comment by BugDiver** [comment]
should be available in following nightlies
* Gauge - 27-11-2017
* Gauge-JS - 27-11-2017
* Gauge-VsCode - 27-11-2017

**Comment by sguptatw** [comment]
OS- Windows
**Version**
```
Gauge version: 0.9.6.nightly-2017-11-27
Commit Hash: ab40a8e

Plugins
-------
js (2.0.3.nightly-2017-11-27)
```
IDE - gauge-0.0.3.nightly-2017-11-27.vsix

**Comment by sriv** [comment]
@sguptatw - what exactly is the issue?

**Comment by sguptatw** [comment]
@sriv : I was using `Find All References` and not gauge specific command in the palette.

Works as expected, hence closing the issue
