### ISSUE TITLE
Stop current execution must stop the current run/debug session

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#332]
**Expected behavior**
Stop current execution must stop the current run/debug session

**Actual behavior**
Getting the following message even after `stop current execution` and then debug again
![aspecificationisstillrunning](https://user-images.githubusercontent.com/6310197/50876367-b323ec00-13f2-11e9-99de-4a95e5fe77ea.png)

**Steps to replicate**
> Observed on Windows
* Open the gauge-tests project
* Start debugging
> The debug seems hung
* Click on debug again
> The above message is seen
* Now `stop current gauge execution` from the command palette
* Click on debug again
> The above message is shown

**Version**
```
Gauge version: 1.0.4.nightly-2019-01-08
Commit Hash: 408b09f

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2019-01-07)
```
IDE Version - gauge-0.0.8.nightly-2019-01-07

> Blocks #83

**Comment by Debashis9012** [comment]
Tested the above steps its working as excepted.
   **Verified with version**
```
Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-18

gauge-0.0.8.nightly-2019-01-21.vsix
```
