### ISSUE TITLE
Should be able to debug a java project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#333]
**Expected behavior**
Should be able to debug a java project

**Actual behavior**
Debug process seems hung

**Steps to replicate**
> Observed on Windows
* Open the gauge-tests project
* Start debugging
> The debug seems hung

**Version**
```
Gauge version: 1.0.4.nightly-2019-01-08
Commit Hash: 408b09f

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2019-01-07)
```
IDE Version - gauge-0.0.8.nightly-2019-01-07

> Blocks #311
> Blocks #344

**Comment by Debashis9012** [comment]
Tested the above steps, able to debug  java project.

Verified with version

Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-

gauge-0.0.8.nightly-2019-01-21.vsix
