### ISSUE TITLE
Importing a csv as a spec level datatable doesn't work.

### ISSUE THREAD

**Issue by ConfusedSky** [getgauge/gauge-vscode#334]
Tests run correctly but there are syntax errors and no auto-completion for table.

![image](https://user-images.githubusercontent.com/12839429/50917209-d26e4980-13f1-11e9-8dc7-43181a9ca9b2.png)

## Steps to reproduce:
Initialize a new python project `gauge init python`
Create a file `content.csv` in the root directory
Create this specfile: 
```
# With csv file

This is an executable specification file. This file follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.

table:/content.csv

* Vowels in English language are "aeiou".

## Vowel counts in single word

tags: single word

* The word <Word> has <Vowel Count> vowels.```

**Comment by ConfusedSky** [comment]
I see now. the vscode didn't like the '/' in front of content.csv works now

**Comment by sriv** [comment]
The `/` in front, i.e. `/content.csv` tells gauge that this is an absolute path and is read from the root of the file system. In your case you probably have it in the root of your project, so a relative path is what you should be using in that case.

Glad you sorted this out!

**Comment by ConfusedSky** [comment]
Yea I realized that was the issue. Weirdly enough running gauge from the command line still worked though!
