### ISSUE TITLE
Unable to open Last Execution Report for a maven project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#336]
**Expected behavior**
Unable to open Last Execution Report for a maven project

**Actual behavior**
Should be able to open the Last Execution Report for a maven project

**Steps to replicate**
* Create a gauge maven project
`gauge init java_maven`
* Open in IDE
* throw an Exception in the context step
```
    @Step("Vowels in English are <oneMore>")
    public void setLanguageVowels(String vowelString) throws Exception {
        throw new Exception("here");
        // vowels = new HashSet<>();
        // for (char ch : vowelString.toCharArray()) {
        //     vowels.add(ch);
        // }
    }
```
* Run the gauge scenario from the IDE
* Open the `Show Last Run Report` in the IDE
> The following error is displayed

<img width="453" alt="screen shot 2019-01-11 at 9 16 09 am" src="https://user-images.githubusercontent.com/6310197/51012281-6a02a200-1582-11e9-841b-02886229b179.png">

**Version**
```
Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
java (0.7.0.nightly-2019-01-07)
```
**IDE** - gauge-0.0.8.nightly-2019-01-09.vsix

> Blocks https://github.com/getgauge/gauge-vscode/issues/311

**Comment by Debashis9012** [comment]
Tested the above steps, able to reproduce it.

Verified with version
```
Gauge version: 1.0.4.nightly-2019-01-09
Commit Hash: 33123a1

Plugins
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-

gauge-0.0.8.nightly-2019-01-21
```

**Comment by Debashis9012** [comment]
Verified in the latest nightly, its working in both the os windows/mac.

```
gauge-0.0.8.nightly-2019-01-24.vsix
```
