### ISSUE TITLE
The step outside src dir are recognised as duplicate implementation

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-vscode#346]
Step to replicate
* `gauge init java`
* Open project in vscode
* Copy `src/test/java/StepImplementation.java` to the project root.
* Open the newly created file
* Observe the problems section

```
Gauge version: 1.0.4
Commit Hash: 33123a1

Plugins
-------
html-report (4.0.6)
java (0.7.0)
js (2.3.4)
php (0.0.1)
python (0.3.5)
screenshot (0.0.1)
```

**Comment by Debashis9012** [comment]
Implementation file outside src directory does not consider. This is working as excepted.
Tested in the below version

```
java (0.7.0.nightly-2019-01-24)
```
