### ISSUE TITLE
Display of reports generated outside VS Code

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#350]
#### Current behaviour
* A gauge project in VS Code 
* Run Gauge tests in the VS Code terminal, or in any other terminal 
* From the command palette select "Show last run report"

As the report is generated outside vs code it does not render correctly.

#### Expected behavior
Option 1: Generate VS code's report and `gauge run` reports in separate folders. The only problem is the reports will be out of sync and "Show last run report" will not reflect the pass/fail state of the test suite when they run the tests from VS Code's terminal or an external terminal.

Option 2: Display a notification when reports generated outside VS Code is opened using "Show last run report" with the message "Do you want to open this report in a browser?" Yes/No

**Comment by zabil** [comment]
Here's a proposed solution.
Instead of displaying HTML reports inside VS Code. Generate a JSON report, parse and display the JSON report inside VS Code. This way existing reporting functionality is untouched.

**Comment by nehashri** [comment]
HTML report is a required plugin. JSON report is not a required plugin, it is also not maintained by Gauge team. It may be easier to make html-report generate two reports.

Another option is to generate the default report first. When the user invokes `Show last run report` from VSCode, we regenerate the report with VSCode theme. This can be done by setting `﻿save_execution_result = true` to save the results. To regenerate, we can call html-report using `html-report -i .gauge/last_run_result -o <vscode report folder> -t <vscode report theme>`. 
In  this case, the VSCode report is generated only when user needs it.

**Comment by zabil** [comment]
Yes sounds like a good option.
i.e generate normal reports by default and lazy generate the VS code report.
We could also add a flag that will open the original html report in the browser instead of VS code. Maybe even change the default behaviour to avoid all these issues and have one consolidate place for all the nice report features.

**Comment by sriv** [comment]
If we are regenerating, perhaps an optimization would be to regenerate only if it is not a vscode themed report. Also, some hint to indicate that this report was for a run outside vscode would be good.

**Comment by nehashri** [comment]
> some hint to indicate that this report was for a run outside vscode would be good.

I think what we will be doing is to generate the default theme report even if run from VSCode. So this hint is not needed.

**Comment by Apoorva-GA** [comment]
Should be addressed as part of #354 and #362
