### ISSUE TITLE
VS code support for nested dir is broken

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/gauge-vscode#355]
**Expected Behaviour**
Gauge IDE features should be available on opening the test/specs/example.spec.

**Actual Behaviour**
Gauge IDE features are not available on opening the test/specs/example.spec.

**Steps to replicate**
* mkdir sub_project
* cd sub_project
* mkdir src
* mkdir test
* cd test
* gauge init python
* cd ..
* code .

**Versions**
Gauge Extension Version: gauge-0.0.9.nightly-2019-02-19.vsix

Gauge version: 	
gauge-1.0.5.nightly-2019-03-20

**Comment by Debashis9012** [comment]
Gauge ide features are working properly.
This issue has been verified and found fixed. Tested with the below version
```2019-03-26```
