### ISSUE TITLE
Error for unimplemented steps in Concepts displayed incorrectly

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#36]
### Steps to reproduce

* Init a gauge js project
```
$ gauge init js
```
* Create a new concept `sample.cpt` with contents
```
# This is a concept
* An unimplemented step
```
* Use `This is a concept` in example spec, multiple times

### Current behavior

* The error is not highlighted in `sample.cpt`
* The specification header of `example.spec` displays error with the message 'Step implemetation not found`.
* The number of error messages = number of time the concept is used in the specification

### Expected behavior

* Highlight the steps with error in the concept file
* Highlight the concept with error in the specification file

**Comment by Apoorva-GA** [comment]
Should be fixed as part of https://github.com/getgauge/gauge/issues/823.

**Comment by sguptatw** [comment]
**Expected behavior**
In a new concept, when there is an unimplemented step - it should show the error

**Actual behavior**
In a new concept file, unimplemented step error does not show up

**Steps to replicate**
* Create a new concept file
* put an unimplemented step
> No error is displayed even after saving or adding a new line and saving

**Comment by sguptatw** [comment]
Duplicate concept definitions are not indicated

**Steps to replicate**
* Project - [test1 (2).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46fc918937d3c3e1dda0fd0fe64de29b234324676b5ee17e26d0e770ee447e075c0c1bf8415c5944fcfdd828f5b33e62964e49bc8f3900299f7744eeaa880dbe06b0218e4e84b4bb824cc0ea3f23e099c2.zip)
* Open in VSCode
The concept named `Concept` has duplicate definitions.
* Open the concept files `one.cpt` and `newConcept.cpt`. 
> Observe they do not indicate the duplicate `Concept` definitions.

**Comment by sguptatw** [comment]
**Expected behavior**
Concept Circular reference should be shown in a both usages.

**Actual behavior**
Circular reference is shown only on one usage

**Steps to replicate**
* Create concepts with circular reference
```
# Concept1
* Concept2

# Concept2
* Concept1
```

**Comment by Apoorva-GA** [comment]
Should be fixed as part of getgauge/gauge#823.

**Comment by sguptatw** [comment]
Please find issue comments inline

**Comment by Apoorva-GA** [comment]
Errors for concepts are displayed only if the concept is used in the spec file.
