### ISSUE TITLE
Show last run report should work when custom report dir is set and when overwrite report is set to false

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-vscode#362]
- Reports directory is configurable through `gauge_reports_dir` property. If the user has configured it to something else then they won't be able to open it through vscode command palette. 
- The same issue will occur when `overwrite_reports` is set to false.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the ``` gauge-0.0.10.nightly-2019-04-09 ``` version
