### ISSUE TITLE
User unable to debug 

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-vscode#367]
**Actual behavior**
User should be able to debug. 

**Excepted behavior**
Debug process fails. Execution does not stop at the debug point.

**Steps to reproduce**
1. create a ruby sample project by using `gauge init ruby`
2. Go to step implementation for any of the step under the spec and keep a debug point
3. Hit on "Debug Scenario" option from vs code

**Versions**
gauge: ```1.0.4 ```
gauge ruby plugin: ``` 0.5.2 ```
vs code :   ``` 1.33.1 ```

Refer : https://gitter.im/getgauge/chat?at=5cbdfceb97dcb371d8f626cc

**Comment by Debashis9012** [comment]
After fix I have followed the above steps to reproduce. I am able to replicate it.
Tested version ```gauge-0.0.10.nightly-2019-05-10.vsix```

**Comment by Apoorva-GA** [comment]
Fix should be available in nightly >= 15/5/19

**Comment by Debashis9012** [comment]
This has been verified and found fixed with the version: ```gauge-0.0.11.nightly-2019-05-16```
