### ISSUE TITLE
VSCode Debug option not working with Gauge's Java project

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-vscode#368]
Expected
Execution should pause at breakpoint in VSCode for Java project

Actual
Execution does not pause in VSCode for Java project

Steps to Reproduce
1. We are using VSCode extension Microsoft's Java Extension Pack (vscjava.vscode-java-pack)
2. I can see Debug option in spec file but execution does not stop.
3. With regular Java program (Without Gauge) in VSCode, my debug works perfectly fine.
3. I am on Windows 10

Version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.7.2)
screenshot (0.0.1)

**Comment by zabil** [comment]
> Execution does not pause in VSCode for Java project

Do you mean it does not stop at a breakpoint set on Java step implementation file?

**Comment by manavghaigithub** [comment]
Yes it does not stop at a breakpoint in implementation file

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manavghaigithub** [comment]
Just to add i am on below versions
VS Code – 1.27.2
Gauge – 0.0.7

**Comment by Debashis9012** [comment]
@manavghaigithub  I have tried to reproduce debug feature is working as excepted. Kindly find the below versions.
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
java (0.7.2)
```
``` vs code version:  1.33.1```
``` os: windows 10```

could you please tell us which gauge-vscode  version you are using?

**Comment by manavghaigithub** [comment]
VS Code – 1.27.2
Gauge – 0.0.7

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Debashis9012** [comment]
@manavghaigithub Java debug support feature in vs code available from ``` gauge-vscode 0.0.8 ``` version. I would suggest you to upgrade gauge-vscode to latest release version and please let us know weather its working for you. You can download the release version from: [Release version](https://github.com/getgauge/gauge-vscode/releases/tag/v0.0.9).

**Comment by NivedhaSenthil** [comment]
Closing this. Please feel free to reopen if it is not working in the latest version.

**Comment by raghav27** [comment]
**Debug spec/scenario option and step definition navigation is not working with gauge-vscode 0.0.15 version.**

- Environment information:
- Operating System: Windows 10 64bit
- JDK version: 11 
- Visual Studio Code version: 1.48.2
- Gauge version: 1.1.2
- Java extension pack: 0.10.0
- Java Debugger extension version: 0.28.0
- Gauge extension (gauge-vscode) : 0.0.15
- Maven for Java : 0.24.2

Debug option is working till gauge-vscode 0.0.8 version (as mentioned in https://github.com/getgauge/gauge-vscode/issues/368). 
After 0.0.8, no version is supporting debug feature for java-maven based project in VSCode.
