### ISSUE TITLE
Add a command palette to report issues or give feedback

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#37]
Add the command "Report Issues" in VS code's command palette to link quickly create a Github issue.

This can be used to capture feedback and report bugs.
This must capture gauge cli and gauge plugin version.

For reference check "Report Issues" command for VS code.

**Comment by BugDiver** [comment]
should be available in gauge-vscode nightly >= 15-11-2017

**Comment by sguptatw** [comment]
The gauge cli and plugin versions are not captured when I click "Report Issue"

**Comment by BugDiver** [comment]
Fix should be available in gauge-vscode nightly >= 16-11-2017
