### ISSUE TITLE
markdown preview

### ISSUE THREAD

**Issue by mfulton26** [getgauge/gauge-vscode#370]
I think it would be awesome to show the side-by-side markdown preview with .spec and .cpt files (similar to how normal .md files can be previewed in VSCode).

**Comment by zabil** [comment]
There were some issues building this feature because VS Code's default markdown handler prevents the Gauge plugin from loading affecting other features like auto complete and code lens. But that was a while ago. Maybe somethings change is how VS Code handles extension in the later releases.

**Comment by zabil** [comment]
Closing this as the VS Code Gauge plugin will not be using the native markdown editor.
