### ISSUE TITLE
Unable to use a python virtual environment

### ISSUE THREAD

**Issue by DonJayamanne** [getgauge/gauge-vscode#371]
### Expected behavior
* Language Server and Test explorer should work.
* Should work with a virtual environment.
* Python users should not be expected to use global python installation (in fact it might not even be in the current path).

### Actual behavior
* For some reason running tests does not work on my global install of python.
* When running tests manually using `gauge run` it works within a virtual environment.
* Looks like there's no way to tell the extension to use my virtual environment instead of using a global install fo python.

### Steps to reproduce
1. Create virtual environment
2. Acrtivate virtual environment
3. Install getgauge, etc into this environment
4. Initialize a python project in here using gauge
5. Open VS Code
6. Testing and LS fail

There's no way to tell the extension to use a specific python environment.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
python (0.3.5)
screenshot (0.0.1)

### Screenshots of failures
<img width="1042" alt="Screen Shot 2019-05-01 at 10 21 07 AM" src="https://user-images.githubusercontent.com/1948812/57030973-357f2880-6bfb-11e9-8d23-b7424c788cf7.png">

<img width="1062" alt="Screen Shot 2019-05-01 at 10 25 21 AM" src="https://user-images.githubusercontent.com/1948812/57031060-7119f280-6bfb-11e9-8cce-9fe04e8d2362.png">

### Work when run manually in terminal

<img width="1015" alt="Screen Shot 2019-05-01 at 10 27 08 AM" src="https://user-images.githubusercontent.com/1948812/57031152-c0602300-6bfb-11e9-9242-011c1306db10.png">

**Comment by nehashri** [comment]
@DonJayamanne This seems to work fine for me.
I am also working on mac and using the same version of Gauge and its plugins. I am not sure why it isn't working for you. Can you provide more details on which version of python you are using globally and in virtualenv. 

Also, you can always specify the python version to used using `GAUGE_PYTHON_COMMAND` environment variable. You can try providing a path too, and see if it works.

The segmentation violation exception seems weird. Can you let us know when this happens? (on opening a new project or after running the tests?)

It will also be helpful if you can share the log files associated with Gauge (the logs folder in you project).

**Comment by sardok** [comment]
This issue is valid for me too. I think after upgrading vscode it got broken. I'm not sure about that however. Tried to uninstall & re-install the plugin.

The issue is even though im using python3.7 in my virtual environment, it keeps selecting python2.7 (which is not my default python interpreter either) when running specs from vscode itself.

Here is tail of `logs/lsp.log`.
```
14:38:22.768 Initializing steps cache with 5 steps
14:38:22.769 Starting language runner
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
14:38:25.198 Python: 2.7.10
14:38:25.202 Failed to parse /Users/sinx/dev/end-to-end-tests/step_impl/mother_api/user.py:7 ':'
14:38:25.204 Failed to parse /Users/sinx/dev/end-to-end-tests/step_impl/mother_api/authorization.py:7 ':'
14:38:25.205 Failed to parse /Users/sinx/dev/end-to-end-tests/step_impl/mother_api/authenticate.py:7 ':'
14:38:25.222 Listening on port:53128
14:38:25.223 LangServer: reading on stdin, writing on stdout
```

My dev environment is macOS 10.16.4.

Also because python2.7 fails to parse existing python files, the editor shows missing steps in spec file.

P.s.: my python interpreter in vscode is properly pointing to the interpreter in my virtual env dir.

**Comment by mikeblakeney** [comment]
Just getting started exploring gauge, but I was able to work around this in VSCode by just pip installing gauge via the commandline while in the venv.  This enabled me to run reports:

`pip install getgauge==0.3.9`
