### ISSUE TITLE
command 'gauge.createProject' not found

### ISSUE THREAD

**Issue by febythomas** [getgauge/gauge-vscode#374]
How to solve this error? Installed the plugin but getting this error..

I did gauge init js and then opened the gauge test folder in VSCode

**Comment by negiDharmendra** [comment]
Please provide a few more details in order to investigate this issue.
 - Run `gauge -v` on your terminal and share the output with us.
 - **Gauge-vscode** extension version
 - **vscode** version
 - nodejs version
 - Which os you are working on

**Comment by febythomas** [comment]
C:\>gauge -v
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
js (2.3.4)
screenshot (0.0.1)

![image](https://user-images.githubusercontent.com/7920055/57288572-57831a00-70d7-11e9-818f-de188ff0fb9e.png)

vscode version: 
![image](https://user-images.githubusercontent.com/7920055/57288607-6c5fad80-70d7-11e9-8f29-409ba55606fa.png)

C:\>npm -v
6.9.0

OS: Windows 10

**Comment by febythomas** [comment]
Hi I tried using the nightly build 0.0.10 from https://bintray.com/gauge/gauge-vscode  and it seems to be working now.

**Comment by febythomas** [comment]
So basically 0.0.9 is not working

**Comment by negiDharmendra** [comment]
It works fine for me. It would be a great help if you could share the logs with us. 
You can find the same in `<gauge_project_root>/logs`

**Comment by febythomas** [comment]
Attaching logs here


Regards,
Feby Thomas

**Comment by negiDharmendra** [comment]
@febythomas Please share the logs.

**Comment by nehashri** [comment]
@febythomas Since this is working with 0.0.10 nightly, this bug will be fixed with the next release that is done.
