### ISSUE TITLE
Report issue redirects to new github issue with incorrect formatting.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#376]
**Steps to Reproduce**
* Open VSCode 
* In command palette choose `Gauge: Report Issue`
* github new issue page is opened with content that is not formatted, as shown below
```
```VS-Code version: 1.33.1Gauge Extension Version: 0.0.10Gauge version: 1.0.5Commit Hash: 562f036Plugins-------html-report (4.0.8)js (2.3.4)screenshot (0.0.1)```
```

**Expected Behaviour**
The new issue should be created with proper formatting.

Gauge VSCode extenstion version : 0.0.10

**Comment by Debashis9012** [comment]
This issue has been verified. Gauge: Report Issue provides proper format.
Tested version: ``` gauge-0.0.10.nightly-2019-05-13```
