### ISSUE TITLE
No debug links in any specs which blocks debugging

### ISSUE THREAD

**Issue by yinzhenzhixin** [getgauge/gauge-vscode#384]
[Expected Result]
There should be debug spec and debug scenario links just beside the run spec and run scenario link in any specifications

[Actual Result]
There is no debug spec or debug scenario in any specifications

[Steps]
I recently set up my gauge environment with VSCode in Windows 10. I installed the csharp plugin and init the sample project.
In the project, I can click on the run spec link or the run scenario link to trigger the testing, however there is no links to let me debug the tests, for any projects I created.
<img width="496" alt="Capture" src="https://user-images.githubusercontent.com/23313797/59753904-ae276a80-92b7-11e9-8c29-16d53dd3439f.PNG">

Version
Gauge version: 1.0.6.nightly-2019-05-31
VS Code Extension veresion: gauge-0.0.11.nightly-2019-06-04

**Comment by nehashri** [comment]
@yinzhenzhixin The csharp plugin is not supported in VSCode. If you want to run your tests with .Net Core, I suggest you use the [`dotnet` plugin](https://github.com/getgauge/gauge-dotnet).
If you want to work with CSharp, I suggest you try [Visual Studio](https://visualstudio.microsoft.com/) with [Gauge plugin for Visual Studio](https://github.com/getgauge/gauge-visualstudio/) instead. We support only Visual Studio 2015 and 2017 right now.

**Comment by yinzhenzhixin** [comment]
@nehashri thanks for your rapid response. BTW, is there any plan to add the debug feature for csharp in vscode? Seems the vs2017 plugin is not quite stable somehow, sometimes the debug doesn't work, sometimes the tests were missed from test explorer once you ran the tests...

**Comment by nehashri** [comment]
@yinzhenzhixin No, there isn't any plans to add it anymore. Not since, .Net Framework is set to go away.
There were a few fixes done for VS 2017 plugin. It should be working now. If you are still facing issues, please raise a issue, we will fix them soon.
