### ISSUE TITLE
.classpath is restored when a folder is loaded in VSCODE with gauge java

### ISSUE THREAD

**Issue by theothermountain** [getgauge/gauge-vscode#385]
%60%60%60%0AVS-Code%20version%3A%201.35.1%0AGauge%20Extension%20Version%3A%200.0.10%0A%0AGauge%20version%3A%201.0.5%0ACommit%20Hash%3A%20562f036%0A%0APlugins%0A-------%0Ahtml-report%20%284.0.8%29%0Ajava%20%280.7.2%29%0Ascreenshot%20%280.0.1%29%0A%60%60%60

It looks like the above text is auto generated, so I'll leave it there.
I am using gauge java in VSCODE. VSCODE version 1.35.1, gauge version shows: 
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)

gauge extension version 0.0.10.

My initial problem is that code complains Java libraries/classes can't be found, even though the jar files for them are in CLASSPATH. So looks like CLASSPATH is not honored.

So I copied jar files to $PROJECT_FOLDER\libs(does not work in other places), and added an entry(classpathentry) for each jar file in .classpath, and then the editor looks OK, showing green on all java files.

Then the new problem is that when the folder is loaded in VSCODE, file .classpath is restored, so my entries are gone, and I have to add them back again.

I've read the issue list but looks like this is not covered. Did I miss something? Or is there a workaround for this? 
Thank you very much!

**Comment by nehashri** [comment]
@theothermountain This seems to be an issue. Thanks for pointing it out, we will try to fix this soon.

**Comment by theothermountain** [comment]
Not sure if I can vote for this issue for it to be addressed soon.
It looks like this is same as in #279 , just there is no detailed information in 279. This issue is on Windows also.
Is there an estimated time of fix?

**Comment by zabil** [comment]
There is no estimated time for this fix yet and there are a lot of things in the backlog that needs immediate attention.

As a workaround can you try using maven or gradle for managing the dependencies and avoid editing the `.classpath` file manually?

**Comment by sriv** [comment]
@theothermountain is this still an issue? Later version of gauge-vscode+gauge-java seem to be handling `.classpath` fine for me.

**Comment by zabil** [comment]
Closing this for now will open if it is still an issue.

**Comment by theothermountain** [comment]
Sorry I missed this notification. 
The issue is still there.
Before I open VSCODDE, I have .classpath as:
<?xml version="1.0" encoding="UTF-8"?>



<classpath>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
  <classpathentry kind="src" path="src/test/java"/>
  <classpathentry kind="output" path="gauge_bin"/>
  <classpathentry kind="lib" path="libs\gauge-java-0.7.3.jar"/>
  <classpathentry kind="lib" path="libs\assertj-core-3.14.0.jar"/>
  <classpathentry kind="lib" path="libs\slf4j-api-1.7.29.jar"/>
  <classpathentry kind="lib" path="libs\IBMiCommon-0.2.jar"/>
  <classpathentry kind="lib" path="libs\IBMiTest-0.2.jar"/>    
  <classpathentry kind="lib" path="libs\IBMiPowerHA-0.2.jar"/>    
</classpath>

After I open VSCODE, it became:
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11"/>
  <classpathentry kind="src" path="src/test/java"/>
  <classpathentry kind="output" path="gauge_bin"/>
  <classpathentry kind="lib" path="C:\Users\shengli.li\AppData\Roaming\Gauge\plugins\java\0.7.9\libs\assertj-core-3.16.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\shengli.li\AppData\Roaming\Gauge\plugins\java\0.7.9\libs\gauge-java-0.7.9.jar"/>
</classpath>

I have VSCODE 1.49.0, and gauge 
D:\>gauge -v
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.9)
screenshot (0.0.1)

**Comment by BugDiver** [comment]
@theothermountain I could replicate this issue. We will try to fix it soon.
