### ISSUE TITLE
Allow users to open html-report post run

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-vscode#39]
After a gauge run, allow the users to open the html-report.

- This option should be available only if user has html-report plugin installed
- If [`overwrite_reports`](https://docs.getgauge.io/configuration.html#default-properties-9) = `false` then the report for the last run must be opened.

#### Options:

- Open report in the user's default browser
  - add a button in the output pane similar to the `Add Configuration...` button in the `launch.json`
  - add a link with a `command-uri` associated with a command that will open the report

> This will require use of a node module (ex. node-open).

- Open report in the `preview` pane.

> This may require a DocumentContentProvider and a DocumentLinkProvider.

**Comment by Apoorva-GA** [comment]
Should be addressed as part of https://github.com/getgauge/gauge-vscode/issues/354 and https://github.com/getgauge/gauge-vscode/issues/362
