### ISSUE TITLE
Fix VSCode tests in GoCD

### ISSUE THREAD

**Issue by luciferankon** [getgauge/gauge-vscode#391]

**Comment by luciferankon** [comment]
This issue is regarding vs code version. Since the vs code version is upgraded to 1.36+ the tests started to fail. In local windows, it passes. But when I log into the container and try to run the tests using vs code 1.36+ it fails. If I downgrade the version to 1.35.1 it works fine.

**Comment by shubhamsc** [comment]
Seems like the latest version of vscode has some issue running inside dokcer. Have raised an issue for the same https://github.com/microsoft/vscode/issues/77499.
For now, downgrading the vscode engine to 1.35.1.
