### ISSUE TITLE
Initialising the sample project is taking longer time.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-vscode#392]
Gauge sample project initialisation doesn't complete on windows.

### Steps
- Install gauge-vscode extenstion
- Select `Create a new Gauge Project` command
- Select the language
- Select the folder to create the project in

Notice that the project creation takes a very long time.

**Comment by BugDiver** [comment]
I'm not able to replicate this issue.
I tried it on a Windows VM and a native Windows machine as well.
Tried removing everything and follow the instruction from the latest getting started page (from invision app).

**Comment by zabil** [comment]
Can you try initialising a Java project?

**Comment by Apoorva-GA** [comment]
Initialising a java project also works fine. So closing this for now.
