### ISSUE TITLE
Should not show `The Gauge server crashed 5 times in the last 3 minutes` error.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-vscode#394]
### Steps
- Install Gauge `1.0.5`
- Install gauge-js  `2.3.6.nightly-2019-07-22`
- Init a js project 
- Open in vscode

`The Gauge server crashed 5 times in the last 3 minutes. The server will not be restarted.` error is shown.

In the above scenario gauge shouldn't crash but show that right message conveying Gauge and Gauge-js versions are not compatible

**Comment by NivedhaSenthil** [comment]
Fix available in gauge nightly >= 24/07/2019

**Comment by Debashis9012** [comment]
This issue issue has been verified and found fixed. 
Tested environment: ``` Gauge version: 1.0.6.nightly-2019-08-01```
