### ISSUE TITLE
vs-code debug process behaves differently in both windows and mac os

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-vscode#395]
action   performed | Expected result(console o/p) | Actual result(console o/p):   win | Actual result(console o/p):   mac | Runner | Versions
-- | -- | -- | -- | -- | --
On   debug break point hit "discontinue" | as the debug process   discontinued from user then the correct message should be "Run stopped   by user" in both the os. | "Run stopped by user"   without any stats | "Success: Tests   passed." without any stats | java | gauge nightly + release version   (Gauge version: 1.0.6.nightly-2019-07-19     Commit Hash: c215a9f + java (0.7.2)+ vs-code release version)
On   debug break point hit "continue" | After debug continue process   stats result should be in console ouput. | There is no statistics in   console output | There is no statistics in   console output | java | gauge nightly + release version   (Gauge version: 1.0.6.nightly-2019-07-19     Commit Hash: c215a9f + java (0.7.2)+ vs-code release version)
On debug   break point hit "discontinue" | If user disconnect the debug   process then stats should not get generated. | stastics available | no stats available | python | gauge nightly + release version   + vs-code release version

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
