### ISSUE TITLE
Whenever I open my tests folder my autosave setting is changed to afterdelay

### ISSUE THREAD

**Issue by joacimaj** [getgauge/gauge-vscode#398]
This requires me to fix my setting every time as I'm using vsode for many repos, which have adverse effects of autosaving.

**Comment by Apoorva-GA** [comment]
@joacimaj What version of Gauge-VScode plugin are you using?

If the Gauge recommended settings (`"files.autoSave": "afterDelay"`,
`"files.autoSaveDelay": 500`) are not set Gauge gives you option to Apply it, ignore it for now and to permanently ignore it.

Popup looks something like this

<img width="533" alt="Screenshot 2019-08-30 at 2 37 46 PM" src="https://user-images.githubusercontent.com/8462534/64008456-c9beb500-cb33-11e9-8c78-73686a4b0325.png">

If you choose `Ignore`. You won't see the popup again.

**Comment by joacimaj** [comment]
I do not get this message, even after uninstalling and reinstalling gauge. 
Yet whenever I open my tests folder it changes the settings, and it changes the settings on reinstall of Gauge.

**Comment by negiDharmendra** [comment]
@joacimaj Installing and uninstalling Gauge does not affect `autoSave` settings. It is Gauge VS Code extension which adds `autoSave` settings depending on the option ( one of the `Apply & Reload`, `Remind me later` or `Ignore`) user would have selected after first installation of Gauge VS code extension.

If you don't want Gauge VS Code extension to change these settings then you should set `gauge.recommendedSettings.options` value to `Ignore` in users settings.

**Comment by Debashis9012** [comment]
This issue has been validated and found fixed. 
Tested version:
```
 Gauge version: 1.0.6
 Commit Hash: 2bc49db

vs code: 41f883ad16cf14e6ffdac83ccf43b1c85b95881f

```
