### ISSUE TITLE
Step implementation not found for step

### ISSUE THREAD

**Issue by andresgaragiola** [getgauge/gauge-vscode#400]
The plugin is not able to find steps implementations in a jar file.

### Expected behavior
The step should be found since it is in a jar file and the spec can be run.

### Actual behavior
Steps are highlighted in red, but I can run the spec or the scenario.

### Steps to reproduce
1. Create a gauge project for java
2. Put the steps implementations in a jar file inside the _libs_ folder.
3. Set the "gauge_additional_libs" to "libs/*"
4. Implement a spec using the steps in the jar

### Version Information

VisualStudio Version and Edition  : 1.38.0
Gauge VisualStudio Plugin Version : 0.0.10

**Comment by nehashri** [comment]
@andresgaragiola This seems to be a bug. The issue https://github.com/getgauge/gauge-java/issues/236 explains the issue in detail. Please track https://github.com/getgauge/gauge-java/issues/236 for updates and fixes for this issue.

**Comment by zabil** [comment]
This should be fixed via https://github.com/getgauge/gauge-java/issues/236 in the latest releases.
