### ISSUE TITLE
Installation Issue: No Commands or Peek Definition on Mac

### ISSUE THREAD

**Issue by paddydeklee** [getgauge/gauge-vscode#402]
I think this is an installation issue:

**Issues**

1. Gauge plugin is working nicely on my windows machine. I have pulled the _same code_ onto my mac, and only two of the Gauge: command pallet commands are available. 
2. The _Peek_ / _Go to definition_ helpers are also not available - I assume these issues are related to each other.

See the images below of my mac VS Code interface:

Image 1
<img width="1322" alt="Screenshot 2019-09-11 at 18 25 55" src="https://user-images.githubusercontent.com/16546936/64720129-9f6ce000-d4c1-11e9-927e-86b0fffdefd9.png">

Image 2
<img width="1318" alt="Screenshot 2019-09-11 at 18 13 18" src="https://user-images.githubusercontent.com/16546936/64719466-35a00680-d4c0-11e9-8fc2-6e5d182662bb.png">

At this point, I have installed the latest gauge plugin using the following methods:

1. via cmd line: `npm i -g @getgauge/cli `
2. using the VS Code **install** button
3. removing the extension via cmd line  `rm -rf getgauge.gauge-0.0.10` and re-trying the installs

When I enter the project, and after installing gauge cli, VS code displays a note in the bottom corner saying: 

> X Gauge executable not found! Click here for install instructions.

Also, Gauge runs fine when I do `gauge run specs` so I think it is to do with the gauge VS code plugin.
Any help with this would be greatly appreciated!

**Comment by nehashri** [comment]
@paddydeklee This is likely to be an issue with gauge not being available in the PATH. The gauge executable is available in your path from the command line but not for VSCode. Can you try opening the project from the command line using VSCode's `code` command and see if it works? Refer https://code.visualstudio.com/docs/editor/command-line

**Comment by nehashri** [comment]
@paddydeklee Can you please provide the Gauge version details (run `gauge -v` command and paste its contents here). 
How was Gauge installed in your machine? Please specify the commands used.
Also, can you try adding the gauge executable folder to your PATH explicitly and try once?

**Comment by paddydeklee** [comment]
**Gauge Version:**
➜ furlong-test git:(master) gauge -v  
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
spectacle (0.1.3)

**Gauge Installation**
Installed using npm:
```
npm install -g npm@latest
npm install -g @getgauge/cli
```

**Adding to Path Explicitly**
Added gauge usr/local/bin/gauge to $PATH explicitly.
<img width="685" alt="Screenshot 2019-09-13 at 15 16 26" src="https://user-images.githubusercontent.com/16546936/64869863-1f1dba80-d63a-11e9-9106-a5129ad34ed1.png">

**Try Opening Project from cmd line**
<img width="1680" alt="Screenshot 2019-09-13 at 15 22 48" src="https://user-images.githubusercontent.com/16546936/64869985-6015cf00-d63a-11e9-82af-f0e139c137a5.png">

AND IT WORKS!!! Well, gauge plugin functions references and go to definition functions work.

<img width="709" alt="Screenshot 2019-09-13 at 15 25 45" src="https://user-images.githubusercontent.com/16546936/64870421-298c8400-d63b-11e9-818f-3a7237d47cc6.png">

Thank you!

One thing that doesn't work - the peek functionality, where I click on a reference and it opens up with GitLens - like this :

<img width="761" alt="Screenshot 2019-09-13 at 15 27 48" src="https://user-images.githubusercontent.com/16546936/64870381-12e62d00-d63b-11e9-960e-2f9c277846dd.png">

- do you know how I can get that working?

**Comment by shubhamsc** [comment]
@paddydeklee  I can see peek definition for the step is not working with gauge-js in vscode. For other runners, it's working fine. We'll look into it soon.
Thanks for reporting this issue.

**Comment by zabil** [comment]
Peek definition now seems to work on Mac with the following versions

```
gauge --version                                          
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
js (2.3.7)
```

@paddydeklee can you check this. Closing it for now but please feel free to open it if it's still a problem.
