### ISSUE TITLE
Unable to create gauge project with csharp 

### ISSUE THREAD

**Issue by ravi-gooty-gpau** [getgauge/gauge-vscode#404]
Hi,

I have the following VS Code version : 1.37.1

And I have installed the Gauge VS Code plugin version: 0.0.10

Post installation, I am unable to create a Gauge project using csharp as the language, is this a version compatibility issue or am I missing something ?

TIA

**Comment by shubhamsc** [comment]
@ravi-gooty-gpau gauge-vscode plugin doesn't have complete support for CSharp. However, you can create a CSharp project from the command line by using `gauge init csharp`, but you can't get all features in VScode.

`Gauge-CSharp` runner is deprecated in respect to `Gauge-Dotnet`, Which works well with VScode.
Currently, there is no template for Dotnet aswell. you can use the command `gauge init dotnet` to create a Dotnet project.
I created an [issue](https://github.com/getgauge/gauge-vscode/issues/405) to add a template for Dotnet in VScode.

**Comment by Apoorva-GA** [comment]
Please track [issue](https://github.com/getgauge/gauge-vscode/issues/405). Closing this.
