### ISSUE TITLE
Python 'Go to Definition' is not working

### ISSUE THREAD

**Issue by vmatyusGitHub** [getgauge/gauge-vscode#406]
I created a basic gauge python with the built-in `Gauge: Create a new Gauge Project`, but the gauge 'Goto Definition' functionality is not working even in the generated project.
I am receiving the following error notification:
`Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected`

I am working on MacOS Mojave 10.14.6
Gauge plugin version: 0.0.10
VSCode version: 1.37.1

**Comment by Apoorva-GA** [comment]
Could you please run `gauge -v` and paste the result here?

**Comment by vmatyusGitHub** [comment]
```gauge -v
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
python (0.3.5)
screenshot (0.0.1)```

**Comment by Apoorva-GA** [comment]
@vmatyusGitHub Thats wired..! I am on the exact same version and things work seamlessly for me.
One more thing I can think of is : 
Could you run `pip/pip3 show getgauge` and paste the results?

**Comment by vmatyusGitHub** [comment]
```
Name: getgauge
Version: 0.3.5
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: protobuf, ptvsd, six, parso, grpcio, redBaron
Required-by: 
```

**Comment by vmatyusGitHub** [comment]
Even the autocorrect not offering `Create step implementation`

**Comment by vmatyusGitHub** [comment]
I installed python3 with brew. And I found an lsp.log file that contains the following logs:
```
01-10-2019 09:20:13.337 [Gauge] [INFO] Watching directory: /Users/my-name/Documents/gauge-test-py/specs
01-10-2019 09:20:13.338 [Gauge] [DEBUG] Found 1 files
01-10-2019 09:20:13.338 [Gauge] [INFO] Initializing concepts cache with 0 concepts
01-10-2019 09:20:13.338 [Gauge] [INFO] Initializing specs cache with 1 specs
01-10-2019 09:20:13.338 [Gauge] [DEBUG] Adding specs from /Users/my-name/Documents/gauge-test-py/specs/example.spec
01-10-2019 09:20:13.338 [Gauge] [INFO] Initializing steps cache with 1 steps
01-10-2019 09:20:13.339 [Gauge] [INFO] Starting language runner
/usr/bin/python: No module named pip
Traceback (most recent call last):
File "start.py", line 6, in <module>
from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
01-10-2019 09:20:43.342 [Gauge] [DEBUG] Unable to connect to runner : Timed out connecting to python
Some of the gauge lsp feature will not work as expected.
01-10-2019 09:20:43.342 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
01-10-2019 09:20:43.347 [Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP
```

**Comment by Apoorva-GA** [comment]
The log shows that `No module named pip`.
You need to install pip and ensure that getgauge is installed. You can check that using `pip/pip3 show getgauge`.

**Comment by Apoorva-GA** [comment]
Also If you are using `python3` then  change `GAUGE_PYTHON_COMMAND = python3` in  `python.properties` file.

**Comment by vmatyusGitHub** [comment]
This setting was missing! I added `GAUGE_PYTHON_COMMAND = python3` to `python.properties` file. Now it works! Thank you for the help!
