### ISSUE TITLE
Executing the previous run from command palette

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#41]
**Proposed behavior**
User should be able to repeat the last run
- [ ] "Repeat Last Run" will repeat the last run
- [ ] "Run Scenarios" will list all scenarios for current open spec. It will warn if the current document is not a specification.

**Behavior to be retained**
- [ ] "Run Specification" - run currently open specification
- [ ] "Run Scenario" if the cursor is outside all scenarios - show the list of scenarios for selection.

**Comment by BugDiver** [comment]
should be available with following in nightlies
* Gauge : >= 20-11-2017
* Gauge-VSCode : >= 20-11-2017

**Comment by sguptatw** [comment]
How do I stop an an ongoing execution from the IDE?

**Comment by sguptatw** [comment]
There should be an ability to stop ongoing executions in the IDE - 
https://github.com/getgauge/gauge-vscode/issues/56
