### ISSUE TITLE
Step implementation not found in referenced .Net Framework project

### ISSUE THREAD

**Issue by jenniferz79** [getgauge/gauge-vscode#411]
Steps to reproduce
----------------------
* Create a VS solution with 2 .Net Framework projects: project1 and project2
* project1 has the specs
* project2 has the steps
* When use Visual Studio 2017, it works fine, steps implementation can be found by F12.
* When use Visual Studio Code to open the same solution, in the spec file, the steps implementation can NOT be found. Although the spec can still be run by click 'Run spec'/'Run scenario'

Expect behavior
-------------------
Steps implementation should be found if it is in referenced c# .Net Core/Framework project. The behavior should be the same as using Visual Studio 2017.

**Comment by shubhamsc** [comment]
gauge-csharp is not fully supported with vscode and it's deprecated as well, Use [gauge-dontnet](https://github.com/getgauge/gauge-dotnet) plugin instead. Please see the [deprecation notice](https://github.com/getgauge/gauge-csharp#deprecation-notice).
