### ISSUE TITLE
Report an issue redirects to new github issue with incorrect formatting.

### ISSUE THREAD

**Issue by ngbrown** [getgauge/gauge-vscode#413]
This was previously reported (and fixed?) in #376, but it seems to have come back.

When clicking the "Open" button in Visual Studio, the resulting URL seems to be double encoded, however, the `Copy` option, then pasting works (and is the start of this issue).

![Screenshot - 2020-01-08_12-00-09](https://user-images.githubusercontent.com/228987/72007229-77db1980-320e-11ea-8347-9614d77d7698.png)

The URL in Chrome is:

```
https://github.com/getgauge/gauge-vscode/issues/new?body=%2560%2560%2560%250AVS-Code%2520version%253A%25201.41.1%250AGauge%2520Extension%2520Version%253A%25200.0.11%250A%250AGauge%2520version%253A%25201.0.6%250ACommit%2520Hash%253A%25202bc49db%250A%250APlugins%250A-------%250Acsharp%2520%25280.10.6%2529%250Adotnet%2520%25280.1.2%2529%250Ahtml-report%2520%25284.0.8%2529%250Ajs%2520%25282.3.7%2529%250Apython%2520%25280.3.7%2529%250Ascreenshot%2520%25280.0.1%2529%250Aspectacle%2520%25280.1.3%2529%250Axml-report%2520%25280.2.2%2529%250A%2560%2560%2560
```

The resulting GitHub request:
![Screenshot - 2020-01-08_12-00-43](https://user-images.githubusercontent.com/228987/72007262-8d504380-320e-11ea-92ab-037c3f0b5f06.png)

```
VS-Code version: 1.41.1
Gauge Extension Version: 0.0.11

Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
csharp (0.10.6)
dotnet (0.1.2)
html-report (4.0.8)
js (2.3.7)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)
```

**Comment by negiDharmendra** [comment]
@ngbrown Thanks for reporting this issue. We will update you once it is fixed.
