### ISSUE TITLE
Current gauge language runner is not compatible with gauge LSP. 

### ISSUE THREAD

**Issue by ksail** [getgauge/gauge-vscode#419]
I see this Error in VScode and some stepimplementation and editing features do not work. 
**Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected**

Here is the gauge version information:
gauge version
Gauge version: 1.0.6
Commit Hash: 2bc49db
Plugins
-------
html-report (4.0.9)
js (2.3.8)
screenshot (0.0.1)

Js.properties:
#js.properties
test_timeout = 20000
DEBUG = false
STEP_IMPL_DIR = tests

**Comment by ksail** [comment]
Installing latest version of gauge globally fixed this issue.

> npm install -g @getgauge/cli

- updated gauge to 1.0.7 and this fixed the problem.

Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
js (2.3.8)
screenshot (0.0.1)

**Comment by Noob7** [comment]
installed the latest version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.8)
js (2.3.11)
screenshot (0.0.1)
xml-report (0.2.2)

still getting it
