### ISSUE TITLE
Cannot create a Gauge project after installing Gauge plugin on VS Code

### ISSUE THREAD

**Issue by levietquynh** [getgauge/gauge-vscode#420]
I installed gauge on Mac version 10.14.6 with command: 'brew install gauge' to get gauge version 1.0.7. After that, I install VS Code then install Gauge plugin version 0.0.11. 
Then I try to create a Gauge project but I always receive notification as "command 'gauge.createProject' not found".

I also tried to run code from my team member, but when I open file .spec, I cannot see option 'Run Scenario'.
I tried to uninstall VS Code and Gauge many times, restart machine, but it didn't work.

**Comment by zabil** [comment]
Can you try creating the project in VS code after installing a gauge plugin from the command line.
For example.
```
gauge install js
```

For details, please refer https://github.com/getgauge/gauge-vscode/issues/417#issuecomment-586908729

**Comment by levietquynh** [comment]
Thanks so much, I tried and it works well now.
