### ISSUE TITLE
Error while running specification from VSCode

### ISSUE THREAD

**Issue by prakashautade** [getgauge/gauge-vscode#428]
I am trying to execute tests specification from VSCode but getting below error.

> Running tool: ./gradlew.bat clean gauge -PadditionalFlags=--hide-suggestion --simple-console -PspecsDir=specs\myTest.spec
'.' is not recognized as an internal or external command,
operable program or batch file.
Error: Tests failed.

**Gauge**:  
`gauge -v`
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
spectacle (0.1.3)

**VSCode**: 1.44.2 (user setup)
**OS**: Windows_NT x64 10.0.17763
**VSCode Gauge Plugin**: 0.0.13

**Comment by sriv** [comment]
what happens if you run the project via command line? If it runs, please paste the command that you use to run it via terminal.

**Comment by prakashautade** [comment]
I use below command to run gauge from CLI

# gradlew clean gauge -PspecsDir=specs\myTest.spec

**Comment by prakashautade** [comment]
Any update on this ?

**Comment by sriv** [comment]
@prakashautade  would you be able to build the plugin from master and check?

**Comment by sriv** [comment]
@prakashautade - are you still facing this issue? 

If you are not comfortable to build and run the plugin, that's fine - we'll send a link to a pre-release build.

**Comment by sriv** [comment]
closing this since there has been no response. Feel free to comment if this needs attention.
