### ISSUE TITLE
Support for Gauge version 1.0.8 in VSCode

### ISSUE THREAD

**Issue by AlexanderNZ** [getgauge/gauge-vscode#431]
I'm unable to get the Gauge plugin working with VSCode 1.45.1 and Gauge 1.0.8.

To reproduce:
Install VSCode 1.45.1
Install Gauge 1.0.8 via apt-get on Ubuntu 18.04
Install Gauge VSCode Plugin from Extensions tab
Create new Gauge Project via command palette

Expected behaviour:
Everything works out and a new project is created.

Actual Behaviour:
A new project is not created.
Recieve error messages that say:
`Error fetching Gauge and plugins version information. error: open /home/user/.gauge/plugins: no such file or directory { "version": "1.0.8", "commitHash": "28617ea", "plugins": [] }`
and
`Command 'Gauge: Create a new Gauge Project' resulted in an error (command 'gauge.createProject' not found)`

Cheers

Alex

**Comment by sriv** [comment]
thanks for reporting. Fix raised via https://github.com/getgauge/gauge/pull/1651
