### ISSUE TITLE
invalid error while build is failing

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge-vscode#439]
Hi,

When there is error in the project and reopen the vscode, gauge failed to show both code lenses or Debug code lense and also giving invaild error "Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected"

After fixing the issue and restarting vscode we can see the code lens.

Also is there any option to restart gauge without closing VSCode IDE?

IDE : VSCODE
language plugin: dotnet

PFA the screenshot.
![Error](https://user-images.githubusercontent.com/36397242/85282759-f15b8100-b4a9-11ea-9d60-bf128fbaab42.png)

**Comment by BugDiver** [comment]
@preetipadalia I'm guessing it's because when the gauge starts the runner it tries to build the project. In case of any error the runner would fail, to start hence the error. Ideally it should not happen, We will look into the issue soon.

**Comment by preetipadalia** [comment]
@BugDiver Yeah and along with that issue it is also giving wrong error message: "Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected" which is also misleading.

**Comment by preetipadalia** [comment]
Hi,

I can still see this issue in while there is an issue in code and build fail and vscode restarts getting invalid error:
unable to connect to runner : Error occurred while waiting for runner process to finish. Error : exit status 1

Thanks
Preeti

**Comment by sriv** [comment]
@preetipadalia what version of gauge+gauge-dotnet are you on?

**Comment by preetipadalia** [comment]
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
dotnet (0.1.6)

**Comment by sriv** [comment]
This should be fixed in #446 which is yet to be merged, reopening.
