### ISSUE TITLE
Gauge extention VS Code error

### ISSUE THREAD

**Issue by Noob7** [getgauge/gauge-vscode#440]
Getting this message in vs code:
Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected

Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.8)
js (2.3.11)
screenshot (0.0.1)
xml-report (0.2.2)

Have tried reinstalling both gauge and vs code and gauge extension

**Comment by sriv** [comment]
is there any errors/information printed in the logs? Please check `logs/gauge.log` and `logs/lsp.log` ?

**Comment by zabil** [comment]
I see this happening when there are compilation errors in the project. This may be application to other languages when there are compilation error

To replicate this for a java project

* Run `gauge init java`
* `code .` (to launch VS Code in the current project)
* Edit the `src/test/java/StepImplementation.java`
* Delete/comment the line `private HashSet<Character> vowels;`
* Reload the project
