### ISSUE TITLE
gauge-vscode v0.0.13 does not work with gauge-java v0.7.8 in Mac

### ISSUE THREAD

**Issue by jnlabs** [getgauge/gauge-vscode#442]
gauge-vscode v0.0.13 does not work with gauge-java v0.7.8

Mac: Catalina 10.15.5
VS Code version: 1.47.1

gauge-vscode version: 0.0.13

Gauge version: 1.1.1
Plugins
-------
html-report (4.0.12)
java (0.7.8)
js (2.3.12)
screenshot (0.0.1)
xml-report (0.2.3)

![image](https://user-images.githubusercontent.com/63402957/87547081-2a6bc780-c6dd-11ea-95ab-db6cf99a2ed4.png)
![image](https://user-images.githubusercontent.com/63402957/87547174-4b341d00-c6dd-11ea-8056-0e248c1ebc13.png)

**Comment by sriv** [comment]
Do you see anything in the logs? Ideally there should be some information either in `gauge.log` or `lsp.log`.

Also, what does `gauge version --machine-readable` say?

**Comment by jnlabs** [comment]
I see lsp.log generated. I believe gauge.log is generated during test execution but my issue is that the vscode plugin features is not working such as 'Goto Definition' and 'Format Specification'.

[lsp-clean.log](https://github.com/getgauge/gauge-vscode/files/4929206/lsp-clean.log)

gauge version --machine-readable
![image](https://user-images.githubusercontent.com/63402957/87624715-f505bf00-c75a-11ea-8838-720cb4e5102f.png)

**Comment by NivedhaSenthil** [comment]
@jnlabs can you please update the plugins to latest version and try again

**Comment by jnlabs** [comment]
Hi @NivedhaSenthil , i updated the plugin to version 0.0.14.
Format Specification works only with .spec file but doesn't work with .cpt
Goto Definition only works with steps defined in concept. Below error is displayed when trying to goto definition with non-concept steps.
![image](https://user-images.githubusercontent.com/63402957/88377734-47d21d00-cdd2-11ea-9410-9ec5957105eb.png)

**Comment by NivedhaSenthil** [comment]
Can you please ensure that gauge-java version is also updated? since there were few issue with the older version.
I could run a sample project fine with below versions.
```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.9)
screenshot (0.0.1)
```

**Comment by jnlabs** [comment]
Hi @NivedhaSenthil , thank you for your quick response. My project also running(test execution) just fine. The issue is vscode plugin unable to goto step definition and concept document format not working. Although we can still proceed but editing is difficult when these features are not working. 

FYI, I have step definitions in src/test/java and steps from compiled maven artifact.
Below is my gauge-java version both gauge plugin and gradle dependency.

```
Gauge version: 1.1.1
Plugins
-------
html-report (4.0.12)
java (0.7.9) --> (same version with gradle dependency)
js (2.3.12)
screenshot (0.0.1)
xml-report (0.2.3)
```
