### ISSUE TITLE
Should not generate stub for empty step text

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#45]
**Expected behavior**
If the step text is empty, copy implementation.. should not be displayed.

**Actual behavior**
```
step("", async function() {
	throw 'Unimplemented Step';
});
```

**Steps to replicate**
* Type * space and then (Ctrl+.). Copy the stub
* Paste it in js
> Observe the code getting generated for empty text

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-15
Commit Hash: 55fe281

Plugins
-------
js (2.0.3.nightly-2017-11-16)
```

**Comment by zabil** [comment]
This behavior is ok.
Can be used as a hack to generate placeholder stubs.
