### ISSUE TITLE
Unable to create new template Projects 

### ISSUE THREAD

**Issue by manasi-rk** [getgauge/gauge-vscode#451]
When I try to create a new Gauge Project from the template I get the following error message -

![image](https://user-images.githubusercontent.com/46588493/93220655-6f1de880-f78a-11ea-9b75-88cee0730f96.png)

Failed to get list of templates.

Am I missing something?

Steps followed as given in - 
https://docs.gauge.org/getting_started/create-test-project.html?os=windows&language=javascript&ide=vscode

Versions - 
Gauge VS Code plugin - 0.0.15
VS Code - 1.49.0
Gauge version - 1.1.1

**Comment by zabil** [comment]
Can you check this after upgrading to Gauge version 1.1.4

**Comment by manasi-rk** [comment]
I am getting the templates now after upgrading to 1.1.4.  Thanks Zabil!
