### ISSUE TITLE
Debug spec/scenario option is not displaying and step definition navigation is not working with latest extension (gauge-vscode 0.0.15 version)

### ISSUE THREAD

**Issue by raghav27** [getgauge/gauge-vscode#452]
**Environment information:**
Operating System: Windows 10 64bit
JDK version: 11
Visual Studio Code version: 1.48.2
Gauge version: 1.1.2
Java extension pack: 0.10.0
Java Debugger extension version: 0.28.0
Gauge extension (gauge-vscode) : 0.0.15
Maven for Java : 0.24.2

**Project** - Java with Maven

**Issues -** 
a. Debug spec/scenario option is not displaying with extension gauge-vscode 0.0.15 
We tried with older version and debug feature is working only till gauge-vscode 0.0.8 version.
(Info on 0.0.8 version is present in issue - https://github.com/getgauge/gauge-vscode/issues/368)

b. Step definition navigation - Navigation from spec file to respective .java file is not working with extension gauge-vscode 0.0.15. Again this feature is also working till gauge-vscode 0.0.8 verison.

Is there any specific reason, **Why both of these features are not working after gauge-vscode 0.0.8 version.**

**Comment by raghav27** [comment]
No updates on this issue. Can anyone pick this.

**Comment by raghav27** [comment]
@NivedhaSenthil

**Comment by gauravcb7** [comment]
@sriv @NivedhaSenthil @nehashri 
We are also facing the same issue, can you guys please look into this

**Comment by sriv** [comment]
@raghav27 :

> No updates on this issue. Can anyone pick this.

- you can always see our support backlog here: https://github.com/orgs/getgauge/projects/4.
- What is the output of `gauge -v`, and what are the versions of `gauge-java` and `gauge-maven-plugin` in your `pom.xml`?
- Did you inspect the logs (`gauge.log` and `lsp.log`) ? Do you see any error?
- Did you try updating gauge/gauge-java (you can run `gauge update -c`)

I am on :

```
Gauge version: 1.1.4
Commit Hash: c982558a

Plugins
-------
dotnet (0.1.7)
flash (0.0.2)
go (0.1.4)
html-report (4.0.12)
java (0.7.10)
js (2.3.12)
json-report (0.3.3)
python (0.3.10)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```
And gauge-vscode `0.0.15` and I cannot see either issues that you report. See below

![gauge_java_maven_vscode](https://user-images.githubusercontent.com/389148/93610127-4f84fb00-f9ea-11ea-9f1c-0e3d40fcf482.png)

![goto_defn](https://user-images.githubusercontent.com/389148/93610149-5449af00-f9ea-11ea-8a77-c04b419e4c8b.gif)

@gauravcb7 

> We are also facing the same issue, can you guys please look into this

Which one? there are two issues reported here. Neither are replicable for me, FWIW.

**Comment by raghav27** [comment]
Thanks Srikanth for the update. 

**Gauge plugins version** - 
Gauge version: 1.1.2

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
xml-report (0.2.2)

Let me try with Gauge 1.1.4 and plugin verison's as mentioned by you. Will share the updates by tomorrow EOD.
Thank you.

**Comment by NivedhaSenthil** [comment]
Any updates ? Does it work fine with the latest versions ?

**Comment by raghav27** [comment]
There are no updates as of now. As this is a new version on github, our security team is analyzing the exe & zip files and hoping to get some updates by today eod.

**Comment by zabil** [comment]
Closing for now. Will re-open after there is a response and if it's still an issue.

**Comment by raghav27** [comment]
Hi @sriv , @NivedhaSenthil , @zabil 
Tried with the latest version of Gauge and plugins but issue is still present. Debug spec/scenario option is not displaying with extension gauge-vscode 0.0.15
We tried with older version and debug feature is working only till gauge-vscode 0.0.8 version.

**Gauge plugins version -**
Gauge version: 1.1.4

Plugins
flash (0.0.1)
html-report (4.0.8)
java (0.7.11)
screenshot (0.0.1)
xml-report (0.2.2)

**Added dependency in pom.xml** - 
<dependency>
<groupId>com.thoughtworks.gauge</groupId>
<artifactId>gauge-java</artifactId>
<version>0.7.11</version>

Also, we are getting an error message in VsCode '**Gauge could not intialize. Install 'vscjava.vscode-java-pack' extension for code insights.**'

Request you to please re-open this ticket and let me know for additional information.

**Comment by zabil** [comment]
I am able to see the debug option option. 
However I do see a problem while trying to debug (which I am investigating)

<img width="1152" alt="Screenshot 2020-11-11 at 12 00 06" src="https://user-images.githubusercontent.com/54427/98809490-889f8180-2415-11eb-9364-e93ff1fd6ecf.png">

Please try the following, if you have the `code` command line installed.
Make sure the gauge vs code plugin and the java extension pack plugin is the latest version

```
gauge init java_maven
code . 
```

Please post screenshots of the error and snippets of the logs from the vscode logging console and well as the logs folder.

**Comment by idanlou** [comment]
Hi, I'm facing the same issues of no debug option and step definition navigation is not working.
Did you ever resolve it?
