### ISSUE TITLE
Gauge must work when there are multiple gauge projects in workspaces

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#46]
**Expected behavior**
When there are multiple workspaces, all the functionality must work.

## Acceptance criteria
**Goto definition**
- [x] Goto definition must take the user to the implementation within the workspace

**Find usages**
- [x] The usage count must be limited to the usages in the workspace. Unless explicitly referenced.

**Diagnostics**
- [x] Duplicate Step implementations must be limited to the workspace
- [x] Duplicate concept definition must be limited to the workspace

**Autocomplete**
Unless explicitly referenced, the list must be limited to elements in the workspace
- [x] Steps 
- [x] The tags 

**Execute**
- [x] Should be able to run specifications of the workspace

**Workspace**
- [ ] Multiple gauge projects with different language runners
- [x] A non-gauge project and a gauge project

**Comment by sguptatw** [comment]
How many gauge projects can be there in a single workspace?

**Comment by nehashri** [comment]
There is no limit to the number of gauge projects that can be added to a single workspace.

**Comment by sguptatw** [comment]
**Test case**
Duplicate step implementation should be limited to workspace

**Issue**
The same step text implemented in multiple gauge projects show `Duplicate step implementation`

**Expected behavior**
The errors should be limited to the project implementations

**Steps to replicate**
* Create project1 `gauge init js`
* Create project2 `gauge init js`
* Add them to the same workspace
* One of the projects is showing `Duplicate step implementation` for all the steps.

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-15
Commit Hash: 15c9822

Plugins
-------
js (2.1.1.nightly-2018-01-15)
```

**Comment by sguptatw** [comment]
Goto definition of a concept shows information about the same name concept defined in the other workspace

<img width="688" alt="gotodefinition" src="https://user-images.githubusercontent.com/6310197/34972554-49b67922-faa8-11e7-85de-b7d400afd612.png">

> Note: This is not a consistent behavior across workspaces. In the other workspace this information is not displayed on navigating to the concept.

**Question**
What is the expected behavior?

**Comment by sguptatw** [comment]
**Issue**
Code Lens appear twice

**Expected behavior**
Code Lens to run the spec or scenario should appear only once.

**Actual behavior**
It appears twice

<img width="409" alt="codelens" src="https://user-images.githubusercontent.com/6310197/34972788-d886c08e-faa9-11e7-9b0c-1e0860372f83.png">

**Steps to replicate**
* Create project1 gauge init js
* Create project2 gauge init js
* Add them to the same workspace
* Open example.spec from projects. One of them is showing the code lens twice.

**Comment by sguptatw** [comment]
Find usages must be limited to the workspace - https://github.com/getgauge/gauge-vscode/issues/91

**Comment by sguptatw** [comment]
Tracking Multiple gauge projects with different language runners - https://github.com/getgauge/gauge-vscode/issues/104 separately
