### ISSUE TITLE
Current gauge language runner is not compatible with gauge LSP. Some of the editing feature will not work as expected

### ISSUE THREAD

**Issue by pratapkuchipudi** [getgauge/gauge-vscode#462]
Still getting the same

**Comment by NivedhaSenthil** [comment]
can you please provide more info regarding your environment and when do you see this error happening ?

**Comment by pratapkuchipudi** [comment]
Yes, 
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041


This is the error
omation\\gauge_bin\"  \"netcore-template.csproj\" --verbosity=quiet'\n   at Gauge.Dotnet.GaugeProjectBuilder.BuildTargetGaugeProject() in \/home\/runner\/work\/gauge-dotnet\/gauge-dotnet\/src\/GaugeProjectBuilder.cs:line 50\r\n   at Gauge.Dotnet.StartCommand.TryBuild() in \/home\/runner\/work\/gauge-dotnet\/gauge-dotnet\/src\/StartCommand.cs:line 62"}
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	windows, 1.1.1, 6e0d83f
	csharp (0.10.6), dotnet (0.1.6), html-report (4.0.12), screenshot (0.0.1)
Error: Tests failed.

**Comment by pratapkuchipudi** [comment]
> Yes,
> Version: 1.49.0 (user setup)
> Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
> Date: 2020-09-10T13:22:08.892Z
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041
> 
> This is the error
> omation\gauge_bin" "netcore-template.csproj" --verbosity=quiet'\n at Gauge.Dotnet.GaugeProjectBuilder.BuildTargetGaugeProject() in /home/runner/work/gauge-dotnet/gauge-dotnet/src/GaugeProjectBuilder.cs:line 50\r\n at Gauge.Dotnet.StartCommand.TryBuild() in /home/runner/work/gauge-dotnet/gauge-dotnet/src/StartCommand.cs:line 62"}
> Error occurred while waiting for runner process to finish.
> Error : exit status 1
> Error ----------------------------------
> 
> [Gauge]
> Failed to start gauge API: Error occurred while waiting for runner process to finish.
> Error : exit status 1
> 
> Get Support ----------------------------
> Docs: https://docs.gauge.org
> Bugs: https://github.com/getgauge/gauge/issues
> Chat: https://spectrum.chat/gauge
> 
> Your Environment Information -----------
> windows, 1.1.1, 6e0d83f
> csharp (0.10.6), dotnet (0.1.6), html-report (4.0.12), screenshot (0.0.1)
> Error: Tests failed.

**Comment by pratapkuchipudi** [comment]
any update on this?

Pratap Kumar Kuchipudi
Mobile:08125877677
Email: pratapkuchipudi@gmail.com

**Comment by sriv** [comment]
There have been some new releases, can you try with latest gauge/gauge-dotnet?

If you still face this issue, would you be able to share a sample project for us to replicate?

**Comment by NivedhaSenthil** [comment]
@pratapkuchipudi any updates on the issue? were you able to check the logs for any info ?
