### ISSUE TITLE
Run Scenario in command palette shows unwanted description

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#49]
```
VS-Code version: 1.18.1
Gauge Extension Version: 0.0.3

Gauge version: 0.9.5
Commit Hash: f539aef

Plugins
-------
csharp (0.10.1)
go (0.1.1)
html-report (4.0.2)
java (0.6.5.nightly-2017-09-05)
js (2.0.3)
python (0.2.2)
ruby (0.4.2)
screenshot (0.0.1)

```

### Steps to reproduce
* Open the command palette
* Search for "Run Scenario"
* The command pallete lists this command as `Run Scenario gauge.execute.scenarios`

### Expected behavior
* Remove the text `gauge.execute.scenarios`

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 22-11-2017
