### ISSUE TITLE
Gauge initialization for .spec and .cpt files

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#5]
VSCode should consider .spec and .cpt files as markdown, so that all markdown features available in VSCode is activated for .spec and .cpt files too. 
VSCode should activate gauge if .spec, .cpt or .md files are opened and the current directory is a gauge project. Gauge daemon should be started to provide LSP features, like code completion, for these files.

**Comment by nehashri** [comment]
Nightly builds available [here](https://bintray.com/gauge/gauge-vscode/Nightly)

**Comment by sguptatw** [comment]
Apart from activating the markdown, the new file created have the relevant templates too. e.g- The way Visual studio and IntelliJ do for a spec and concept.

**Comment by sguptatw** [comment]
A newly created spec file should have
```
Specification Heading
=====================
Created by <username> on <date>

This is an executable specification file which follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.
     
Scenario Heading
----------------
```
A newly created concept file should have
```
Created by <user> on <date>

This is a concept file with following syntax for each concept.
# Concept Heading
* step1
* step2
```

**Comment by nehashri** [comment]
@sguptatw that looks like a feature request. Can you please raise an issue for the same

**Comment by sguptatw** [comment]
https://github.com/getgauge/gauge-vscode/issues/7
