### ISSUE TITLE
Should handle a project with space in path

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#50]
**Expected behavior**
Gauge functionality should work normally when there is a space in the project path

**Actual behavior**
Getting
```
09:59:40.267 failed to parse specification <folderpath>\Downloads\test1%!\(MISSING)test1\specs\example.spec
```
**Steps to replicate**
* Create project with space in the path
`test1 1\projectfolder`
* Open VS code.
* Add an unimplemented step
> Observe code action for generating stubs for unimplemented step is not available

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-22
Commit Hash: 9432093

Plugins
-------
js (2.0.3.nightly-2017-11-22)
```

**Comment by sguptatw** [comment]
**Expected behavior**
The step reference count displayed is wrong.

**Actual behavior**
Count shown is wrong

<img width="696" alt="usages" src="https://user-images.githubusercontent.com/6310197/33304182-6005f0a0-d42d-11e7-8c7e-3a47b61177e2.png">
> Observe the search window is showing
- a log file
- a js file
- a spec file
There is only one usage in the project. But it displays 4

**Steps to replicate**
* The spec file name has a space.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 1/12/17
