### ISSUE TITLE
VS Code 1.51.0 breaks some intellisense functionality

### ISSUE THREAD

**Issue by CharlieDigital** [getgauge/gauge-vscode#509]
# Describe the bug

VS Code 1.51.0 breaks some intellisense behavior.

1. ~~Editor no longer highlights/underlines Step statements which have no backing implementation (works fine for Scenarios)~~
2. For Step statements with backing implementation, `CTRL+Click` does not highlight the line but individual words in the line (still works fine, just a change in behavior)

### What command(s) did you run when you found the bug?

N/A

### Output, stack trace or logs related to the bug

N/A

### Versions

```
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

#### Gauge (Output of `gauge -v`)

```
gauge -v
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)
ts (0.1.0)
```

#### Node.js/Java/Python/.Net/Ruby version

`Node.js: 12.14.1`

#### Operating System information

`OS: Windows_NT x64 10.0.18363`

#### IDE information

```
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
```

**Comment by CharlieDigital** [comment]
Strike the first issue; after reloading VS Code, it seemed to be resolved.

However, second issue (minor) is still occurring.

**Comment by NivedhaSenthil** [comment]
are you still see this.. I could see the step implementation being highlighted fully. Can you attach a screenshot for us to understand this scenario better ?

**Comment by zabil** [comment]
I see it working for me too in the versions menioned. Closing this until there are further details.
