### ISSUE TITLE
For a new project diagnostics and goto definition does not work

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#51]
**Expected behavior**
Gauge functionality should work for a new project

**Actual behavior**
Diagnostics and goto definition does not work

**Steps to replicate**
* Create a new project.
* Open in VS code

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-22
Commit Hash: 9432093

Plugins
-------
js (2.0.3.nightly-2017-11-22)
```

**Comment by Apoorva-GA** [comment]
Fix is available in gauge nightly >= 23/11/17
