### ISSUE TITLE
Duplicate scenario definition should have details about the other step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#52]
**Expected behavior**
I should be able to identify the duplicate scenario with the message.

**Actual behavior**
The current error message has line number details of the current scenario

**Steps to replicate**
* Create duplicate Scenario

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-22
Commit Hash: 9432093

Plugins
-------
js (2.0.3.nightly-2017-11-22)
```

**Comment by zabil** [comment]
This behavior is fine as long as it highlights one of the scenarios. 
It's easy to locate duplicates within the document.

e.g.

![duplicatescenario](https://user-images.githubusercontent.com/54427/34093307-7f2f9f7e-e3ed-11e7-8fe2-962cc12b38fb.png)
