### ISSUE TITLE
Diagnostic errors are not displayed when the highest specification folder is not specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#53]
**Expected behavior**
Diagnostics should appear for gauge files.

**Actual behavior**
Diagnostics are being displayed only when specs is the highest folder of specifications.

**Steps to replicate**
* Create a gauge js project
```
gauge init js
```
* Rename specs to something
* Open in vscode
* add an unimplemented step
* Diagnostic errors are not displayed
> Observation run, goto definition are working.

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-22
Commit Hash: 9432093

Plugins
-------
js (2.0.3.nightly-2017-11-22)
```

**Comment by zabil** [comment]
This will work if you modify `env/default/default.properties` and `gauge_specs_dir = renamedfolder`
