### ISSUE TITLE
Getting Invalid response and Request timeouts

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#54]
**Expected behavior**
I should be able to work with VS Code seamlessly

**Actual behavior**
Getting `Invalid response` and `Request timout` errors on the steps

**Steps to replicate**
* Work on the gauge-lsp-tests for a while
* Keep switching between IDE and command line running tests - multiple times.
> Observe these errors occurs after a while

<img width="552" alt="requesttimeout" src="https://user-images.githubusercontent.com/6310197/33175032-4f6bcd88-d080-11e7-8fb2-12b6d033fcc5.png">

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
```

**Comment by sguptatw** [comment]
<img width="647" alt="invalidresponse" src="https://user-images.githubusercontent.com/6310197/33305814-b4dd8f04-d435-11e7-9bd2-3ef57fccdbbe.png">

**API Logs**
```
11:53:43.932 Initializing steps cache with 5 steps
11:53:45.915 LangServer: reading on stdin, writing on stdout
11:54:23.620 Error while connecting to runner : Request Timeout
```

**Gauge Logs**
```
11:47:17.028 
Total time taken: 400ms
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
11:53:43.871 Gauge Install ID: 8f2038dc-6258-46c4-826d-9691cfbb1370
11:53:43.934 Starting language runner
```

**Comment by BugDiver** [comment]
Steps to reproduce:- 
* Open a fresh gauge-js project in code.
* open spec and implementation file
* Keep implementation file in focus
* reload the project 
* quickly switch to spec file and perform a `go to definition` action (quickly)

**Comment by sriv** [comment]
@BugDiver - I suppose this can be scripted out? by hitting some LSP endpoints?

**Comment by BugDiver** [comment]
Should be fixed in nightly >= 12-12-2017

**Comment by sguptatw** [comment]
Issues
- [ ] Parallel run task is getting hung - getgauge/gauge#899
