### ISSUE TITLE
Should show stacktrace when exception is thrown

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#55]
**Expected behavior**
Should show stacktrace when exception is thrown

**Actual behavior**
- does not show the stack trace for `throw 'Error'`
```
throw 'Error2'; // generates an exception with a string value
throw 42;       // generates an exception with the value 42
throw true;     // generates an exception with the value true
```
- [x] Works for an assertion failure
- [x] Works for `throw new Error('Unimplemented Step');`

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
```

**Comment by BugDiver** [comment]
@sguptatw That's not an issue with the plugin. It's the way how `nodejs` handle errors.
`throw "Error"` is not same as `throw new Error("Error")`. first one is a primitive, not an object. throwing a primitive will not capture any stack trace.
