### ISSUE TITLE
Error when clicking on References annotation on the Steps file

### ISSUE THREAD

**Issue by deepabgit** [getgauge/gauge-vscode#556]
This issue is related to gauge-vscode extension.

Get the following error when clicking references in the Steps file:

failed to parse request json: cannot unmarshal array into Go value of type string

Gauge Extension is 0.0.19
Visual Studio Code is 1.52.1

Please see below screenshot:

![image](https://user-images.githubusercontent.com/72279222/103939866-5478d200-50e1-11eb-889d-9e4ec0f9d029.png)

Thanks,
Deepa

**Comment by zabil** [comment]
Duplicate of #555
