### ISSUE TITLE
Stop execution when the user chooses to

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#56]
**Proposed behavior**
User should be able to stop an execution which is started

**Actual behavior**
There is no way to stop executions

**Things to consider**
* User can execute in multiple sessions.

**Comment by sriv** [comment]
Current status:

- Only one execution at a time. Warn user if execution is in progress.
- Add a command to stop execution (shows up in command pallette)
- Show progress of execution (currently shows at status bar)
- Add button to stop execution (shown next to progress)
- progress and button shown only during execution

Preview:
![2017-12-06_07-39-04.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/565d81a4bb6deb13000d012e/125516c66e82c728ace21e0d46bac4cb74cfd2fbc2b9e97cf40abdc7700b77276b48e13b628ae92dbc56395b4d5a48a915505e12a9af8a78f3e23c748c5c0be9806e0c71c42f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e6898a4d38180c1d8bf85927ed.gif)

**Comment by BugDiver** [comment]
Should be available in nightly >= 13-12-2017
