### ISSUE TITLE
Handle/remove panic runtime errors

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#57]
**Problem**
When there is a panic runtime exception from gauge, the gauge process is getting killed in the IDE.

**Observations**
IDE VSCode gives the error `The language server crashed 5 times in the last 3 minutes`

**Expected behavior**
IDE should continue working

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
screenshot (0.0.1
```

**Comment by nehashri** [comment]
This issue is because gauge throws panic in some places. It should be handled as a part of https://github.com/getgauge/gauge/issues/877
