### ISSUE TITLE
Snippets for gauge

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#6]
Snippets for specification, scenario and tables should be added for markdown files. 
Snippet provided -

|Key|Snippet|
|---|---|
|spec|Specification Heading|
|sce|Scenario Heading|
|table:1|Table with 1 column|
|table:2|Table with 2 columns|
|table:3|Table with 3 columns|
|table:4|Table with 4 columns|
|table:5|Table with 5 columns|
|table:6|Table with 6 columns|

**Comment by sguptatw** [comment]
Unable to test as the build is broken

**Comment by nehashri** [comment]
Nightly builds available [here](https://bintray.com/gauge/gauge-vscode/Nightly)

**Comment by sguptatw** [comment]
Short cut to invoke the snippets - Ctrl+space with the snippet names

**Comment by sguptatw** [comment]
Since we are looking markdown templates. Can a new file created have the relevant templates too. e.g- The way Visual studio and IntelliJ do for a spec and concept.

**Comment by sguptatw** [comment]
When table snippet is invoked on a step. Can the template be inserted in the next line?

**Comment by nehashri** [comment]
@sguptatw doesn't look like there is a way to insert text in new line in VSCode yet.
