### ISSUE TITLE
Running the contributed command: 'gauge.showReferences' fail

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge-vscode#611]
### Describe the bug
When I click on the "reference" link above a method, it won't show the file where the method was referenced.

### What command(s) did you run when you found the bug?
Just regular coding in Python with Gauge in VSCode

### Output, stack trace or logs related to the bug
I just get a notification (bottom right):
"Running the contributed command: 'gauge.showReferences' fail..."

#### Gauge (Output of `gauge -v`)
Gauge version: 1.1.7
Plugins
-------
html-report (4.0.12)
python (0.3.14)
screenshot (0.0.1)

#### Node.js/Java/Python/.Net/Ruby version
Python 3.7.4

#### Operating System information
macOS 11.2.3

#### IDE information
Visual Studio Code 1.54.3

**Comment by sriv** [comment]
hi, do you see any errors logged in the `lsp.log` file? This file should be under the `logs` directory in your project.

**Comment by florinalex1984** [comment]
Hi, i'm receiving the same error, and, in lsp.log file, i think this issue is logged
`07-04-2021 14:39:33.638 [Gauge] [DEBUG] request #4: gauge/stepReferences: failed to parse request json: cannot unmarshal array into Go value of type string`

**Comment by zabil** [comment]
Thanks for logs. This is supposed to be fixed via https://github.com/getgauge/gauge/pull/1858

Have you tried upgrading to the latest version of Gauge (1.1.8)?

**Comment by florinalex1984** [comment]
Yes, it's fixed on v1.1.8. thank you
