### ISSUE TITLE
Error calculating project classpath

### ISSUE THREAD

**Issue by HalloThomas** [getgauge/gauge-vscode#613]
### Describe the bug
* Vs code start with an existing project
### Output, stack trace or logs related to the bug
* error message: "Error calculating project classpath.	
,,Der Befehl "undefined" ist entweder falsch geschrieben oder
konnte nicht gefunden werden."

_* Code\User\settings.json_

> _{
>     "workbench.editor.enablePreview": false,
>     "gauge.launch.enableDebugLogs": true,
>     "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
>     "window.zoomLevel": 1,
>     "editor.multiCursorModifier": "ctrlCmd",
>     "gauge.recommendedSettings.options": "Apply & Reload",
>     "gauge.execution.debugPort": null
> }_

_* .vscode\settings.json_

> _{
>     "files.associations": {
>         "*.spec": "gauge",
>         "*.itsispec": "markdown",
>         "*.cpt": "gauge",
>         "*.md": "gauge"
>     },

    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 500,
    
    "markdown.extension.toc.omittedFromToc": {
    
    },

    "gauge.execution.debugPort": null,
    "gauge.launch.enableDebugLogs": true,
    "gauge.recommendedSettings.options": "Apply & Reload"
}_
### Versions
Gauge version: 1.1.7
Commit Hash: 5d86b72

Plugins
-------
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
screenshot (0.0.1)
spectacle (0.1.4)
#### Node.js/Java/Python/.Net/Ruby version
Node.js v15.11.0
npm@7.6.3
#### Operating System information
MS Windows Version 1607
#### IDE information
Visual Studio Code 1.54.3

**Comment by sriv** [comment]
Hi, is this error occurring in a gauge-java project? Is there a sample project that you can share for me to replicate this? Thanks.

**Comment by HalloThomas** [comment]
Hello, it's a gauge javascript project. I have not yet tried to create an example project with the error.

**Comment by sriv** [comment]
this is strange and unexpected. gauge-vscode should not be considering classpath for javascript projects! If you get a chance to create a sample project that'd help us troubleshoot. Thanks

**Comment by HalloThomas** [comment]
Now I can reproduce the error, the file "pom.xml" (empty or not) in the main folder triggers the error message.

**Comment by sriv** [comment]
thanks for that, I can replicate this now. I'll push a fix
