### ISSUE TITLE
Why on vscode, we do not see the "Debug Spec" option

### ISSUE THREAD

**Issue by smaikk** [getgauge/gauge-vscode#628]
#### Gauge (Output of `gauge -v`)
Gauge version: 1.1.8
Commit Hash: b1501f4

Plugins
-------
dotnet (0.3.1)
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

**Comment by zabil** [comment]
I ran the following commands

```
gauge init java_maven_selenium
maven compile
maven test-compile
code . # open vs code
```

The debug option does appear.

<img width="763" alt="Screenshot 2021-04-06 at 12 57 15" src="https://user-images.githubusercontent.com/54427/113707449-d627ce00-96d7-11eb-996c-c4d356c13d3b.png">

It maybe due to a configuration issue of the Java JDK

Here are my versions

```
/usr/libexec/java_home
/Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home

Gauge version: 1.1.8
Plugins
-------
dotnet (0.3.0)
flash (0.0.2)
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
json-report (0.3.5)
python (0.3.12)
ruby (0.5.4)
screenshot (0.0.1)
spectacle (0.1.4)
ts (0.1.0)
xml-report (0.2.3)

code --version
1.55.0
c185983a683d14c396952dd432459097bc7f757f
x64
```

**Comment by zabil** [comment]
You can also try checking errors at `logs/lsp.log`

**Comment by smaikk** [comment]
Thank you Zabil for your responsiveness!

I just changed the java 11 version to java 16, and suddenly the problem is solved!

I also have the problem of the green color of the steps which is not recognized!

![image](https://user-images.githubusercontent.com/34989545/113715296-9ff34a00-96e9-11eb-8071-6b154074fc21.png)

**Comment by zabil** [comment]
> green color of the steps which is not recognized

What do you mean by this? When I try entering a step which is not recognized it highlights the error for example

<img width="271" alt="Screenshot 2021-04-06 at 14 14 03" src="https://user-images.githubusercontent.com/54427/113716320-5eab6c00-96e2-11eb-99af-8ed195339896.png">


Also, I am closing this for now as the original issue is solved, but please feel free to carry on discussing.

**Comment by smaikk** [comment]
No, just the font color, the steps are well recognized, without error, but the color of the steps is always displayed in white fonts.

See in the screenshot, the difference between the appearance of the steps on my vscode and on your vscode.

![image](https://user-images.githubusercontent.com/34989545/113718092-98817000-96ec-11eb-95a0-c6da37a5f0f4.png)

**Comment by zabil** [comment]
Ah ok. The color is different because I was using a different VS Code theme (Monokai). Switching back to default color scheme makes it the same as yours.
