### ISSUE TITLE
Cancelling run scenarios gives error

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-vscode#65]
In a gauge project, 
- open a spec file
- Focus cursor outside of scenario context
- from command palette choose `Gauge: Run Scenario`
- A list of scenarios in the specs will be shown.
- Cancel the command, press `esc`
- An error dialog is shown with message `Cannot read property 'label' of undefined`

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-vscode nightly >= 4/12/17
