### ISSUE TITLE
Multiple goto definitions on a project with 900 specs stops working

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#67]
**Expected behavior**
Should be able to gauge features on a project with 900 specs

**Actual behavior**
Gauge features goto definition, find usages stop working.

**Steps to replicate**
* Open project [performance.zip](https://github.com/getgauge/gauge/files/1526752/performance.zip)
* Open Duplicate Definitions.cpt
* Goto Concept Heading6
* Goto example spec
* Goto definition
(multiple times)

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-01
Commit Hash: fdcd4e2

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```
IDE - gauge-0.0.3.nightly-2017-12-01.vsix

**Comment by sriv** [comment]
@sguptatw - please upload the project with this issue.

**Comment by sguptatw** [comment]
@sriv : Please find the project inline the issue description

**Comment by sguptatw** [comment]
Not replicable with the latest gauge version
