### ISSUE TITLE
DebugLogs configuration must be honoured

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#68]
**Expected behavior**
If "gauge.launch.enableDebugLogs": false then LSP logs should not appear in the output pane

**Actual behavior**
It appears in the output pane.

**Steps to replicate**
* Install the vscode nightly - gauge-0.0.3.nightly-2017-12-05.vsix
* The default setting is false.
* Open a file.
> Observe the output pane with log details.

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-04
Commit Hash: 584485d

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```

**Comment by sguptatw** [comment]
When there user tries to navigate to a step with no implementation. The Gauge logs are getting printed even if "gauge.launch.enableDebugLogs": false

[Error - 2:32:45 PM] Request textDocument/definition failed.
  Message: Step implementation not found for step : List of errors should be asserted irrespective of the order
  Code: 0

**Comment by nehashri** [comment]
@sguptatw Only the errors are getting printed, I thought this was the expectation.
Do you really want to hide the errors from the user too? If we do that, it will be hard to debug any issue posted.
