### ISSUE TITLE
Should be able to run specs in parallel

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#70]
**Expected behavior**
Should be able to run specs in parallel

**Actual behavior**
Unable to run specs in parallel

**Steps to replicate**
* In IDE, click 'Run in parallel'
* this is not running specs in parallel

**Version**
```
gauge-0.0.3.nightly-2017-12-08
```

**Comment by BugDiver** [comment]
should be fixed in nightly >= 13-12-2017
