### ISSUE TITLE
Repeat last run from IDE gives Scenario still running

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#71]
**Expected behavior**
If an execution is completed. I must be able to repeat the last run

**Actual behavior**
`Path must be string receiving null`. Then trying to rerun am Getting `Scenario is still running`
<img width="960" alt="pathmustbeastring" src="https://user-images.githubusercontent.com/6310197/33932908-400396f6-e01a-11e7-9822-cfa499983cc6.png">

<img width="960" alt="scenariostillrunning" src="https://user-images.githubusercontent.com/6310197/33931926-827353a8-e017-11e7-8ffb-a0f4773af288.png">

**Steps to replicate**
* LSP tests - run c:\work\getgauge\gauge-lsp-tests\specs\diagnostics\concept diagnostics.spec
* Now from the js file re-run using the IDE command pallete
* Getting the above error

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-12
Commit Hash: 643882c

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```
IDE - gauge-0.0.3.nightly-2017-12-08.vsix

**Comment by sguptatw** [comment]
Unable to run specs from the IDE after this.

**Comment by BugDiver** [comment]
This issue occurs when running `Re-Run failed scenarios` from `vscode` command-palate as well.

**Comment by BugDiver** [comment]
fix should be available in nightly >= 13-12-2017
