### ISSUE TITLE
The "Test Explorer" view (GAUGE SPECS) is not displayed

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-vscode#722]
### Describe the bug
The test explorer view "GAUGE SPECS" is not displayed in my java gauge test project on VSCode

### Output, stack trace or logs related to the bug
![image](https://user-images.githubusercontent.com/59898499/132198860-77399c14-e594-463e-97d1-0385e22406c9.png)

####  (Output of `gauge -v`)
![image](https://user-images.githubusercontent.com/59898499/132197332-afaa6d3b-457f-4dbf-9c24-5bc9f673758d.png)

#### IDE information
Gauge-VSCode : v0.0.21

**Comment by zabil** [comment]
I think the screenshot is outdated. It should appear under the "Tests" section

<img width="342" alt="Screenshot 2021-09-09 at 13 41 10" src="https://user-images.githubusercontent.com/54427/132687709-3ac0d7e4-342e-44f6-b372-0c0f105191f0.png">

**Comment by zbrea** [comment]
Thank-you for your prompt response.
But in the explorer Text section it never shows me anything.
Is there a configuration to activate somewhere or it should be displayed by default?

![image](https://user-images.githubusercontent.com/59898499/132696086-b8757ff4-e4d5-45a0-8d84-af447e0a935c.png)

**Comment by zbrea** [comment]
Thank you my friend,
Now it works very well
