### ISSUE TITLE
Recurring gauge initialization problem message

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-vscode#734]
### Describe the bug
Often I get a message from the problem, that Gauge cannot initialize. while the extension 'vscjava.vscode-java-pack' is well installed.
But  I deactivate  I reactivate vscode-gauge in VSCode, the message disappears. I've had this problem, every time  I start from Vscode
I am trying to convince my team to use this nice gauge framework, but this kind of problem can discourage them to use it.

### Output, stack trace or logs related to the bug
![image](https://user-images.githubusercontent.com/59898499/132951046-7fb5b66f-fddf-489d-a20b-2ba9ee1f1793.png)

#### Gauge (Output of `gauge -v`)
![image](https://user-images.githubusercontent.com/59898499/132951344-4955959f-968e-4ab9-9eca-a2ca1a794e5d.png)

#### Node.js/Java/Python/.Net/Ruby version
![image](https://user-images.githubusercontent.com/59898499/132951390-9e9bef06-2882-4b59-a29f-bdb065a35edc.png)

#### IDE information
VS Code: 
![image](https://user-images.githubusercontent.com/59898499/132952276-7c268dfb-5611-49d1-bef3-2633576a6619.png)

vscjava.vscode-java-pack installed.:
![image](https://user-images.githubusercontent.com/59898499/132951706-28d21f6d-a591-4d02-921c-0d91a49e630f.png)

**Comment by sriv** [comment]
Could you please inspect and share any errors that are visible in `gauge.log` file? It is quite possible that the underlying error and the error being reported are different. Thanks

**Comment by zbrea** [comment]
Thank-you for your prompt response.

I created a new project after deleting all the logs, to have short and clear logs.
So the problem occurs before the evening gauge log is created.
I give you lisp.log file which better details the problem when checking and installing the application.

[lsp.log](https://github.com/getgauge/gauge-vscode/files/7149416/lsp.log)

**Comment by sriv** [comment]
The files that you've attached seem to be unavailable to me, I get a 'Not Found' message. If you can inspect the files and see if there are any errors, we can troubleshoot this further.

**Comment by zbrea** [comment]
[lsp.log](https://github.com/getgauge/gauge-vscode/files/7157088/lsp.log)

**Comment by zbrea** [comment]
12-09-2021 11:07:47.425 [Gauge] [INFO] Initializing specs cache with 1 specs
12-09-2021 11:07:47.425 [Gauge] [DEBUG] Adding specs from c:\Workspace\MVN\specs\example.spec
12-09-2021 11:07:47.425 [Gauge] [INFO] Initializing steps cache with 1 steps
12-09-2021 11:07:47.426 [Gauge] [INFO] Starting language runner
12-09-2021 11:07:47.485 [Gauge] [DEBUG] Watching directory: c:\Workspace\MVN\specs
12-09-2021 11:07:47.488 [Gauge] [DEBUG] Found 1 files
12-09-2021 11:07:47.926 [java] [DEBUG] ***** Printing Properties/Env Values *****
12-09-2021 11:07:47.926 [java] [DEBUG] PATH: 
	C:\Program Files\Common Files\Oracle\Java\javapath; 
	C:\Sources\apache-maven-3.6.3\bin; 
	C:\Program Files\Java\jdk-11.0.11\bin; 
	C:\Sources\maven-compiler-plugin-3.8.1; 
	C:\Program Files\nodejs\; 
	C:\Program Files\PowerShell\7\; 
	C:\Gradle\gradle-7.0\bin; 
	C:/Program Files/nodejs\node.exe; 
	C:\Program Files\PowerShell\7-preview\preview; 
	C:\Program Files\Git\cmd; 
	C:\Program Files\Gauge\bin; 
	C:\Users\s.keddar\AppData\Roaming\cmder\bin; 
	C:\Program Files\Gauge\bin; 
	C:\Users\s.keddar\AppData\Local\Microsoft\WindowsApps; 
	C:\Sources\apache-maven-3.6.3\bin; 
	C:\Users\s.keddar\.dotnet\tools; 
	C:\Sources\apache-maven-3.6.3\bin; 
	C:\Sources\maven-compiler-plugin-3.8.1; 
	C:\Program Files\Gauge\plugins\screenshot\0.1.0
12-09-2021 11:07:47.926 [java] [DEBUG] JAVA_HOME: C:\Program Files\Java\jdk-11.0.11
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_project_root: c:\Workspace\MVN
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_parallel_streams_count: 
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_reports_dir: reports
12-09-2021 11:07:47.926 [java] [DEBUG] overwrite_reports: true
12-09-2021 11:07:47.926 [java] [DEBUG] logs_directory: logs
12-09-2021 11:07:47.926 [java] [DEBUG] enable_multithreading: false
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_specs_dir: specs
12-09-2021 11:07:47.926 [java] [DEBUG] csv_delimiter: ,
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_java_home: 
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_custom_build_path: 
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_additional_libs: libs/*
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_jvm_args: 
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_custom_compile_dir: 
12-09-2021 11:07:47.926 [java] [DEBUG] gauge_clear_state_level: scenario
12-09-2021 11:07:47.926 [java] [DEBUG] ***** END *****

12-09-2021 11:08:07.896 [java] [DEBUG] classpath set to c:\Workspace\MVN\target\test-classes; 
c:\Workspace\MVN\target\classes; 
C:\Sources\maven\repository\com\thoughtworks\gauge\gauge-java\0.7.15\gauge-java-0.7.15.jar; 
C:\Sources\maven\repository\org\reflections\reflections\0.9.9\reflections-0.9.9.jar; 
C:\Sources\maven\repository\org\javassist\javassist\3.18.2-GA\javassist-3.18.2-GA.jar; 
C:\Sources\maven\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; 
C:\Sources\maven\repository\com\github\javaparser\javaparser-core\3.16.3\javaparser-core-3.16.3.jar; 
C:\Sources\maven\repository\commons-io\commons-io\2.8.0\commons-io-2.8.0.jar; 
C:\Sources\maven\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar; 
C:\Sources\maven\repository\org\json\json\20210307\json-20210307.jar; 
C:\Sources\maven\repository\com\google\protobuf\protobuf-java\3.15.8\protobuf-java-3.15.8.jar; 
C:\Sources\maven\repository\com\google\guava\guava\30.1.1-jre\guava-30.1.1-jre.jar; 
C:\Sources\maven\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar; 
C:\Sources\maven\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar; 
C:\Sources\maven\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar; 
C:\Sources\maven\repository\org\checkerframework\checker-qual\3.8.0\checker-qual-3.8.0.jar; 
C:\Sources\maven\repository\com\google\errorprone\error_prone_annotations\2.5.1\error_prone_annotations-2.5.1.jar; 
C:\Sources\maven\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar; 
C:\Sources\maven\repository\io\grpc\grpc-netty-shaded\1.37.0\grpc-netty-shaded-1.37.0.jar; 
C:\Sources\maven\repository\io\grpc\grpc-core\1.37.0\grpc-core-1.37.0.jar; 
C:\Sources\maven\repository\com\google\code\gson\gson\2.8.6\gson-2.8.6.jar; 
C:\Sources\maven\repository\com\google\android\annotations\4.1.1.4\annotations-4.1.1.4.jar; 
C:\Sources\maven\repository\io\perfmark\perfmark-api\0.23.0\perfmark-api-0.23.0.jar; 
C:\Sources\maven\repository\io\grpc\grpc-protobuf\1.37.0\grpc-protobuf-1.37.0.jar; 
C:\Sources\maven\repository\io\grpc\grpc-api\1.37.0\grpc-api-1.37.0.jar; 
C:\Sources\maven\repository\io\grpc\grpc-context\1.37.0\grpc-context-1.37.0.jar; 
C:\Sources\maven\repository\com\google\api\grpc\proto-google-common-protos\2.0.1\proto-google-common-protos-2.0.1.jar; 
C:\Sources\maven\repository\io\grpc\grpc-protobuf-lite\1.37.0\grpc-protobuf-lite-1.37.0.jar; 
C:\Sources\maven\repository\org\codehaus\mojo\animal-sniffer-annotations\1.19\animal-sniffer-annotations-1.19.jar; 
C:\Sources\maven\repository\io\grpc\grpc-stub\1.37.0\grpc-stub-1.37.0.jar; 
C:\Sources\maven\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar; 
C:\Sources\maven\repository\org\assertj\assertj-core\3.17.2\assertj-core-3.17.2.jar

12-09-2021 11:08:07.995 [java] [DEBUG] found java executable in C:\Program Files\Java\jdk-11.0.11\bin\java.exe
12-09-2021 11:08:07.995 [java] [DEBUG] running - C:\Program Files\Java\jdk-11.0.11\bin\java.exe [-Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime --start]
12-09-2021 11:08:07.995 [java] [DEBUG] stdout/stderr is logged to logs\170984-java.exe.out
12-09-2021 11:08:09.189 [java] [DEBUG] multithreading is set to false
12-09-2021 11:08:10.872 [java] [DEBUG] Using reflection to scan dependencies for gauge implementations...
12-09-2021 11:08:17.660 [Gauge] [DEBUG] Gauge could not initialize. Install 'vscjava.vscode-java-pack' extension for code insights. For more information see[Problems](command:workbench.actions.view.problems), check logs.[Troubleshooting](https://docs.gauge.org/troubleshooting.html?language=javascript&ide=vscode#gauge-could-not-initialize-for-more-information-see-problems)
Some of the gauge lsp feature will not work as expected.
12-09-2021 11:08:17.660 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
12-09-2021 11:08:17.660 [Gauge] [DEBUG] jsonrpc2: <-- notif: window/showMessage: {"type":1,"message":"Gauge could not initialize. Install 'vscjava.vscode-java-pack' extension for code insights. For more information see[Problems](command:workbench.actions.view.problems), check logs.[Troubleshooting](https://docs.gauge.org/troubleshooting.html?language=javascript\u0026ide=vscode#gauge-could-not-initialize-for-more-information-see-problems)"}
12-09-2021 11:08:17.661 [Gauge] [DEBUG] jsonrpc2: --> request #0: initialize: {"processId":168828,"clientInfo":{"name":"Visual Studio Code","version":"1.60.0"},"locale":"fr","rootPath":"c:\\Workspace\\MVN","rootUri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true,"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true},"activeParameterSupport":true},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true,"tagSupport":{"valueSet":[1]},"labelSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"disabledSupport":true,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"honorsChangeAnnotations":false},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1,"honorsChangeAnnotations":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false},"linkedEditingRange":{"dynamicRegistration":true}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"showDocument":{"support":true},"workDoneProgress":true},"general":{"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"markdown":{"parser":"marked","version":"1.1.0"}},"saveFiles":true},"trace":"off","workspaceFolders":[{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN","name":"MVN"}]}
12-09-2021 11:08:17.816 [Gauge] [DEBUG] jsonrpc2: <-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["*","* ","\"","\u003c",":",","]},"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"renameProvider":true}}
12-09-2021 11:08:17.989 [java] [DEBUG] Scanning packages for steps
12-09-2021 11:08:18.071 [java] [DEBUG] Comparing 'StepImplementation.verifyVowelsCountInMultipleWords' and 'StepImplementation.verifyVowelsCountInMultipleWords'
12-09-2021 11:08:18.071 [java] [DEBUG] Found Almost all words have vowels {} in current project scope.
12-09-2021 11:08:18.071 [java] [DEBUG] Comparing 'StepImplementation.setLanguageVowels' and 'StepImplementation.setLanguageVowels'
12-09-2021 11:08:18.071 [java] [DEBUG] Found Vowels in English language are {}. in current project scope.
12-09-2021 11:08:18.071 [java] [DEBUG] Comparing 'StepImplementation.verifyVowelsCountInWord' and 'StepImplementation.verifyVowelsCountInWord'
12-09-2021 11:08:18.071 [java] [DEBUG] Found The word {} has {} vowels. in current project scope.
12-09-2021 11:08:18.071 [java] [DEBUG] Scanning packages for hooks
12-09-2021 11:08:18.071 [java] [DEBUG] Scanned steps (using static parsing + reflections): 
12-09-2021 11:08:18.071 [java] [DEBUG] 	The word {} has {} vowels. : public void verifyVowelsCountInWord(String word, int expectedCount)
12-09-2021 11:08:18.071 [java] [DEBUG] 	Almost all words have vowels {} : public void verifyVowelsCountInMultipleWords(Table wordsTable)
12-09-2021 11:08:18.071 [java] [DEBUG] 	Vowels in English language are {}. : public void setLanguageVowels(String vowelString)
12-09-2021 11:08:19.079 [java] [DEBUG] gauge-java took 9859milliseconds to load and scan. This should be less than 'runner_connection_timeout' config value.
12-09-2021 11:08:19.079 [java] [DEBUG] run 'gauge config runner_connection_timeout' and verify that it is < 9859
12-09-2021 11:08:19.079 [java] [DEBUG] starting gRPC server...
12-09-2021 11:08:24.844 [Gauge] [DEBUG] jsonrpc2: --> notif: initialized: {}
12-09-2021 11:08:24.845 [Gauge] [DEBUG] jsonrpc2: <-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"c:/Workspace/MVN/**/*{.spec,.md,.cpt}","kind":5}]}}]}
12-09-2021 11:08:25.068 [Gauge] [DEBUG] jsonrpc2: --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","languageId":"gauge","version":1,"text":"Specification Heading\n=====================\n\nThis is an executable specification file. This file follows markdown syntax.\nEvery heading in this file denotes a scenario. Every bulleted point denotes a step.\n\nTo execute this specification, run\n\tgauge specs\n\n\n* Vowels in English language are \"aeiou\".\n\nVowel counts in single word\n---------------------------\n\ntags: single word\n\n* The word \"gauge\" has \"3\" vowels.\n\n\nVowel counts in multiple word\n-----------------------------\n\nThis is the second scenario in this specification\n\nHere's a step that takes a table\n\n* Almost all words have vowels\n     |Word  |Vowel Count|\n     |------|-----------|\n     |Gauge |3          |\n     |Mingle|2          |\n     |Snap  |1          |\n     |GoCD  |1          |\n     |Rhythm|0          |\n"}}
12-09-2021 11:08:25.068 [Gauge] [DEBUG] jsonrpc2: --> request #1: gauge/getRunnerLanguage: null
12-09-2021 11:08:25.068 [Gauge] [DEBUG] jsonrpc2: --> request #2: textDocument/documentSymbol: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"}}
12-09-2021 11:08:25.068 [Gauge] [DEBUG] jsonrpc2: --> request #3: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"},"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":30}},"context":{"diagnostics":[]}}
12-09-2021 11:08:25.068 [Gauge] [DEBUG] jsonrpc2: --> notif: $/cancelRequest: {"id":3}
12-09-2021 11:08:25.069 [Gauge] [DEBUG] jsonrpc2: --> request #4: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"},"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":30}},"context":{"diagnostics":[]}}
12-09-2021 11:08:25.069 [Gauge] [DEBUG] jsonrpc2: --> notif: $/cancelRequest: {"id":4}
12-09-2021 11:08:25.069 [Gauge] [DEBUG] jsonrpc2: --> request #5: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"},"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":30}},"context":{"diagnostics":[]}}
12-09-2021 11:08:25.165 [Gauge] [DEBUG] jsonrpc2: <-- result #3: textDocument/codeAction: null
12-09-2021 11:08:25.167 [Gauge] [DEBUG] jsonrpc2: --> request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"c:/Workspace/MVN/**/*{.spec,.md,.cpt}","kind":5}]}}]}
12-09-2021 11:08:25.167 [Gauge] [DEBUG] jsonrpc2: --> request #6: textDocument/codeLens: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"}}
12-09-2021 11:08:25.183 [Gauge] [DEBUG] jsonrpc2: <-- result #5: textDocument/codeAction: null
12-09-2021 11:08:25.183 [Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP
12-09-2021 11:08:25.387 [Gauge] [DEBUG] jsonrpc2: --> notif: $/cancelRequest: {"id":5}
12-09-2021 11:08:25.861 [Gauge] [DEBUG] jsonrpc2: --> request #7: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"},"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":30}},"context":{"diagnostics":[]}}
12-09-2021 11:08:25.861 [Gauge] [DEBUG] jsonrpc2: --> request #8: textDocument/codeLens: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"}}
12-09-2021 11:08:25.867 [Gauge] [DEBUG] jsonrpc2: <-- result #4: textDocument/codeAction: null
12-09-2021 11:08:25.868 [Gauge] [DEBUG] jsonrpc2: <-- result #1: gauge/getRunnerLanguage: ""
12-09-2021 11:08:25.868 [Gauge] [DEBUG] jsonrpc2: <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","diagnostics":[]}
12-09-2021 11:08:25.868 [Gauge] [DEBUG] jsonrpc2: <-- notif: window/logMessage: {"type":1,"message":"notif #0: initialized: current runner is not compatible with gauge LSP"}
12-09-2021 11:08:25.871 [Gauge] [DEBUG] jsonrpc2: <-- result #7: textDocument/codeAction: null
12-09-2021 11:08:25.872 [Gauge] [DEBUG] jsonrpc2: <-- result #2: textDocument/documentSymbol: [{"name":"# Specification Heading","kind":3,"location":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":21}}}},{"name":"## Vowel counts in single word","kind":3,"location":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","range":{"start":{"line":12,"character":0},"end":{"line":12,"character":27}}}},{"name":"## Vowel counts in multiple word","kind":3,"location":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","range":{"start":{"line":20,"character":0},"end":{"line":20,"character":29}}}}]
12-09-2021 11:08:25.872 [Gauge] [DEBUG] jsonrpc2: <-- result #6: textDocument/codeLens: [{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:13"]}},{"range":{"start":{"line":20,"character":0},"end":{"line":20,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:21"]}},{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":8}},"command":{"title":"Run Spec","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec"]}}]
12-09-2021 11:08:25.879 [Gauge] [DEBUG] jsonrpc2: <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec","diagnostics":[]}
12-09-2021 11:08:25.881 [Gauge] [DEBUG] jsonrpc2: <-- result #8: textDocument/codeLens: [{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:13"]}},{"range":{"start":{"line":20,"character":0},"end":{"line":20,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:21"]}},{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":8}},"command":{"title":"Run Spec","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec"]}}]
12-09-2021 11:08:26.316 [java] [DEBUG] started gRPC server on port 49906
12-09-2021 11:08:34.906 [Gauge] [DEBUG] jsonrpc2: --> request #9: textDocument/codeAction: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"},"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":30}},"context":{"diagnostics":[]}}
12-09-2021 11:08:34.958 [Gauge] [DEBUG] jsonrpc2: <-- result #9: textDocument/codeAction: null
12-09-2021 11:08:36.700 [Gauge] [DEBUG] jsonrpc2: --> request #10: textDocument/codeLens: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"}}
12-09-2021 11:08:36.701 [Gauge] [DEBUG] jsonrpc2: <-- result #10: textDocument/codeLens: [{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:13"]}},{"range":{"start":{"line":20,"character":0},"end":{"line":20,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:21"]}},{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":8}},"command":{"title":"Run Spec","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec"]}}]
12-09-2021 11:08:36.703 [Gauge] [DEBUG] jsonrpc2: --> request #11: textDocument/codeLens: {"textDocument":{"uri":"file:///c%!!(MISSING)A(MISSING)/Workspace/MVN/specs/example.spec"}}
12-09-2021 11:08:36.704 [Gauge] [DEBUG] jsonrpc2: <-- result #11: textDocument/codeLens: [{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:13"]}},{"range":{"start":{"line":20,"character":0},"end":{"line":20,"character":12}},"command":{"title":"Run Scenario","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec:21"]}},{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":8}},"command":{"title":"Run Spec","command":"gauge.execute","arguments":["c:\\Workspace\\MVN\\specs\\example.spec"]}}]
12-09-2021 11:16:29.370 [Gauge] [DEBUG] jsonrpc2: --> request #12: shutdown: null
12-09-2021 11:16:29.374 [Gauge] [DEBUG] jsonrpc2: <-- result #12: shutdown: null
12-09-2021 11:16:29.423 [Gauge] [INFO] Connection closed
12-09-2021 11:16:29.423 [Gauge] [ERROR] Unable to log error 'Connection closed' to LSP: jsonrpc2: connection is closed
