### ISSUE TITLE
With circular reference in project other IDE features stop working

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#77]
**Expected behavior**
IDE features should continue to work

**Actual behavior**
In the spec adding a new unimplemented step crashes the language runner.

**Steps to replicate** 
* Project parse-errors-circular in [LSP- tests](https://github.com/getgauge/gauge-lsp-tests) test data
* in the spec file `specification.spec` add a new step
> Observation while adding a new step the red underline is not present. Further other IDE Gauge features do not work

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-13
Commit Hash: 571fda8

Plugins
-------
js (2.0.3.nightly-2017-12-15)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
