### ISSUE TITLE
Test view container of Gauge is hidden in the Activity Bar in VSCode

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-vscode#798]
### Describe the bug

When creating a new project via the  template on a new PC, the ".gauge" folder is never created, while on my old PC everything is fine.
With dotnet it works great too.
I have been with this problem for 2 days, and I can’t find the cause of the problem.

### What command(s) did you run when you found the bug?

```
Create a new Gauge Project ( Template java) 
```

![create  project](https://user-images.githubusercontent.com/59898499/142855337-c7f493e2-f8d4-4c57-a1d8-eff787411322.PNG)

### Output, stack trace or logs related to the bug

![Gauge](https://user-images.githubusercontent.com/59898499/142855102-a28c9390-1f39-4c5d-b14a-2bf0ac069342.PNG)

#### Gauge (Output of `gauge -v`)

![gauge plugins](https://user-images.githubusercontent.com/59898499/142855132-6a0e26ed-6237-43a6-94cf-56402a108156.PNG)

#### Operating System information
![jdk](https://user-images.githubusercontent.com/59898499/142855462-9f94aabf-124b-4c18-8322-8fa801875efe.PNG)

#### IDE information
![](https://user-images.githubusercontent.com/59898499/142855848-1542e0de-66d2-4b0d-a638-ed41bfa350ab.PNG)

**Comment by sriv** [comment]
The `.gauge` folder is created by `gauge` during execution, it isn't part of the template. Is there a reason you expect to see this folder?

**Comment by zbrea** [comment]
I know the folder is not part of the model, but the folder is created once the gauge plugin is initialized.
Here it is never created.
You see the PC2 screen:
- Test view container of Gauge is hidden in the Activity Bar in VSCode.
- The tests case are not displayed, 
- The run and debug button are not displayed, if as if the vscode-gauge is not is not recognized.

## PC1 

![PC_OLD](https://user-images.githubusercontent.com/59898499/142878408-72a7a7a7-2692-4895-82a6-28f041abf767.PNG)

## PC2 (New)
![PC New](https://user-images.githubusercontent.com/59898499/142878413-4eafbf58-118f-4a17-8670-3ea612cee610.PNG)

**Comment by zbrea** [comment]
I changed the title of the problem to make it clearer.
I can excuse the test via the command line but I cannot manage the test with visual studio and especially the debug mode.
In my team we received 2 new pc and both have the same problem

**Comment by zbrea** [comment]
I was able to solve my problem, I launched my VSCode as administrator, and there the whole problem is solved instantly.
It is possible that my company has restricted the rights on my PC.
Even if I did not find the exact cause but at least the use of VSCode in admin profile it solves the problem.

you can close the bug ! my friend :)

**Comment by sriv** [comment]
Thanks for sharing your notes @zbrea ! This will help future users.
