### ISSUE TITLE
Documentation for VS Code support

### ISSUE THREAD

**Issue by SreejithShenoi** [getgauge/gauge-vscode#8]
Looking for a document regarding the features supported by gauge plugin for VSCode.
Can you please guide me to the corresponding link?

**Comment by zabil** [comment]
https://docs.getgauge.io/using.html#visual-studio

**Comment by SreejithShenoi** [comment]
Hi Zabil,

This link describes about support for visual studio. My query was regarding VSCode.

**Comment by zabil** [comment]
My bad, the plugin page will have all the features listed. There won't be separate documentation.

**Comment by SreejithShenoi** [comment]
Hi Zabil,

Checked in the plugin documentation page as well, but nothing specific to VSCode is mentioned there.
Looking for what kind of support is present in VSCode at this point of time from gauge plugin for VSCode.

**Comment by zabil** [comment]
@SreejithShenoi 
https://github.com/getgauge/gauge-vscode#gauge-vscode does list the features. 

For eg.
```
Gauge extension for VSCode.

This extension adds language support for the Gauge projects, including:

    Autocomplete of steps and parameters

IDE Features :

    Snippets for specification, scenarios and tables.
```

This is the updated list. As an when we add features we will expand this section.

This will list currently supported features. Future planned features will be added to the issue list.
