### ISSUE TITLE
Extract a concept

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#82]
Show a Quick fix to generate a concept stub when a sequence of steps is selected.

### Expected behavior

* Open a spec file
* Select/highlight a series of steps
* Show the Quick fix "Extract Concept"
* On clicking extract concept the command palate lists existing concept files which can be narrowed down by typing.
* If an existing concept file is selected it adds the extracted concept to the end of the file
* For a new concept file type the name of the file in the command palate text box and press "enter"

**Comment by sguptatw** [comment]
**Question**
If the same steps are present in other specifications or concepts, should that also get replaced with the new concept?

**Comment by BugDiver** [comment]
The fix should be available in following nightlies :

* Gauge 2018-03-01
* Gauge-Vscode 2018-03-01

**Comment by zabil** [comment]
Please change this functionality as follows.

* Remove the extract to concept quick fix
* When the user writes a step that is not implemented we show 2 quick fixes
    * Implement as concept
    * Generate step implementation stub
* When the user chooses "Implement as concept" and quick pick `New File` a `.cpt` file with using the step text for e.g. if the step is `* Authenticate user` create a file `autheticate-user.cpt` and use `Authenticate user` as the concept heading.
* The user must be able to pick an existing concept file too.

**Comment by BugDiver** [comment]
This functionality is removed from the current scope. A new feature `Implement concept` is proposed.  Please Refer #192
