### ISSUE TITLE
Support for Ruby Language

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-vscode#85]
### Expected behavior
Support features that currently works only on javascript.

* Goto definition
* Find step references
* Generate implementation stub
* etc
  
Ref: https://github.com/getgauge/gauge-ruby/issues/47

**Comment by BugDiver** [comment]
Should be available in nightlies
* Gauge - 17-01-2018
* Gauge-Ruby 17-01-2018

**Comment by sguptatw** [comment]
Gauge nightly 17-01-2018 not available

**Comment by BugDiver** [comment]
@sguptatw  My bad. It's available in Gauge nightly 16-01-2018

**Comment by sguptatw** [comment]
**Issues**
* Find usages should be displayed on implementation - https://github.com/getgauge/gauge-ruby/issues/53
* Validation errors - https://github.com/getgauge/gauge-ruby/issues/52

**Comment by sguptatw** [comment]
**Test Cases**
- [x] Find usages of steps
- [ ] Find usages of alias
- [x] Goto definition of step
- [x] Goto definition of unimplemented step
- [x] Autocomplete of steps
- [x] Autocomplete of implemented but unused step
- [x] Generate stub implementation

**Comment by sguptatw** [comment]
Refactoring will be taken up as a separate card
