### ISSUE TITLE
Version of ts-node causes error `The Gauge server crashed 5 times in the last 3 minutes. The server will not be restarted.`

### ISSUE THREAD

**Issue by mizuochi-hikaru** [getgauge/gauge-vscode#885]
### Describe the bug
I encountered #636 and #759, and I found below.

| template-ts version | gauge-vscode can start |
|:--------------------|:------------------------|
| 0.9.0(latest)              | 🙅                                    |
| 0.8.0                          | 🙅                                    |
| 0.7.0                           | 🙆 OK!                            |

I get `diff` between two templates, `0.8.0` and `0.7.0`.
```diff
Common subdirectories: template-ts-0.0.7/.github and template-ts-0.0.8/.github
Common subdirectories: template-ts-0.0.7/env and template-ts-0.0.8/env
diff --color template-ts-0.0.7/metadata.json template-ts-0.0.8/metadata.json
4c4
<   "version": "0.0.7",
---
>   "version": "0.0.8",
diff --color template-ts-0.0.7/package.json template-ts-0.0.8/package.json
6c6
<     "ts-node": "^8.7.0",
---
>     "ts-node": "^10.4.0",
Common subdirectories: template-ts-0.0.7/specs and template-ts-0.0.8/specs
Common subdirectories: template-ts-0.0.7/tests and template-ts-0.0.8/tests
```

Therefore, as for title,  I can say that version of ts-node causes error.
As a side note, version of gauge-ts and typescript has no effect on this error.

### What command(s) did you run when you found the bug?

Open gauge-ts project in VSCode.

### Output, stack trace or logs related to the bug

See #636 and #759.

#### Gauge (Output of `gauge -v`)
```
Gauge version: 1.5.4
Plugins
-------
dotnet (0.5.2)
html-report (4.2.0)
java (0.10.2)
js (3.0.1)
screenshot (0.1.0)
ts (0.1.0)
```

#### Node.js/Java/Python/.Net/Ruby version
```shell
$ node -v
v20.5.0
```
_This is NOT used in VSCode._

#### Operating System information
Macbook Pro 2020 (Intel Chip)
Ventura 13.5.1

#### IDE information
```
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0
```

**Comment by chadlwilson** [comment]
Hopefully fixed by https://github.com/getgauge/gauge/pull/2422 in Gauge `1.5.6` - we can re-open if it turns out not to be the case.

**Comment by mizuochi-hikaru** [comment]
@chadlwilson 
I updated and checked and it was OK!
Thank you for your support!

**Comment by chadlwilson** [comment]
All credit and thanks goes to @bockstaller on this one; I'm just clicking some buttons to get the automation through :-)
