### ISSUE TITLE
Display Issue in gauge-vscode v0.1.4: Absence of 'Run Scenario' and 'Debug Scenario' Labels

### ISSUE THREAD

**Issue by Smaiik** [getgauge/gauge-vscode#900]
### Describe the bug
gauge-vscode v0.1.4 is not working correctly because the labels "Run Scenario" and "Debug Scenario" no longer appear. I have tried several times, but nothing is displayed. However, once I reinstall the old version gauge-vscode v0.1.0, everything works correctly! (see associated screenshots)

<img width="853" alt="KO-v0 1 4" src="https://github.com/getgauge/gauge-vscode/assets/144631369/6c6ea087-946b-453c-860d-9b9e3fbb63ca">
<img width="885" alt="OK-v0 1 0" src="https://github.com/getgauge/gauge-vscode/assets/144631369/15a51fda-3424-4fce-b68f-d988566c1f48">

#### Gauge (Output of `gauge -v`)
Gauge version: 1.5.6
Commit Hash: 9b96118

Plugins
-------
confluence (0.18.4)
dotnet (0.5.2)
html-report (4.2.0)
inprogress (0.4.0)
java (0.10.3)

#### Java version 
"11.0.15" 2022-04-19 LTS#### Operating System information

**Comment by chadlwilson** [comment]
Thx for the report. I trust the downgrade worked fine? Which VS Code version are you using on which OS?

**Comment by Smaiik** [comment]
Thank you for your quick response and your promptness. Here are the requested details :
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
![image](https://github.com/getgauge/gauge-vscode/assets/144631369/f66a8b35-cb3f-4d1c-b832-64287b07598d)

**Comment by chadlwilson** [comment]
Yeah, something is not right here. I don't actively use vscode so am not such an expert here, but even for specs using the alternate syntax, the CodeLens labels appear initially and then disappear after editing a spec.

I'm not sure what might have changed here, certainly nothing intentional. Is this something you've seen, by chance @bockstaller ?

**Comment by jensakejohansson** [comment]
This happend to me too. For some reason I didn't check the version of the plugin, so I wasted alot of time even completely re-installing VSCode before realising there was a new no-working version of the plugin. Thanks @Smaiik for bringing this to my attention!

**Comment by bockstaller** [comment]
It feels like the vscode to gauge communication isn't working.
Which is strange because all of the Java specific parts should be hidden away.

It's difficult to pinpoint without an lsp.log file.

**Comment by jensakejohansson** [comment]
To be clear I'm working with C#/dotnet 6. There is not even an lsp.log file created when using the new version. Simple to reproduce:

1. Install the new version of the plugin.
2. Create a new project: "gauge init dotnet".
3. Open the project folder in VSC. The plugin appears "dead", lsp.log not created and no options to run tests, "intellisense" in spec/concept-files or anything.

**Comment by chadlwilson** [comment]
I'm not sure if I have the same root cause as others as I am getting a whole lot of errors even with `0.1.0`, even though the symptoms are similar (crashing gauge server, no useful logs). Will try and fix my env first.

**Comment by bockstaller** [comment]
I used the setup new project functionality and created both a java and a dotnet project (both with SDK 6.0.319 and 7.0.403).
All versions work fine on my Mac M2 Pro. 


```bash
> gauge -v

Gauge version: 1.5.6
Plugins
-------
dotnet (0.5.2)
html-report (4.2.0)
java (0.10.3)
js (4.0.0)
python (0.4.1)
ruby (0.7.0)
screenshot (0.1.0)
ts (0.1.1)
xml-report (0.4.0)
```

```bash
> code -v

1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
arm64
```

```bash
> dotnet --list-sdks

6.0.319 [/usr/local/share/dotnet/sdk]
7.0.403 [/usr/local/share/dotnet/sdk]
```

```bash 
> java --version

openjdk 21 2023-09-19
OpenJDK Runtime Environment Homebrew (build 21)
OpenJDK 64-Bit Server VM Homebrew (build 21, mixed mode, sharing)
```

**Comment by Smaiik** [comment]
When I delete the automatically generated folders when opening a gauge project with VScode, the .gauge and logs folders are never generated using gauge version vscode-0.1.4 whereas with version 0.1.4 they are generated correctly and everything works correctly.
Note: in our organization we are required to launch VScode as administrator.
![O](https://github.com/getgauge/gauge-vscode/assets/144631369/c80419d8-557d-4108-bc6b-8a36a68c8d98)

**Comment by bockstaller** [comment]
What happens when you manually run `gauge validate` and `gauge run`

**Comment by Smaiik** [comment]
![gauge](https://github.com/getgauge/gauge-vscode/assets/144631369/74af3fd1-ab7a-4c8f-b69e-0915fbc07316)
with :
![image](https://github.com/getgauge/gauge-vscode/assets/144631369/53912c9c-3e36-4206-b9af-4adc62887f6b)

**Comment by bockstaller** [comment]
Looking at https://github.com/getgauge/gauge/issues/2431 it seems like windows users are affected.
I gather from this logline
`13-11-2023 11:16:51.791 [python] [ERROR] '"C:\Program Files\Python310\python.exe -m pip install getgauge==0.4.1 --user"' is not recognized as an internal or external command,`
that

1. VScode is starting vscode-gauge
2. vscode-gauge starts gauge
3. gauge correctly identifies the language plugin to use
4. gauge starts [start.sh](https://github.com/getgauge/gauge-python/blob/master/start.bat) 
5. start.bat starts [check_and_install_getgauge.py](https://github.com/getgauge/gauge-python/blob/master/check_and_install_getgauge.py)
6. there it fails because it cannot resolve(?) the command

This feels like a path issue to me, even if I don't have a clue how it could've been introduced.

@EGTomKies It may be interesting to output the available path in `start.bat` or `check_and_install_getgauge.py`, to see if this is the case.
The plugins are located in the home directory at `.gauge/plugins`. Editing `start.bat` there should take effect directly.

**Comment by nablik** [comment]
Same here, with 
Gauge version: 1.4.3
Commit Hash: f98dd40

Plugins
-------
dotnet (0.5.1)
html-report (4.2.0)
xml-report (0.3.1)


and VS plugin 0.1.4 is not working. rolling back to 0.1.0 works.

**Comment by jensakejohansson** [comment]
@bockstaller Yes, I saw a similar Python error in VSC when I tried 0.1.4., so your on to something there.

**Comment by sriv** [comment]
Funnily enough, when I can see this issue on a windows machine with gauge 1.5.6 and gauge-vscode 0.1.4 on a dotnet project. There are no logs or anything (my suspicion is that for some reason the gauge LSP server isnt started up).

But what's strange is that when I launch it from code of gauge-vscode, it worked. When I did a new build locally, it worked. But when I install the vsix from gauge-vscode releases, it didn't work. 

Not sure what's causing this.. will try to investigate further.

**Comment by EGTomKies** [comment]
@bockstaller  My apologies, which variable were you looking for?   

I wonder if it has anything to do with the default command line/terminal on the user's machine.   I ran this in cmd and it works fine: 

"C:\Program Files\Python310\python.exe" -m pip install getgauge==0.1.4 --user

but if I run the same in PowerShell (which I lean towards) I get this: 

![image](https://github.com/getgauge/gauge-vscode/assets/55757738/d2df2d06-441f-4dd4-8eff-26c500dc46d4)


My default for the terminal window in VSC is Powershell.

**Comment by EGTomKies** [comment]
Just as an amusing addendum, I'd forgotten I updated getgauge from the command line to 0.4.1 this morning, and when I went to run a test from within VSC, I hit: 

```
'"C:\Program Files\Python310\python.exe -m pip install getgauge==0.4.1 --user"' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
File "C:\Users\tom.kies\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 40, in <module>
assert_versions()
File "C:\Users\tom.kies\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 34, in assert_versions
install_getgauge("getgauge=="+expected_gauge_version)
File "C:\Users\tom.kies\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 20, in install_getgauge
check_output([" ".join(install_cmd)], shell=True)
File "C:\Program Files\Python310\lib\subprocess.py", line 420, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\Program Files\Python310\lib\subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Python310\\python.exe -m pip install getgauge==0.4.1 --user']' returned non-zero exit status 1.
Traceback (most recent call last):
File "C:\Users\tom.kies\AppData\Roaming\gauge\plugins\python\0.4.1\start.py", line 11, in <module>
from getgauge import handlers, logger, processor
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\getgauge\processor.py", line 4, in <module>
from getgauge.executor import set_response_values, execute_method, run_hook
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\getgauge\executor.py", line 7, in <module>
from getgauge.messages.messages_pb2 import Message
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\getgauge\messages\messages_pb2.py", line 8, in <module>
from google.protobuf import reflection as _reflection
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\google\protobuf\reflection.py", line 58, in <module>
from google.protobuf.internal import python_message as message_impl
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\google\protobuf\internal\python_message.py", line 62, in <module>
from google.protobuf.internal import containers
File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\google\protobuf\internal\containers.py", line 182, in <module>
MutableMapping = collections.MutableMapping
AttributeError:
module 'collections' has no attribute 'MutableMapping'
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	windows, 1.5.6, 9b96118
	html-report (4.2.0), json-report (0.3.7), python (0.4.1), screenshot (0.1.0), spectacle (0.1.4), xml-report (0.4.0)
Error: Tests failed.

```

**Comment by zabil** [comment]
@EGTomKies can you try running the code on python 3.9 from the stack you posted this seems to be an issue with one of the dependencies that gauge uses (protocol buffers) not being compatible with python 3.10

**Comment by EGTomKies** [comment]
@zabil We had that package limited in our requirements.txt file, though I don't recall why offhand; I think it was a problem with an interaction with opencv or PIL.   

I have meetings for the rest of the morning, but after lunch I can try both running with the latest protobuf, but also pull down python 3.9 and give it a shot as well.

**Comment by EGTomKies** [comment]
With python 3.10, I ran our requirements.txt file with the version limiter removed for protobuf.  

I updated to the latest Gauge extension, 0.1.4
The links still aren't visible.  

There's no lsp.log generated.  


I installed Python 3.9, set it as the Python Interpreter within VSC and restarted, but the links still don't show, and there's no lsp.log created.  

On a whim, I also changed my default for Windows Terminal from Powershell to cmd, and reopened VSC on the off chance there's a tight integration there, but there are still no links, and no lsp.log generated.

**Comment by theothermountain** [comment]
I have the same issue with Java. 
In exthost log, I found an error. But I am not sure the URL path for which file is in error.

2023-11-15 10:59:43.884 [error] Activating extension getgauge.gauge failed due to an error:
2023-11-15 10:59:43.884 [error] TypeError: File URL path must be absolute
	at new NodeError (node:internal/errors:399:5)
	at getPathFromURLWin32 (node:internal/url:1464:11)
	at fileURLToPath (node:internal/url:1496:22)
	at 8718 (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:536982)
	at n (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:539573)
	at 3495 (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:67226)
	at n (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:539573)
	at 112 (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:103099)
	at n (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:539573)
	at c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:539940
	at Object.<anonymous> (c:\Users\shengli.li\.vscode\extensions\getgauge.gauge-0.1.4\out\extension.js:1:539965)
	at o._compile (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at h.vb (c:\Users\shengli.li\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:30610)
	at async Promise.all (index 0)

**Comment by RedEyePilot** [comment]
Same issue with VSCode plugin here. Rolled back to 0.1.0 and the Run links reappeared

**Comment by sschulz92** [comment]
We have the same issue with VS Code, using Python 3.10.9.

```
$ gauge -v
Gauge version: 1.5.4
Commit Hash: 30a0c23

Plugins
-------
html-report (4.2.0)
json-report (0.3.7)
python (0.4.1)
```

**Comment by chadlwilson** [comment]
I am not sure about the Python errors or some of the other noise above - I am disinclined to focus on anything single language as others have commented about it not working with other languages alone (Java, dotnet).

The main issue seems to be that the extension doesn't load at all on windows, as noted from the extension host log in https://github.com/getgauge/gauge-vscode/issues/900#issuecomment-1812818137 which I can also replicate in Windows

```
2023-11-15 10:59:43.884 [error] Activating extension getgauge.gauge failed due to an error:
2023-11-15 10:59:43.884 [error] TypeError: File URL path must be absolute
at new NodeError (node:internal/errors:399:5)
at getPathFromURLWin32 (node:internal/url:1464:11)
at fileURLToPath (node:internal/url:1496:22)
```

```js
const kt=p.dirname((0,m.fileURLToPath)("file:///home/runner/work/gauge-vscode/gauge-vscode/node_modules/clipboardy/lib/windows.js"))
```

This problem appears to be the upgrade to clipboardy at https://github.com/getgauge/gauge-vscode/commit/0c8837095771bf6080af3b55d148aa96038453fc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L481-R481 which brought in [this change here](https://github.com/sindresorhus/clipboardy/compare/v2.3.0...v4.0.0#diff-26b75a635f124d2b9e6537c2b58d8cc31420031b1233cafa420bc1e57bff7a99R1-R8) which just doesn't work properly right now. Webpack is including a URL generated at compile time (which makes no sense) due to https://github.com/webpack/webpack/issues/14445 and I am not sure what actually makes sense to do here for a VS Code extension .

With clipboardy downgraded back to `2.3.0` the plugin seems to at least load on Windows so let's see if we get further with that.

I don't know how/why the Windows-based tests still seem to pass on the extension earlier though.

**Comment by chadlwilson** [comment]
If someone wants to help validate with [gauge-0.1.5.zip](https://github.com/getgauge/gauge-vscode/files/13376493/gauge-0.1.5.zip) (rename to `.vsix`) that might help.

**Comment by chadlwilson** [comment]
Hey folks - please give https://github.com/getgauge/gauge-vscode/releases/tag/v0.1.5 a go via https://marketplace.visualstudio.com/items?itemName=getgauge.gauge and let us know if you still have any problems (especially specific to Windows) and we can re-open this, or open a new issue as suitable.
