### ISSUE TITLE
Does the vs code gauge support .net 8 gauge repo now?

### ISSUE THREAD

**Issue by GavinSun9527** [getgauge/gauge-vscode#945]
I have a gauge test project and use the .NET framework and it 's worked, today I tried to upgrade gauge repo to .NET 8 , and upgrade is success , build success ,  I want to us vs code to run&debug the spec file, but when I open the repo with VS code, I got this error message, do you know which plugins version is incorrect?

There are version incompatibilities between Gauge and it's plugins in this project. Some features will not work as expected.

vs code gauge extension version: v0.1.6
local installed gauge version: 1.4.3

**Comment by chadlwilson** [comment]
Start by updating Gauge to the latest version? Gauge `1.4.3` is over two years old, that plugin version is the latest version.

**Comment by GavinSun9527** [comment]
Hi @chadlwilson 
I have updated to Gauge 1.6.6, but it still has the same issue

**Comment by GavinSun9527** [comment]
Hi @chadlwilson 
and I tried click run Scenario ,  I will got these message from output 

Running tool: gauge.cmd run --hide-suggestion --simple-console c:\xxxxxxxxx (mark)\ProcessPaymentTests.spec:9
Building project: c:\xxxxxxxxxxxxxx.Gauge.Tests.csproj
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  c:\xxxxxxxxxxxx.Tests.csproj /t:Build /m  /nodeReuse:False  /v:q    /p:RestorePackages="False" /p:OutputPath="c:\xxxxxxxxxx\gauge_bin" /p:Platform="Any CPU" /p:Configuration="Debug" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\gsun\AppData\Roaming\gauge\plugins\csharp\0.10.6\bin\FakeLib.dll"
Microsoft (R) Build Engine version 4.8.9037.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.
c:\xxxxxxxxxxxxxxxxx.Gauge.Tests.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 f
