### ISSUE TITLE
Error in Run in parallel

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#95]
**Expected behavior**
By clicking on the `Run in parallel`, I should be able to run specs in parallel.

**Actual behavior**
Getting error 
<img width="701" alt="inparallel" src="https://user-images.githubusercontent.com/6310197/34974503-68ce87f4-fab3-11e7-800b-9815e83c3b1a.png">

**Steps to replicate**
* Create a gauge js project
* In example spec add a data table as shown above.
* Click on run in parallel

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-15
Commit Hash: 15c9822

Plugins
-------
js (2.1.1.nightly-2018-01-15)
```

**Comment by sguptatw** [comment]
Run in parallel is not working for a basic js project.

**Comment by Apoorva-GA** [comment]
Fix should be available in vscode nightly >= 17/01/18
