### ISSUE TITLE
Add propertie configuration to run the test case by ./venv/Script/python (Window 10 or 11)

### ISSUE THREAD

**Issue by ZurdenRo** [getgauge/gauge-vscode#951]
### Describe the bug
I found, when you click `run scenario` from spec file. The extension didn't use the bin python in `./venv/` folder. Used the bin python from `AppData` in Window 10.

### What command(s) did you run when you found the bug?
Only click in `run scenario` in spec file.

### Output, stack trace or logs related to the bug
```
Traceback (most recent call last):
File "C:\Users\name\AppData\Roaming\gauge\plugins\python\0.4.3\check_and_install_getgauge.py", line 5, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
File "C:\Users\name\AppData\Roaming\gauge\plugins\python\0.4.3\start.py", line 9, in <module>
import grpc
ModuleNotFoundError:
No module named 'grpc'
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------
```
### Versions
Gauge version: 1.6.6
Commit Hash: 209816e

Plugins
-------
html-report (4.3.1)
python (0.4.3)
screenshot (0.2.0)
#### Python
Python 3.11.5
#### Operating System information
Window 10
#### IDE information
VS code:
v: 1.88.1
chromium: 120.0.60
Nodejs: 18.18.2
OS: window x64

**Comment by chadlwilson** [comment]
I believe this has been solved, according to https://github.com/getgauge/gauge-python/issues/343#issuecomment-2073838518
