### ISSUE TITLE
[Workspace] IDE feature should work when project names are similar

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#96]
**Expected behavior**
IDE Features should work irrespective of project names

**Actual behavior**
When one project name is a subset of the other. Example `something` and `something-else`. The following issues occur

* Find usages display wrong details
<img width="497" alt="findusages" src="https://user-images.githubusercontent.com/6310197/34973086-ab97dbc4-faab-11e7-989b-b4bf1c1cb97e.png">
* Code lens appears twice
<img width="409" alt="codelens" src="https://user-images.githubusercontent.com/6310197/34972788-d886c08e-faa9-11e7-9b0c-1e0860372f83.png">

* Autocomplete is not limited to elements in workspace

* Duplicate step implementation is displayed for steps across projects in workspace

**Steps to replicate**
* Create project `one`. `gauge init js`
* Create another project `onemore` `gauge init js`
* Add both to one workspace
* Observe the above issues

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-15
Commit Hash: 15c9822

Plugins
-------
js (2.1.1.nightly-2018-01-15)
```

**Comment by Apoorva-GA** [comment]
Raised an [issue](https://github.com/Microsoft/vscode/issues/41724) in vscode.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge and vscode nightly >= 19/01/18

**Comment by sguptatw** [comment]
Seems like VSCode is giving a fix for the raised [issue](https://github.com/Microsoft/vscode/issues/41724) in vscode. We should take a re-look after their fix.

**Comment by Apoorva-GA** [comment]
VSCode has released a fix for this issue.
Please test with insider Version 1.20.0-insider.(60440c72461e96893766bce73d7bdf1f5136a19f) release on 2018-01-23.

**Comment by sguptatw** [comment]
Trying to get the insider version from - https://code.visualstudio.com/insiders/. The latest available one is 1.19.0

**Comment by sguptatw** [comment]
Code Lens appear only once. With `Find Usages` statistics are displayed correctly.
However
* Clicking on the usage statistics does not list the usages.

**Comment by sguptatw** [comment]
Working in VSCode - 
```
Version 1.20.0-insider
Commit 757ff83f0dece1ecf43d3a92e91fe467de1cc9dc
Date 2018-01-29T05:13:39.772Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by sguptatw** [comment]
**Issue**
Ruby projects are not working as expected in this Insider version - https://github.com/getgauge/gauge-vscode/issues/116
