### ISSUE TITLE
Removing a project from workspace gives error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#98]
Allows adding the parent folder of a gauge project. But removing it gives an error
<img width="672" alt="description_undefined" src="https://user-images.githubusercontent.com/6310197/35027352-402588d4-fb76-11e7-8143-db9101f5fab4.png">

**Steps to replicate**
* In [LSP Tests](github.com/getgauge/gauge-lsp-tests). Open workspace `data\testdata.code-workspace`.
* Add folder `parse-errors`.
* Remove `parse-errors` from the workspace.
> Note the error

**Version**
VSCode - gauge-0.0.4.nightly-2018-01-16.vsix

**Comment by Apoorva-GA** [comment]
Issue is not replicable.
